#!/bin/bash

# Setting for k-coefficient calculation
SP_ID="dsa_mars"
SOLAR_SPEC="sun"
PT_FILE="pt793"
NBANDS="36"

# For a 10 bar atmosphere
COL_H2O="1.0e+03" 
COL_CO2="1.0e+05" # 1e6 ppmv in a 10 bar atmosphere
COL_H2OC="100.0" # 10 bar atmosphere
COL_CO2C="1.0e6" # 1e6 ppmv in a 10 bar atmosphere

. ../set_paths_sw

# This script creates the 6 band SW spectral file sp_sw_6_jm2
# from scratch using HITRAN database files available in August 2013.
# The following files (available from www.cfa.harvard.edu/hitran)
# are required in HITRAN_DIR (set to your local HITRAN directory):

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"

# Water vapour continuum uses CAVIAR data contained within the
# suite ($RAD_DATA/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script should be run after the LbL files have been created
# by running the script for the 260 band file.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

ref_pt_file="$RAD_DATA/gases/ref_pt"

# Create skeleton spectral file
specfile="sp_sw_${NBANDS}_${SP_ID}_skel"
rm -f $specfile
. mk_sp_sw_${NBANDS}_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

# Construct weight argument
WGT="+S ${SOLAR_SPEC_DIR}/${SOLAR_SPEC}"

# Hadgem bands ->  220        ->  260 bands:
#            1 ->    1 -  38  ->  1/6 -  29
#            2 ->   38 -  91  ->   30 -  66
#            3 ->   91 - 118  ->   67 - 103
#            4 ->  118 - 148  ->  104 - 154
#            5 ->  148 - 188  ->  155 - 214
#            6 ->  188 - 220  ->  215 - 260

# Gases

echo "Jobs running in background:"
# Increased band 5 precision from 3e-3 to 4e-3
if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_4l ] ; then
  echo "CO2 band 4"
  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 4 11 -c 50000.0 -i 1.0 -l 2 ${COL_CO2} -t 4.0e-3  \
    -sb gas_fractions -lp 2 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBANDS}_4l -m ${K_COEFF_DIR}/co2_s${NBANDS}_4lm \
    -L $SW_DATA/co2_sblbl_sw_${PT_FILE}_gf1.0.nc > \
    ${K_COEFF_DIR}/co2_s${NBANDS}_4log \
    && echo "CO2 band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_5l ] ; then
  echo "CO2 band 5"
  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 12 25 -c 50000.0 -i 1.0 -l 2 ${COL_CO2} -t 4.0e-3  \
    -sb gas_fractions -lp 2 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBANDS}_5l -m ${K_COEFF_DIR}/co2_s${NBANDS}_5lm \
    -L $SW_DATA/co2_sblbl_sw_${PT_FILE}_gf1.0.nc > \
    ${K_COEFF_DIR}/co2_s${NBANDS}_5log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_6l ] ; then
  echo "CO2 band 6"
  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 26 ${NBANDS} -c 50000.0 -i 1.0 -l 2 ${COL_CO2} -t 6.0e-3  \
    -sb gas_fractions -lp 2 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBANDS}_6l -m ${K_COEFF_DIR}/co2_s${NBANDS}_6lm \
    -L $SW_DATA/co2_sblbl_sw_${PT_FILE}_gf1.0.nc > \
    ${K_COEFF_DIR}/co2_s${NBANDS}_6log \
    && echo "CO2 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_2l ] || \
    [ ! -s $SW_DATA/h2o_lbl_vis_${PT_FILE}.nc ] ; then
  echo "H2O lines band 2"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 2 2 -c 2500.0 -i 1.0 -l 1 ${COL_H2O} -n 1 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_2l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_2lm \
    -L $SW_DATA/h2o_lbl_vis_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/h2o_s${NBANDS}_2log && echo "H2O lines band 2 done" &
fi

echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_3l ] ; then
  echo "H2O lines band 3"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_3l*
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 3 3 -c 2500.0 -i 1.0 -l 1 ${COL_H2O} -n 2  \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_3l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_3lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_3log \
    && echo "H2O lines band 3 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_4l ] ; then
  echo "H2O lines band 4"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 4 11 -c 2500.0 -i 1.0 -l 1 ${COL_H2O} -t 6.0e-3  \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_4l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_4lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_4log \
    && echo "H2O lines band 4 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_5l ] ; then
  echo "H2O lines band 5"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 12 25 -c 2500.0 -i 1.0 -l 1 ${COL_H2O} -t 6.0e-3  \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_5l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_5lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_5log \
    && echo "H2O lines band 5 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_6l ] ; then
  echo "H2O lines band 6"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 26 ${NBANDS} -c 2500.0 -i 1.0 -l 1 ${COL_H2O} -t 6.0e-3  \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_6l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_6lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_6log \
    && echo "H2O lines band 6 done"
fi

if [ ! -s ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c*
  Ccorr_k -F ../pt_cont \
    -R 3 ${NBANDS} -i 1.0 -ct 1 1 ${COL_H2OC} -t 1.0e-3 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c \
    -m ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6cm \
    -L $SW_DATA/h2o-h2o_lbl_sw.nc \
    -lw ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6clog \
    && echo "H2O self-broadened continuum done"
fi

if [ ! -s ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6c ] ; then
  echo "CO2-CO2 CIA"
  rm -f ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/co2-co2.cia \
    -R 26 ${NBANDS} -i 1.0 \
    -ct 2 2 ${COL_CO2C} -t 1.0e-2 \
    -k -s $specfile +p -lk \
    -o ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6c \
    -m ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6cm \
    -L $SW_DATA/co2-co2_lbl_sw.nc \
    > ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6clog \
    && echo "CO2-CO2 CIA done"
fi

wait

echo "All done"

exit 0
