#!/bin/bash

# Import parameters
. $1

. ../set_paths_sw

# Create full path to spectral file
SPEC_FILE="${SPEC_FILE_DIR}/sp_sw_${NBAND}_${SP_ID}_${SOLAR_SPEC}"

mkdir -p ${SPEC_FILE_DIR}
rm -f ${SPEC_FILE}
rm -f ${SPEC_FILE}_k

# Construct spectral file with gases
prep_spec << EOF
sp_sw_${NBAND}_${SP_ID}_skel
n
${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_v${NBAND}_l
5
y
${K_COEFF_DIR}/h2o_s${NBAND}_l
19
${K_COEFF_DIR}/h2o-h2o_s${NBAND}_c
5
y
${K_COEFF_DIR}/co2_s${NBAND}_l
19
y
${K_COEFF_DIR}/co2-co2_s${NBAND}_c
-1
EOF

# Add cloud fits to spectral file
# prep_spec << EOF
# ${SPEC_FILE}
# a
# 10
# 5
# ${CLD_COEFF_DIR}/fit_sw_drop5_${NBAND}
# 1.70000E-06 5.00000E-05
# 12
# 8
# ${CLD_COEFF_DIR}/fit_sw_ice8_${NBAND}
# 8.00000E-06 3.00000E-04
# -1
# EOF

# Add solar spectrum and Rayleigh scattering coefficients
prep_spec << EOF
${SPEC_FILE}
a
2
n
${SOLAR_SPEC_DIR}/${SOLAR_SPEC}
y
3
c
a
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
tidy_90 << EOF
${SPEC_FILE}
o
1
${COL_MASS_ELIM_H2O}
${COL_MASS_ELIM_CO2}
0.0
0.0
${COL_H2OC}
${COL_CO2C}
0.999990
6
${COL_MASS_STMJ_H2O}
${COL_MASS_STMJ_CO2}
0.0
0.0
${COL_H2OC}
${COL_CO2C}
n
8
1
0
-1
EOF

exit 0
