#!/bin/bash

# Setting for k-coefficient calculation
SP_ID="dsa_mars"
SP_FLDR="dsa_mars"
NBANDS="36"
SOLAR_SPEC="pc"
PT_FILE="pt793"
TOL="-b 1.0e-3"
BAND_NIR_START="3" # 5.000000000E-07 m

# For molecules with near-IR absorption, the index of the first band for which
# to calculate absorption
BAND_FIRST_H2O="2"  # 25710 cm-1 = 3.88953714507973e-07 m
BAND_FIRST_CO2="4" # 12784 cm-1 = 7.82224331232518e-07 m

# Column masses for all molecules for k-coefficient calculation
COL_MASS_K_H2O="1.0e+03"
COL_H2OC="100.0"
COL_MASS_K_CO2="1.0e+05"
COL_CO2C="1.0e6"

# Column masses for all molecules for eliminating weak absorbers
COL_MASS_ELIM_H2O=${COL_MASS_K_H2O}
COL_MASS_ELIM_CO2=${COL_MASS_K_CO2}

# Column masses for all molecules for sorting absorbers
COL_MASS_STMJ_H2O=${COL_MASS_K_H2O}
COL_MASS_STMJ_CO2=${COL_MASS_K_CO2}
