#!/bin/bash

NBANDS="250" # Number of bands
SP_ID="dsa_titan" # Spectral file ID
PT_FILE="pt_titan" # P-T grid
PT_CONT="pt_cont_titan" # T grid continuum

# N2-dominated, up to 5% CH4, 1% H2
COL_CH4="6e+2"
COL_N2_CH4="4e+3"
COL_N2_N2="2e+5"
COL_N2_H2="1e+2"

. ../set_paths_lw

################################################################################
# Calculate k-coefficients
################################################################################

echo "Calculating k-coefficients."

# Set paths to files
HITRAN_CH4="${HITRAN_DIR}/06_hit12.par"

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Create skeleton spectral file
SPECFILE="sp_lw_${NBANDS}_${SP_ID}_skel"
rm -f ${SPECFILE}
. mk_sp_lw_${NBANDS}_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/ch4_l${NBANDS}_l ] || \
    [ ! -s ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc ] ; then
  echo "CH4"
  rm -f ${K_COEFF_DIR}/ch4_l${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D ${HITRAN_CH4} -np 40 \
    -R 1 ${NBANDS} -c 2500.0 -i 0.02 -l 6 ${COL_CH4} \
    -b 1.0e-3 -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBANDS}_l -m ${K_COEFF_DIR}/ch4_l${NBANDS}_lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBANDS}_log && echo "CH4 done" &
fi

if [ ! -s ${K_COEFF_DIR}/n2-ch4_l${NBANDS}_c ] || \
    [ ! -s ${ABS_COEFF_DIR}/n2-ch4_lbl_lw.nc ] ; then
  echo "N2-CH4 CIA"
  rm -f ${K_COEFF_DIR}/n2-ch4_l${NBANDS}_c*
  Ccorr_k -F ../${PT_CONT} -CIA ${CONT_DIR}/n2-ch4_2011.cia \
    -R 1 ${NBANDS} -i 1.0 \
    -ct 13 6 ${COL_N2_CH4} -t 1.0e-3 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2-ch4_l${NBANDS}_c \
    -m ${K_COEFF_DIR}/n2-ch4_l${NBANDS}_cm \
    -L ${ABS_COEFF_DIR}/n2-ch4_lbl_lw_${PT_CONT}.nc \
     > ${K_COEFF_DIR}/n2-ch4_l${NBANDS}_clog \
     && echo "N2-CH4 CIA done" &
fi

if [ ! -s ${K_COEFF_DIR}/n2-n2_l${NBANDS}_c ] || \
    [ ! -s ${ABS_COEFF_DIR}/n2-n2_lbl_lw.nc ] ; then
  echo "N2-N2 CIA"
  rm -f ${K_COEFF_DIR}/n2-n2_l${NBANDS}_c*
  Ccorr_k -F ../${PT_CONT} -CIA ${CONT_DIR}/n2-n2_2011_clean.cia \
    -R 1 ${NBANDS} -i 1.0 \
    -ct 13 13 ${COL_N2_N2} -t 1.0e-3 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2-n2_l${NBANDS}_c \
    -m ${K_COEFF_DIR}/n2-n2_l${NBANDS}_cm \
    -L ${ABS_COEFF_DIR}/n2-n2_lbl_lw_${PT_CONT}.nc \
     > ${K_COEFF_DIR}/n2-n2_l${NBANDS}_clog \
     && echo "N2-N2 CIA done" &
fi

if [ ! -s ${K_COEFF_DIR}/n2-h2_l${NBANDS}_c ] || \
    [ ! -s ${ABS_COEFF_DIR}/n2-h2_lbl_lw.nc ] ; then
  echo "N2-H2 CIA"
  rm -f ${K_COEFF_DIR}/n2-h2_l${NBANDS}_c*
  Ccorr_k -F ../${PT_CONT} -CIA ${CONT_DIR}/n2-h2_2011.cia \
    -R 1 ${NBANDS} -i 1.0 \
    -ct 13 23 ${COL_N2_H2} -t 1.0e-3 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2-h2_l${NBANDS}_c \
    -m ${K_COEFF_DIR}/n2-h2_l${NBANDS}_cm \
    -L ${ABS_COEFF_DIR}/n2-h2_lbl_lw_${PT_CONT}.nc \
     > ${K_COEFF_DIR}/n2-h2_l${NBANDS}_clog \
     && echo "N2-H2 CIA done" &
fi

wait
echo "Calculation of k-coefficients completed."

################################################################################
# Calculate optical properties
################################################################################

echo "Calculating cloud optical properties."

mkdir -p ${CLD_COEFF_DIR}

if [ ! -s ${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS} ] ; then
  rm -f ${CLD_COEFF_DIR}/mon_lw_drop5_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -t -p 125 \
    -f 5 ${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_lw_drop5_${NBANDS} 1.e3 \
    ${RAD_DATA}/cloud/scatter_drop_type5
fi
if [ ! -s ${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS} ] ; then
  rm -f ${CLD_COEFF_DIR}/mon_lw_ice8_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -w -p 125 \
    -f 12 ${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_lw_ice8_${NBANDS} 920 \
    ${RAD_DATA}/cloud/scatter_ice_lw_type8
fi

echo "Calculation of cloud optical properties completed."

################################################################################
# Create spectral file
################################################################################

echo "Creating spectral file."

# Create name of spectral file
SPEC_FILE="sp_lw_${NBANDS}_${SP_ID}"

mkdir -p ${SPEC_FILE_DIR}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}_k

# Construct spectral file
prep_spec << EOF > mk_sp_lw_${NBANDS}_${SP_ID}_out
${SPEC_FILE}_skel
n
${SPEC_FILE_DIR}/${SPEC_FILE}
5
${K_COEFF_DIR}/ch4_l${NBANDS}_l
19
${K_COEFF_DIR}/n2-ch4_l${NBANDS}_c
19
y
${K_COEFF_DIR}/n2-n2_l${NBANDS}_c
19
y
${K_COEFF_DIR}/n2-h2_l${NBANDS}_c
6
n
t
1 300
300
-1
EOF

# Add cloud properties
prep_spec << EOF >> mk_sp_lw_${NBANDS}_${SP_ID}_out
${SPEC_FILE_DIR}/${SPEC_FILE}
a
10
5
${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS}
7.60000E-06 5.00000E-05
12
8
${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS}
1.30000E-05 3.10000E-04
-1
EOF

# Remove weak absorbers in bands and set major absorbers
tidy_90 << EOF >> mk_sp_lw_${NBANDS}_${SP_ID}_out
${SPEC_FILE_DIR}/${SPEC_FILE}
o
1
${COL_CH4}
0.0
0.0
${COL_N2_CH4}
${COL_N2_N2}
${COL_N2_H2}
0.99990
6
${COL_CH4}
0.0
0.0
${COL_N2_CH4}
${COL_N2_N2}
${COL_N2_H2}
2.0e+5
n
-1
EOF

. ../set_permissions

echo "Spectral file ${SPEC_FILE} created. All done."
echo "Please check mk_sp_lw_${NBANDS}_${SP_ID}_out for errors."

exit 0
