#!/bin/bash

# Import parameters
. $1

# Paths
HITRAN_DIR="/home/damundse/Line_lists/HITRAN"
K_COEFF_DIR="/home/damundse/k-coeff/sw_${SP_ID}/${PT_FILE}/${SOLAR_SPEC}"
SW_DATA="/home/damundse/Abs_coeff"
SOLAR_SPEC_DIR="/home/damundse/Stellar_spectra"

# Line lists and cross-sections
HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_O3="$HITRAN_DIR/03_hit12.par"
HITRAN_N2O="$HITRAN_DIR/04_hit08.par"
HITRAN_UV_N2O="$HITRAN_DIR/N2O-UV00.xsc"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"
HITRAN_O2="$HITRAN_DIR/07_hit12.par"
HITRAN_UV_O2="$HITRAN_DIR/07_UV06.par"
HITRAN_SO2="$HITRAN_DIR/09_hit12.par"
HITRAN_UV_SO2="$HITRAN_DIR/SO2_UV08.xsc"
HITRAN_OCS="$HITRAN_DIR/19_hit12.par"

HITRAN_UV_O3="$RAD_DATA/gases/ser_bdm_o3.xsc"
JPL_UV_O2="$RAD_DATA/gases/jpl_o2.xsc"

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

o3_pt_file="$RAD_DATA/gases/pt_o3_ser"
o2_pt_file="$RAD_DATA/gases/pt_o2_jpl"
n2o_pt_file="$RAD_DATA/gases/pt_n2o_uv"
so2_pt_file="$RAD_DATA/gases/pt_so2_uv"
ref_pt_file="../ref_pt"

# Create skeleton spectral file
specfile="sp_sw_${NBAND}_${SP_ID}_skel"
rm -f $specfile
. mk_sp_sw_${NBAND}_${SP_ID}_skel > /dev/null

# Construct weighting argument
WGT="+S ${SOLAR_SPEC_DIR}/${SOLAR_SPEC}"

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/h2o_v${NBAND}_l ] || \
    [ ! -s $SW_DATA/h2o_lbl_vis_${PT_FILE}.nc ] ; then
  echo "H2O lines (visible)"
  rm -f ${K_COEFF_DIR}/h2o_v${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R ${BAND_FIRST_H2O} $((BAND_NIR_START-1)) -c 2500.0 -i 1.0 \
    -l 1 ${COL_MASS_K_H2O} ${TOL_LINE} \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/h2o_v${NBAND}_l -m ${K_COEFF_DIR}/h2o_v${NBAND}_lm \
    -L $SW_DATA/h2o_lbl_vis_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_v${NBAND}_log && echo "H2O lines (visible) done" &
fi

if [ ! -s ${K_COEFF_DIR}/co2_s${NBAND}_l ] || \
    [ ! -s $SW_DATA/co2_lbl_sw_${PT_FILE}.nc ] ; then
  echo "CO2"
  rm -f ${K_COEFF_DIR}/co2_s${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R ${BAND_FIRST_CO2} ${NBAND} -c 2500.0 -i 1.0 \
    -l 2 ${COL_MASS_K_CO2} ${TOL_LINE} \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBAND}_l -m ${K_COEFF_DIR}/co2_s${NBAND}_lm \
    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/co2_s${NBAND}_log && echo "CO2 done" &
fi

if [ ! -s ${K_COEFF_DIR}/o3_u${NBAND}_l ] || \
    [ ! -s $SW_DATA/o3_lbl_uv_${PT_FILE}.nc ] ; then
  echo "O3"
  rm -f ${K_COEFF_DIR}/o3_u${NBAND}_l*
  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
    -R ${BAND_RANGE_UVC_O3} -c 2500.0 -i 1.0 \
    -l 3 ${COL_MASS_K_O3} ${TOL_XSEC} \
    -s $specfile ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/o3_u${NBAND}_l -m ${K_COEFF_DIR}/o3_u${NBAND}_lm \
    -L $SW_DATA/o3_lbl_uv_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/o3_u${NBAND}_log && echo "O3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o3_s${NBAND}_l ] || \
    [ ! -s $SW_DATA/o3_lbl_sw_${PT_FILE}.nc ] ; then
  echo "O3 (near-IR)"
  rm -f ${K_COEFF_DIR}/o3_s${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O3 \
    -R ${BAND_FIRST_O3} ${NBAND} -c 2500.0 -i 1.0 \
    -l 3 ${COL_MASS_K_O3} ${TOL_LINE} \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/o3_s${NBAND}_l -m ${K_COEFF_DIR}/o3_s${NBAND}_lm \
    -L $SW_DATA/o3_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/o3_s${NBAND}_log && echo "O3 (near-IR) done" &
fi

if [ ! -s ${K_COEFF_DIR}/n2o_s${NBAND}_l ] || \
    [ ! -s $SW_DATA/n2o_lbl_sw_${PT_FILE}.nc ] ; then
  echo "N2O"
  rm -f ${K_COEFF_DIR}/n2o_s${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R ${BAND_FIRST_N2O} ${NBAND} -c 2500.0 -i 1.0 \
    -l 4 ${COL_MASS_K_N2O} ${TOL_LINE} \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/n2o_s${NBAND}_l -m ${K_COEFF_DIR}/n2o_s${NBAND}_lm \
    -L $SW_DATA/n2o_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/n2o_s${NBAND}_log && echo "N2O done" &
fi
if [ "${O2_N2O_CONTINUUM}" = "TRUE" ] ; then
  if [ ! -s ${K_COEFF_DIR}/n2o_u${NBAND}_l ] || \
      [ ! -s $SW_DATA/n2o_lbl_uv_${PT_FILE}.nc ] ; then
    echo "N2O (UV)"
    rm -f ${K_COEFF_DIR}/n2o_u${NBAND}_l*
    Ccorr_k -F $n2o_pt_file -X $HITRAN_UV_N2O \
      -R ${BAND_RANGE_UVC_N2O} -c 2500.0 -i 1.0 \
      -l 4 ${COL_MASS_K_N2O} ${TOL_XSEC} \
      -s $specfile ${WGT} \
      -o ${K_COEFF_DIR}/n2o_u${NBAND}_l -m ${K_COEFF_DIR}/n2o_u${NBAND}_lm \
      -L $SW_DATA/n2o_lbl_uv_${PT_FILE}.nc \
       > ${K_COEFF_DIR}/n2o_u${NBAND}_log && echo "N2O (UV) done" &
  fi
fi

if [ ! -s ${K_COEFF_DIR}/ch4_s${NBAND}_l ] || \
    [ ! -s $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc ] ; then
  echo "CH4"
  rm -f ${K_COEFF_DIR}/ch4_s${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R ${BAND_FIRST_CH4} ${NBAND} -c 2500.0 -i 1.0 \
    -l 6 ${COL_MASS_K_CH4} ${TOL_LINE} \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_s${NBAND}_l -m ${K_COEFF_DIR}/ch4_s${NBAND}_lm \
    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/ch4_s${NBAND}_log && echo "CH4 done" &
fi

if [ "${O2_N2O_CONTINUUM}" = "TRUE" ] ; then
  if [ ! -s ${K_COEFF_DIR}/o2_j${NBAND}_l ] || \
      [ ! -s $SW_DATA/o2_lbl_jpl_${PT_FILE}.nc ] ; then
    echo "O2 (UV continuum: JPL)"
    rm -f ${K_COEFF_DIR}/o2_j${NBAND}_l*
    Ccorr_k -F $o2_pt_file -X $JPL_UV_O2 \
      -R ${BAND_RANGE_UVC_O2} -c 2500.0 -i 1.0 \
      -l 7 ${COL_MASS_K_O2} ${TOL_XSEC} \
      -s $specfile ${WGT} \
      -o ${K_COEFF_DIR}/o2_j${NBAND}_l -m ${K_COEFF_DIR}/o2_j${NBAND}_lm \
      -L $SW_DATA/o2_lbl_jpl_${PT_FILE}.nc \
       > ${K_COEFF_DIR}/o2_j${NBAND}_log && echo "O2 (UV continuum: JPL) done" &
  fi
fi
if [ ! -s ${K_COEFF_DIR}/o2_u${NBAND}_l ] || \
    [ ! -s $SW_DATA/o2_lbl_uv_${PT_FILE}.nc ] ; then
  echo "O2 (UV lines: HITRAN)"
  rm -f ${K_COEFF_DIR}/o2_u${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_UV_O2 \
    -R ${BAND_RANGE_UVL_O2} -c 2500.0 -i 1.0 \
    -l 7 ${COL_MASS_K_O2} ${TOL_LINE} \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/o2_u${NBAND}_l -m ${K_COEFF_DIR}/o2_u${NBAND}_lm \
    -L $SW_DATA/o2_lbl_uv_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/o2_u${NBAND}_log && echo "O2 (UV lines: HITRAN) done" &
fi
if [ ! -s ${K_COEFF_DIR}/o2_s${NBAND}_l ] || \
    [ ! -s $SW_DATA/o2_lbl_sw_${PT_FILE}.nc ] ; then
  echo "O2 (near-IR)"
  rm -f ${K_COEFF_DIR}/o2_s${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O2 \
    -R ${BAND_FIRST_O2} ${NBAND} -c 2500.0 -i 1.0 \
    -l 7 ${COL_MASS_K_O2} ${TOL_LINE} \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/o2_s${NBAND}_l -m ${K_COEFF_DIR}/o2_s${NBAND}_lm \
    -L $SW_DATA/o2_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/o2_s${NBAND}_log && echo "O2 (near-IR) done" &
fi

if [ ! -s ${K_COEFF_DIR}/so2_s${NBAND}_l ] || \
    [ ! -s $SW_DATA/so2_lbl_sw_${PT_FILE}.nc ] ; then
  echo "SO2"
  rm -f ${K_COEFF_DIR}/so2_s${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_SO2 \
    -R ${BAND_FIRST_SO2} ${NBAND} -c 2500.0 -i 1.0 \
    -l 9 ${COL_MASS_K_SO2} ${TOL_LINE} \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/so2_s${NBAND}_l -m ${K_COEFF_DIR}/so2_s${NBAND}_lm \
    -L $SW_DATA/so2_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/so2_s${NBAND}_log && echo "SO2 done" &
fi
if [ ! -s ${K_COEFF_DIR}/so2_u${NBAND}_l ] || \
    [ ! -s $SW_DATA/so2_lbl_uv_${PT_FILE}.nc ] ; then
  echo "SO2 (UV)"
  rm -f ${K_COEFF_DIR}/so2_u${NBAND}_l*
  Ccorr_k -F $so2_pt_file -X $HITRAN_UV_SO2 \
    -R ${BAND_RANGE_UVC_SO2} -c 2500.0 -i 1.0 \
    -l 9 ${COL_MASS_K_SO2} ${TOL_XSEC} \
    -s $specfile ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/so2_u${NBAND}_l -m ${K_COEFF_DIR}/so2_u${NBAND}_lm \
    -L $SW_DATA/so2_lbl_uv_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/so2_u${NBAND}_log && echo "SO2 (UV) done" &
fi

if [ ! -s ${K_COEFF_DIR}/ocs_s${NBAND}_l ] || \
    [ ! -s $SW_DATA/ocs_lbl_sw_${PT_FILE}.nc ] ; then
  echo "OCS"
  rm -f ${K_COEFF_DIR}/ocs_s${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_OCS \
    -R ${BAND_FIRST_OCS} ${NBAND} -c 2500.0 -i 1.0 \
    -l 25 ${COL_MASS_K_OCS} ${TOL_LINE} \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/ocs_s${NBAND}_l -m ${K_COEFF_DIR}/ocs_s${NBAND}_lm \
    -L $SW_DATA/ocs_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/ocs_s${NBAND}_log && echo "OCS done" &
fi

echo
echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBAND}_l ] || \
    [ ! -s $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc ] ; then
  echo "H2O lines"
  rm -f ${K_COEFF_DIR}/h2o_s${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R ${BAND_NIR_START} ${NBAND} -c 2500.0 -i 1.0 \
    -l 1 ${COL_MASS_K_H2O} ${TOL_LINE} \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBAND}_l -m ${K_COEFF_DIR}/h2o_s${NBAND}_lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm $SW_DATA/h2o_map_${specfile}.nc \
    > ${K_COEFF_DIR}/h2o_s${NBAND}_log && echo "H2O lines done"
fi

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBAND}_s ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o_s${NBAND}_s*
  Ccorr_k -C 33 1.0e-4 1.0e4 -F ../${PT_FILE} -D $HITRAN_H2O \
    -P 7 -R ${BAND_NIR_START} ${NBAND} -c 2500.0 -i 1.0 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s $specfile ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/h2o_s${NBAND}_s -m ${K_COEFF_DIR}/h2o_s${NBAND}_sm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/h2o_s${NBAND}_slog \
     && echo "H2O self-broadened continuum done"
fi

wait

echo "All done"

exit 0