#!/bin/bash

# Import parameters
. $1

# Paths
. set_paths

# Create full path to spectral file
SPEC_FILE="${SPEC_FILE_DIR}/sp_sw_${NBAND}_${SP_ID}_${SOLAR_SPEC}"

mkdir -p ${SPEC_FILE_DIR}
rm -f ${SPEC_FILE}
rm -f ${SPEC_FILE}_k

# Construct spectral file with gases
prep_spec << EOF
sp_sw_${NBAND}_${SP_ID}_skel
n
${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_v${NBAND}_l
5
y
${K_COEFF_DIR}/h2o_s${NBAND}_l
9
${K_COEFF_DIR}/h2o_s${NBAND}_s
5
y
${K_COEFF_DIR}/co2_s${NBAND}_l
5
y
${K_COEFF_DIR}/o3_u${NBAND}_l
5
y
${K_COEFF_DIR}/o3_s${NBAND}_l
5
y
${K_COEFF_DIR}/n2o_s${NBAND}_l
5
y
${K_COEFF_DIR}/ch4_s${NBAND}_l
5
y
${K_COEFF_DIR}/o2_u${NBAND}_l
5
y
${K_COEFF_DIR}/o2_s${NBAND}_l
5
y
${K_COEFF_DIR}/so2_s${NBAND}_l
5
y
${K_COEFF_DIR}/so2_u${NBAND}_l
5
y
${K_COEFF_DIR}/ocs_s${NBAND}_l
-1
EOF

# Add N2O and O2 UV continua if requested
if [ ${O2_N2O_CONTINUUM} = "TRUE" ] ; then
prep_spec << EOF
${SPEC_FILE}
a
5
y
${K_COEFF_DIR}/n2o_u${NBAND}_l
5
y
${K_COEFF_DIR}/o2_j${NBAND}_l
-1
EOF
fi

# Add cloud fits to spectral file
prep_spec << EOF
${SPEC_FILE}
a
10
5
${CLD_COEFF_DIR}/fit_sw_drop5_${NBAND}
1.70000E-06 5.00000E-05
12
8
${CLD_COEFF_DIR}/fit_sw_ice8_${NBAND}
7.00000E-06 3.00000E-04
-1
EOF

# Add solar spectrum and Rayleigh scattering coefficients
prep_spec << EOF
${SPEC_FILE}
a
2
n
${SOLAR_SPEC_DIR}/${SOLAR_SPEC}
y
3
a
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
tidy_90 << EOF
${SPEC_FILE}
o
1
${COL_MASS_ELIM_H2O}
${COL_MASS_ELIM_CO2}
${COL_MASS_ELIM_O3}
${COL_MASS_ELIM_N2O}
${COL_MASS_ELIM_CH4}
${COL_MASS_ELIM_O2}
${COL_MASS_ELIM_SO2}
${COL_MASS_ELIM_OCS}
0.999990
6
${COL_MASS_STMJ_H2O}
${COL_MASS_STMJ_CO2}
${COL_MASS_STMJ_O3}
${COL_MASS_STMJ_N2O}
${COL_MASS_STMJ_CH4}
${COL_MASS_STMJ_O2}
${COL_MASS_STMJ_SO2}
${COL_MASS_STMJ_OCS}
-1
EOF

exit 0