#!/bin/bash

NBANDS="6"
SP_ID="jm2dsa"
SP_FLDR="ga7"
SOLAR_SPEC="gj876"
PT_FILE="pt663"

. ../set_paths_sw

################################################################################
# Calculate k-coefficients
################################################################################

echo "Calculating k-coefficients."

# Set paths to files
HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_O3="$HITRAN_DIR/03_hit12.par"
HITRAN_N2O="$HITRAN_DIR/04_hit08.par"
HITRAN_UV_N2O="$HITRAN_DIR/N2O-UV00.xsc"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"
HITRAN_O2="$HITRAN_DIR/07_hit12.par"
HITRAN_UV_O2="$HITRAN_DIR/07_UV06.par"
HITRAN_SO2="$HITRAN_DIR/09_hit12.par"
HITRAN_UV_SO2="$HITRAN_DIR/SO2_UV08.xsc"
HITRAN_OCS="$HITRAN_DIR/19_hit12.par"
HITRAN_UV_O3="$RAD_DATA/gases/ser_bdm_o3.xsc"
JPL_UV_O2="$RAD_DATA/gases/jpl_o2.xsc"
o3_pt_file="$RAD_DATA/gases/pt_o3_ser"
o2_pt_file="$RAD_DATA/gases/pt_o2_jpl"
n2o_pt_file="$RAD_DATA/gases/pt_n2o_uv"
so2_pt_file="$RAD_DATA/gases/pt_so2_uv"
ref_pt_file="$RAD_DATA/gases/ref_pt"

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Create skeleton spectral file
SPECFILE="sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_skel"
rm -f ${SPECFILE}
. mk_sp_sw_${NBANDS}_${SP_ID}_skel ${SOLAR_SPEC} > /dev/null

# Create 12 band skeleton spectral file for pseudo-bands
specfile12="sp_sw_12_${SP_ID}_${SOLAR_SPEC}_skel"
rm -f ${SPECFILE}12
. mk_sp_sw_12_${SP_ID}_skel ${SOLAR_SPEC} > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

# Construct weight argument
WGT="+S ${SOLAR_SPEC_DIR}/${SOLAR_SPEC}"

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_5l ] ; then
  echo "CO2 band 5"
  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 5 5 -c 2500.0 -i 1.0 -l 2 1.0e1 -t 4.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBANDS}_5l -m ${K_COEFF_DIR}/co2_s${NBANDS}_5lm \
    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/co2_s${NBANDS}_5log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_6l ] ; then
  echo "CO2 band 6"
  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 6 6 -c 2500.0 -i 1.0 -l 2 1.0e1 -t 1.0e-2  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBANDS}_6l -m ${K_COEFF_DIR}/co2_s${NBANDS}_6lm \
    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/co2_s${NBANDS}_6log \
    && echo "CO2 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/o3_u6_2l ] ; then
  echo "O3 bands 3-4"
  rm -f ${K_COEFF_DIR}/o3_u6_2l*
  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
    -R 3 4 -c 2500.0 -i 1.0 -l 3 1.0e-2 -t 1.0e-2  \
    -s ${SPECFILE} ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/o3_u6_2l -m ${K_COEFF_DIR}/o3_u6_2lm \
    -L $SW_DATA/o3_lbl_uv_${PT_FILE}.nc > ${K_COEFF_DIR}/o3_u6_2log \
    && echo "O3 bands 3-4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o3_s${NBANDS}_2l ] ; then
  echo "O3 band 6"
  rm -f ${K_COEFF_DIR}/o3_s${NBANDS}_2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O3 \
    -R 6 6 -c 2500.0 -i 1.0 -l 3 1.0e-2 -t 1.0e-2  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/o3_s${NBANDS}_2l -m ${K_COEFF_DIR}/o3_s${NBANDS}_2lm \
    -L $SW_DATA/o3_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/o3_s${NBANDS}_2log \
    && echo "O3 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/n2o_s${NBANDS}_6l ] ; then
  echo "N2O band 6"
  rm -f ${K_COEFF_DIR}/n2o_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 6 6 -c 2500.0 -i 1.0 -l 4 5.0e-3 -t 6.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/n2o_s${NBANDS}_6l -m ${K_COEFF_DIR}/n2o_s${NBANDS}_6lm \
    -L $SW_DATA/n2o_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/n2o_s${NBANDS}_6log \
    && echo "N2O band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ch4_s${NBANDS}_5l ] ; then
  echo "CH4 band 5"
  rm -f ${K_COEFF_DIR}/ch4_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 5 5 -c 2500.0 -i 1.0 -l 6 1.0e-2 -t 6.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_s${NBANDS}_5l -m ${K_COEFF_DIR}/ch4_s${NBANDS}_5lm \
    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/ch4_s${NBANDS}_5log \
    && echo "CH4 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_s${NBANDS}_6l ] ; then
  echo "CH4 band 6"
  rm -f ${K_COEFF_DIR}/ch4_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 6 6 -c 2500.0 -i 1.0 -l 6 1.0e-2 -t 6.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_s${NBANDS}_6l -m ${K_COEFF_DIR}/ch4_s${NBANDS}_6lm \
    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/ch4_s${NBANDS}_6log \
    && echo "CH4 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/o2_u6_1l ] ; then
  echo "O2 band 1"
  rm -f ${K_COEFF_DIR}/o2_u6_1l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_UV_O2 \
    -R 1 1 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 1.0e-2  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/o2_u6_1l -m ${K_COEFF_DIR}/o2_u6_1lm \
    -L $SW_DATA/o2_lbl_uv_${PT_FILE}.nc > ${K_COEFF_DIR}/o2_u6_1log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o2_s${NBANDS}_3l ] ; then
  echo "O2 band 3"
  rm -f ${K_COEFF_DIR}/o2_s${NBANDS}_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O2 \
    -R 3 3 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 1.0e-2  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/o2_s${NBANDS}_3l -m ${K_COEFF_DIR}/o2_s${NBANDS}_3lm \
    -L $SW_DATA/o2_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/o2_s${NBANDS}_3log \
    && echo "O2 band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o2_s${NBANDS}_4l ] ; then
  echo "O2 band 4"
  rm -f ${K_COEFF_DIR}/o2_s${NBANDS}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O2 \
    -R 4 4 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 2.2e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/o2_s${NBANDS}_4l -m ${K_COEFF_DIR}/o2_s${NBANDS}_4lm \
    -L $SW_DATA/o2_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/o2_s${NBANDS}_4log \
    && echo "O2 band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o2_s${NBANDS}_5l ] ; then
  echo "O2 band 5"
  rm -f ${K_COEFF_DIR}/o2_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O2 \
    -R 5 5 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 1.0e-2  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/o2_s${NBANDS}_5l -m ${K_COEFF_DIR}/o2_s${NBANDS}_5lm \
    -L $SW_DATA/o2_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/o2_s${NBANDS}_5log \
    && echo "O2 band 5 done" &
fi

if [ ! -s ${K_COEFF_DIR}/so2_s${NBANDS}_l ] ; then
  echo "SO2 band 6"
  rm -f ${K_COEFF_DIR}/so2_s${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_SO2 \
    -R 6 6 -c 2500.0 -i 1.0 -l 9 3.0e-4 -t 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/so2_s${NBANDS}_l -m ${K_COEFF_DIR}/so2_s${NBANDS}_lm \
    -L $SW_DATA/so2_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/so2_s${NBANDS}_log \
    && echo "SO2 band 6 done" &
fi
if [ ! -s ${K_COEFF_DIR}/so2_u6_l ] ; then
  echo "SO2 band 1-2"
  rm -f ${K_COEFF_DIR}/so2_u6_l*
  Ccorr_k -F $so2_pt_file -X $HITRAN_UV_SO2 \
    -R 1 2 -c 2500.0 -i 1.0 -l 9 3.0e-4 -t 1.0e-3  \
    -s ${SPECFILE} ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/so2_u6_l -m ${K_COEFF_DIR}/so2_u6_lm \
    -L $SW_DATA/so2_lbl_uv_${PT_FILE}.nc > ${K_COEFF_DIR}/so2_u6_log \
    && echo "SO2 band 1-2 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ocs_s${NBANDS}_l ] ; then
  echo "OCS band 6"
  rm -f ${K_COEFF_DIR}/ocs_s${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_OCS \
    -R 6 6 -c 2500.0 -i 1.0 -l 25 1.0e-3 -t 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ocs_s${NBANDS}_l -m ${K_COEFF_DIR}/ocs_s${NBANDS}_lm \
    -L $SW_DATA/ocs_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/ocs_s${NBANDS}_log \
    && echo "OCS band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_3l ] ; then
  echo "H2O lines band 3"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 3 3 -c 2500.0 -i 1.0 -l 1 1.0e2 -n 2  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_3l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_3lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s${NBANDS}_3log \
    && echo "H2O lines band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_4l ] ; then
  echo "H2O lines band 4"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 4 4 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 1.0e-2  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_4l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_4lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s${NBANDS}_4log \
    && echo "H2O lines band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_5l ] ; then
  echo "H2O lines band 5"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 5 5 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 1.0e-2  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_5l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_5lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s${NBANDS}_5log \
    && echo "H2O lines band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_6l ] ; then
  echo "H2O lines band 6"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 6 6 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 1.2e-2  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_6l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_6lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s${NBANDS}_6log \
    && echo "H2O lines band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_s ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_s*
  Ccorr_k -C 33 1.0e-4 1.0e4 -F ../${PT_FILE} -D $HITRAN_H2O \
    -P 7 -R 3 6 -c 2500.0 -i 1.0 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s ${SPECFILE} ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_s -m ${K_COEFF_DIR}/h2o_s${NBANDS}_sm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s${NBANDS}_slog \
    && echo "H2O self-broadened continuum done" &
fi

echo "Jobs running in the foreground:"

if [ ! -s ${K_COEFF_DIR}/o3_u12_l ] ; then
  echo "O3 bands 1-8 (of 12)"
  rm -f ${K_COEFF_DIR}/o3_u12_l*
  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
    -R 1 8 -c 2500.0 -i 1.0 -l 3 1.0e-2 -n 1  \
    -s ${SPECFILE}12 ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/o3_u12_l -m ${K_COEFF_DIR}/o3_u12_lm \
    -L $SW_DATA/o3_lbl_uv_${PT_FILE}.nc > ${K_COEFF_DIR}/o3_u12_log \
    && echo "O3 bands 1-8 (of 12) done"
fi
# Edit 12 band O3 file to give 6 band file:
# Adjust weights to normalised solar spectrum weights from sp_sw_12_jm2dsa_skel
# (hardwired here: should be changed if solar spectrum is changed)
if [ ${SOLAR_SPEC} = "sun" ] ; then
  sed -e "15s/1/6/"                                            \
      -e "18s/1.000000000E+00/2.121528934E-02/"  -e "20,38d"   \
      -e "39s/1.000000000E+00/3.472014963E-02/"  -e "41,59d"   \
      -e "60s/1.000000000E+00/4.818967733E-02/"  -e "62,80d"   \
      -e "81s/1.000000000E+00/1.412245476E-01/"  -e "83,101d"  \
      -e "102s/1.000000000E+00/2.941486590E-01/" -e "104,122d" \
      -e "123s/1.000000000E+00/4.605016771E-01/"               \
      -e "130s/7/2/"                                           \
      -e "141s/1/2/"                                           \
      -e "144s/1.000000000E+00/2.900632239E-01/" -e "146,164d" \
      -e "165s/1.000000000E+00/7.099367761E-01/"               \
      ${K_COEFF_DIR}/o3_u12_l > ${K_COEFF_DIR}/o3_u6_l

elif [ ${SOLAR_SPEC} = "pc" ] ; then
  sed -e "15s/1/6/"                                            \
      -e "18s/1.000000000E+00/6.901997742E-01/"  -e "20,38d"   \
      -e "39s/1.000000000E+00/5.293133998E-02/"  -e "41,59d"   \
      -e "60s/1.000000000E+00/3.327782674E-02/"  -e "62,80d"   \
      -e "81s/1.000000000E+00/7.190050499E-02/"  -e "83,101d"  \
      -e "102s/1.000000000E+00/4.394576332E-02/" -e "104,122d" \
      -e "123s/1.000000000E+00/1.077447907E-01/"               \
      -e "130s/7/2/"                                           \
      -e "141s/1/2/"                                           \
      -e "144s/1.000000000E+00/1.804974896E-01/" -e "146,164d" \
      -e "165s/1.000000000E+00/8.195025106E-01/"               \
      ${K_COEFF_DIR}/o3_u12_l > ${K_COEFF_DIR}/o3_u6_l

elif [ ${SOLAR_SPEC} = "gj876" ] ; then
  sed -e "15s/1/6/"                                            \
      -e "18s/1.000000000E+00/5.775872224E-01/"  -e "20,38d"   \
      -e "39s/1.000000000E+00/3.405126467E-02/"  -e "41,59d"   \
      -e "60s/1.000000000E+00/2.904063550E-02/"  -e "62,80d"   \
      -e "81s/1.000000000E+00/1.033824522E-01/"  -e "83,101d"  \
      -e "102s/1.000000000E+00/1.414090007E-01/" -e "104,122d" \
      -e "123s/1.000000000E+00/1.145294246E-01/"               \
      -e "130s/7/2/"                                           \
      -e "141s/1/2/"                                           \
      -e "144s/1.000000000E+00/1.308343729E-01/" -e "146,164d" \
      -e "165s/1.000000000E+00/8.691656268E-01/"               \
      ${K_COEFF_DIR}/o3_u12_l > ${K_COEFF_DIR}/o3_u6_l

elif [ ${SOLAR_SPEC} = "k186" ] ; then
  sed -e "15s/1/6/"                                            \
      -e "18s/1.000000000E+00/2.091296926E-04/"  -e "20,38d"   \
      -e "39s/1.000000000E+00/1.384036529E-03/"  -e "41,59d"   \
      -e "60s/1.000000000E+00/8.923413110E-03/"  -e "62,80d"   \
      -e "81s/1.000000000E+00/5.035518055E-02/"  -e "83,101d"  \
      -e "102s/1.000000000E+00/1.794202293E-01/" -e "104,122d" \
      -e "123s/1.000000000E+00/7.597080108E-01/"               \
      -e "130s/7/2/"                                           \
      -e "141s/1/2/"                                           \
      -e "144s/1.000000000E+00/1.306757696E-01/" -e "146,164d" \
      -e "165s/1.000000000E+00/8.693242305E-01/"               \
      ${K_COEFF_DIR}/o3_u12_l > ${K_COEFF_DIR}/o3_u6_l

elif [ ${SOLAR_SPEC} = "sun_0.715gyr" ] ; then
  sed -e "15s/1/6/"                                            \
      -e "18s/1.000000000E+00/2.166362164E-02/"  -e "20,38d"   \
      -e "39s/1.000000000E+00/3.465688541E-02/"  -e "41,59d"   \
      -e "60s/1.000000000E+00/4.849478939E-02/"  -e "62,80d"   \
      -e "81s/1.000000000E+00/1.425375069E-01/"  -e "83,101d"  \
      -e "102s/1.000000000E+00/2.965934810E-01/" -e "104,122d" \
      -e "123s/1.000000000E+00/4.560537157E-01/"               \
      -e "130s/7/2/"                                           \
      -e "141s/1/2/"                                           \
      -e "144s/1.000000000E+00/2.903952229E-01/" -e "146,164d" \
      -e "165s/1.000000000E+00/7.096047774E-01/"               \
      ${K_COEFF_DIR}/o3_u12_l > ${K_COEFF_DIR}/o3_u6_l

elif [ ${SOLAR_SPEC} = "sun_2.9gyr" ] ; then
  sed -e "15s/1/6/"                                            \
      -e "18s/1.000000000E+00/2.038003079E-02/"  -e "20,38d"   \
      -e "39s/1.000000000E+00/3.070740297E-02/"  -e "41,59d"   \
      -e "60s/1.000000000E+00/4.502093415E-02/"  -e "62,80d"   \
      -e "81s/1.000000000E+00/1.402717281E-01/"  -e "83,101d"  \
      -e "102s/1.000000000E+00/2.924388629E-01/" -e "104,122d" \
      -e "123s/1.000000000E+00/4.711810409E-01/"               \
      -e "130s/7/2/"                                           \
      -e "141s/1/2/"                                           \
      -e "144s/1.000000000E+00/2.834020970E-01/" -e "146,164d" \
      -e "165s/1.000000000E+00/7.165979031E-01/"               \
      ${K_COEFF_DIR}/o3_u12_l > ${K_COEFF_DIR}/o3_u6_l

elif [ ${SOLAR_SPEC} = "hd22049" ] ; then
  sed -e "15s/1/6/"                                            \
      -e "18s/1.000000000E+00/1.166662245E-02/"  -e "20,38d"   \
      -e "39s/1.000000000E+00/1.907442736E-02/"  -e "41,59d"   \
      -e "60s/1.000000000E+00/3.717517612E-02/"  -e "62,80d"   \
      -e "81s/1.000000000E+00/1.216750121E-01/"  -e "83,101d"  \
      -e "102s/1.000000000E+00/2.777548694E-01/" -e "104,122d" \
      -e "123s/1.000000000E+00/5.326538924E-01/"               \
      -e "130s/7/2/"                                           \
      -e "141s/1/2/"                                           \
      -e "144s/1.000000000E+00/2.080770319E-01/" -e "146,164d" \
      -e "165s/1.000000000E+00/7.919229679E-01/"               \
      ${K_COEFF_DIR}/o3_u12_l > ${K_COEFF_DIR}/o3_u6_l
else
  echo "Error, no weight conversion for spectrum."
  stop
fi

wait
echo "Calculation of k-coefficients completed."

################################################################################
# Calculate optical properties
################################################################################

echo "Calculating cloud optical properties."

WGT_SCTAVG="-${WGT:1}"

mkdir -p ${CLD_COEFF_DIR}

if [ ! -s ${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS} ] ; then
  echo 'Type 5 droplets'
  rm -f ${CLD_COEFF_DIR}/mon_sw_drop5_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -t ${WGT_SCTAVG} \
    -f 5 ${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_sw_drop5_${NBANDS} 1.e3 \
    ${RAD_DATA}/cloud/scatter_drop_type5
fi
if [ ! -s ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS} ] ; then
  echo 'Type 8 ice'
  rm -f ${CLD_COEFF_DIR}/mon_sw_ice8_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -w ${WGT_SCTAVG} \
    -f 12 ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_sw_ice8_${NBANDS} 920 \
    ${RAD_DATA}/cloud/scatter_ice_sw_type8
fi

echo "Calculation of cloud optical properties completed."

################################################################################
# Create spectral file
################################################################################

echo "Creating spectral file."

# Create full path to spectral file
SPEC_FILE="${SPEC_FILE_DIR}/sp_sw_ga7_dsa_${SOLAR_SPEC}"

mkdir -p ${SPEC_FILE_DIR}
rm -f ${SPEC_FILE}
rm -f ${SPEC_FILE}_k

# Replace old k-coefficients by new k-coefficients in spectral file
prep_spec << EOF > mk_sp_sw_ga7_dsa_${SOLAR_SPEC}_out
sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_skel
n
${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_s${NBANDS}_4l
5
y
${K_COEFF_DIR}/h2o_s${NBANDS}_5l
5
y
${K_COEFF_DIR}/h2o_s${NBANDS}_6l
9
${K_COEFF_DIR}/h2o_s${NBANDS}_s
5
y
${K_COEFF_DIR}/co2_s${NBANDS}_5l
5
y
${K_COEFF_DIR}/co2_s${NBANDS}_6l
5
y
${K_COEFF_DIR}/o3_u6_2l
5
y
${K_COEFF_DIR}/o3_s${NBANDS}_2l
5
y
${K_COEFF_DIR}/o3_u6_l
5
y
${K_COEFF_DIR}/h2o_s${NBANDS}_3l
5
y
${K_COEFF_DIR}/n2o_s${NBANDS}_6l
5
y
${K_COEFF_DIR}/ch4_s${NBANDS}_5l
5
y
${K_COEFF_DIR}/ch4_s${NBANDS}_6l
5
y
${K_COEFF_DIR}/o2_u6_1l
5
y
${K_COEFF_DIR}/o2_s${NBANDS}_3l
5
y
${K_COEFF_DIR}/o2_s${NBANDS}_4l
5
y
${K_COEFF_DIR}/o2_s${NBANDS}_5l
5
y
${K_COEFF_DIR}/so2_s${NBANDS}_l
5
y
${K_COEFF_DIR}/so2_u6_l
5
y
${K_COEFF_DIR}/ocs_s${NBANDS}_l
-1
EOF

# Add cloud fits to spectral file
prep_spec << EOF >> mk_sp_sw_ga7_dsa_${SOLAR_SPEC}_out
${SPEC_FILE}
a
10
5
${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS}
1.50000E-06 5.00000E-05
12
8
${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS}
7.00000E-06 3.20000E-04
-1
EOF

# Add solar spectrum and Rayleigh scattering coefficients
prep_spec << EOF >> mk_sp_sw_ga7_dsa_${SOLAR_SPEC}_out
${SPEC_FILE}
a
2
y
n
${SOLAR_SPEC_DIR}/${SOLAR_SPEC}
y
3
a
-1
EOF

. ../set_permissions

echo "Spectral file sp_sw_ga7_dsa_${SOLAR_SPEC} created. All done."
echo "Please check mk_sp_sw_ga7_dsa_${SOLAR_SPEC}_out for errors."

exit 0
