#!/bin/bash

# Import parameters
. $1

. ../set_paths_sw

################################################################################
# Calculate k-coefficients
################################################################################

echo "Calculating k-coefficients."

# Set paths to files
HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_O3="$HITRAN_DIR/03_hit12.par"
HITRAN_N2O="$HITRAN_DIR/04_hit08.par"
HITRAN_UV_N2O="$HITRAN_DIR/N2O-UV00.xsc"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"
HITRAN_O2="$HITRAN_DIR/07_hit12.par"
HITRAN_UV_O2="$HITRAN_DIR/07_UV06.par"
HITRAN_SO2="$HITRAN_DIR/09_hit12.par"
HITRAN_UV_SO2="$HITRAN_DIR/SO2_UV08.xsc"
HITRAN_OCS="$HITRAN_DIR/19_hit12.par"
HITRAN_UV_O3="$RAD_DATA/gases/ser_bdm_o3.xsc"
JPL_UV_O2="$RAD_DATA/gases/jpl_o2.xsc"
o3_pt_file="$RAD_DATA/gases/pt_o3_ser"
o2_pt_file="$RAD_DATA/gases/pt_o2_jpl"
n2o_pt_file="$RAD_DATA/gases/pt_n2o_uv"
so2_pt_file="$RAD_DATA/gases/pt_so2_uv"
ref_pt_file="../ref_pt"

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Create skeleton spectral file
SPECFILE="sp_sw_${NBANDS}_${SP_ID}_skel"
rm -f ${SPECFILE}
. mk_sp_sw_${NBANDS}_${SP_ID}_skel > /dev/null

# Construct weighting argument
WGT="+S ${SOLAR_SPEC_DIR}/${SOLAR_SPEC}"

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/h2o_v${NBANDS}_l ] || \
    [ ! -s $SW_DATA/h2o_lbl_vis_${PT_FILE}.nc ] ; then
  echo "H2O lines (visible)"
  rm -f ${K_COEFF_DIR}/h2o_v${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R ${BAND_FIRST_H2O} $((BAND_NIR_START-1)) -c 2500.0 -i 1.0 \
    -l 1 ${COL_MASS_K_H2O} ${TOL_LINE} \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/h2o_v${NBANDS}_l -m ${K_COEFF_DIR}/h2o_v${NBANDS}_lm \
    -L $SW_DATA/h2o_lbl_vis_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_v${NBANDS}_log && echo "H2O lines (visible) done" &
fi

if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_l ] || \
    [ ! -s $SW_DATA/co2_lbl_sw_${PT_FILE}.nc ] ; then
  echo "CO2"
  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R ${BAND_FIRST_CO2} ${NBANDS} -c 2500.0 -i 1.0 \
    -l 2 ${COL_MASS_K_CO2} ${TOL_LINE} \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBANDS}_l -m ${K_COEFF_DIR}/co2_s${NBANDS}_lm \
    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/co2_s${NBANDS}_log && echo "CO2 done" &
fi

if [ ! -s ${K_COEFF_DIR}/o3_u${NBANDS}_l ] || \
    [ ! -s $SW_DATA/o3_lbl_uv_${PT_FILE}.nc ] ; then
  echo "O3"
  rm -f ${K_COEFF_DIR}/o3_u${NBANDS}_l*
  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
    -R ${BAND_RANGE_UVC_O3} -c 2500.0 -i 1.0 \
    -l 3 ${COL_MASS_K_O3} ${TOL_XSEC} \
    -s ${SPECFILE} ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/o3_u${NBANDS}_l -m ${K_COEFF_DIR}/o3_u${NBANDS}_lm \
    -L $SW_DATA/o3_lbl_uv_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/o3_u${NBANDS}_log && echo "O3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o3_s${NBANDS}_l ] || \
    [ ! -s $SW_DATA/o3_lbl_sw_${PT_FILE}.nc ] ; then
  echo "O3 (near-IR)"
  rm -f ${K_COEFF_DIR}/o3_s${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O3 \
    -R ${BAND_FIRST_O3} ${NBANDS} -c 2500.0 -i 1.0 \
    -l 3 ${COL_MASS_K_O3} ${TOL_LINE} \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/o3_s${NBANDS}_l -m ${K_COEFF_DIR}/o3_s${NBANDS}_lm \
    -L $SW_DATA/o3_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/o3_s${NBANDS}_log && echo "O3 (near-IR) done" &
fi

if [ ! -s ${K_COEFF_DIR}/n2o_s${NBANDS}_l ] || \
    [ ! -s $SW_DATA/n2o_lbl_sw_${PT_FILE}.nc ] ; then
  echo "N2O"
  rm -f ${K_COEFF_DIR}/n2o_s${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R ${BAND_FIRST_N2O} ${NBANDS} -c 2500.0 -i 1.0 \
    -l 4 ${COL_MASS_K_N2O} ${TOL_LINE} \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/n2o_s${NBANDS}_l -m ${K_COEFF_DIR}/n2o_s${NBANDS}_lm \
    -L $SW_DATA/n2o_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/n2o_s${NBANDS}_log && echo "N2O done" &
fi
if [ "${O2_N2O_CONTINUUM}" = "TRUE" ] ; then
  if [ ! -s ${K_COEFF_DIR}/n2o_u${NBANDS}_l ] || \
      [ ! -s $SW_DATA/n2o_lbl_uv_${PT_FILE}.nc ] ; then
    echo "N2O (UV)"
    rm -f ${K_COEFF_DIR}/n2o_u${NBANDS}_l*
    Ccorr_k -F $n2o_pt_file -X $HITRAN_UV_N2O \
      -R ${BAND_RANGE_UVC_N2O} -c 2500.0 -i 1.0 \
      -l 4 ${COL_MASS_K_N2O} ${TOL_XSEC} \
      -s ${SPECFILE} ${WGT} \
      -o ${K_COEFF_DIR}/n2o_u${NBANDS}_l -m ${K_COEFF_DIR}/n2o_u${NBANDS}_lm \
      -L $SW_DATA/n2o_lbl_uv_${PT_FILE}.nc \
       > ${K_COEFF_DIR}/n2o_u${NBANDS}_log && echo "N2O (UV) done" &
  fi
fi

if [ ! -s ${K_COEFF_DIR}/ch4_s${NBANDS}_l ] || \
    [ ! -s $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc ] ; then
  echo "CH4"
  rm -f ${K_COEFF_DIR}/ch4_s${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R ${BAND_FIRST_CH4} ${NBANDS} -c 2500.0 -i 1.0 \
    -l 6 ${COL_MASS_K_CH4} ${TOL_LINE} \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_s${NBANDS}_l -m ${K_COEFF_DIR}/ch4_s${NBANDS}_lm \
    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/ch4_s${NBANDS}_log && echo "CH4 done" &
fi

if [ "${O2_N2O_CONTINUUM}" = "TRUE" ] ; then
  if [ ! -s ${K_COEFF_DIR}/o2_j${NBANDS}_l ] || \
      [ ! -s $SW_DATA/o2_lbl_jpl_${PT_FILE}.nc ] ; then
    echo "O2 (UV continuum: JPL)"
    rm -f ${K_COEFF_DIR}/o2_j${NBANDS}_l*
    Ccorr_k -F $o2_pt_file -X $JPL_UV_O2 \
      -R ${BAND_RANGE_UVC_O2} -c 2500.0 -i 1.0 \
      -l 7 ${COL_MASS_K_O2} ${TOL_XSEC} \
      -s ${SPECFILE} ${WGT} \
      -o ${K_COEFF_DIR}/o2_j${NBANDS}_l -m ${K_COEFF_DIR}/o2_j${NBANDS}_lm \
      -L $SW_DATA/o2_lbl_jpl_${PT_FILE}.nc \
       > ${K_COEFF_DIR}/o2_j${NBANDS}_log && echo "O2 (UV continuum: JPL) done" &
  fi
fi
if [ ! -s ${K_COEFF_DIR}/o2_u${NBANDS}_l ] || \
    [ ! -s $SW_DATA/o2_lbl_uv_${PT_FILE}.nc ] ; then
  echo "O2 (UV lines: HITRAN)"
  rm -f ${K_COEFF_DIR}/o2_u${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_UV_O2 \
    -R ${BAND_RANGE_UVL_O2} -c 2500.0 -i 1.0 \
    -l 7 ${COL_MASS_K_O2} ${TOL_LINE} \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/o2_u${NBANDS}_l -m ${K_COEFF_DIR}/o2_u${NBANDS}_lm \
    -L $SW_DATA/o2_lbl_uv_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/o2_u${NBANDS}_log && echo "O2 (UV lines: HITRAN) done" &
fi
if [ ! -s ${K_COEFF_DIR}/o2_s${NBANDS}_l ] || \
    [ ! -s $SW_DATA/o2_lbl_sw_${PT_FILE}.nc ] ; then
  echo "O2 (near-IR)"
  rm -f ${K_COEFF_DIR}/o2_s${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O2 \
    -R ${BAND_FIRST_O2} ${NBANDS} -c 2500.0 -i 1.0 \
    -l 7 ${COL_MASS_K_O2} ${TOL_LINE} \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/o2_s${NBANDS}_l -m ${K_COEFF_DIR}/o2_s${NBANDS}_lm \
    -L $SW_DATA/o2_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/o2_s${NBANDS}_log && echo "O2 (near-IR) done" &
fi

if [ ! -s ${K_COEFF_DIR}/so2_s${NBANDS}_l ] || \
    [ ! -s $SW_DATA/so2_lbl_sw_${PT_FILE}.nc ] ; then
  echo "SO2"
  rm -f ${K_COEFF_DIR}/so2_s${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_SO2 \
    -R ${BAND_FIRST_SO2} ${NBANDS} -c 2500.0 -i 1.0 \
    -l 9 ${COL_MASS_K_SO2} ${TOL_LINE} \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/so2_s${NBANDS}_l -m ${K_COEFF_DIR}/so2_s${NBANDS}_lm \
    -L $SW_DATA/so2_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/so2_s${NBANDS}_log && echo "SO2 done" &
fi
if [ ! -s ${K_COEFF_DIR}/so2_u${NBANDS}_l ] || \
    [ ! -s $SW_DATA/so2_lbl_uv_${PT_FILE}.nc ] ; then
  echo "SO2 (UV)"
  rm -f ${K_COEFF_DIR}/so2_u${NBANDS}_l*
  Ccorr_k -F $so2_pt_file -X $HITRAN_UV_SO2 \
    -R ${BAND_RANGE_UVC_SO2} -c 2500.0 -i 1.0 \
    -l 9 ${COL_MASS_K_SO2} ${TOL_XSEC} \
    -s ${SPECFILE} ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/so2_u${NBANDS}_l -m ${K_COEFF_DIR}/so2_u${NBANDS}_lm \
    -L $SW_DATA/so2_lbl_uv_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/so2_u${NBANDS}_log && echo "SO2 (UV) done" &
fi

if [ ! -s ${K_COEFF_DIR}/ocs_s${NBANDS}_l ] || \
    [ ! -s $SW_DATA/ocs_lbl_sw_${PT_FILE}.nc ] ; then
  echo "OCS"
  rm -f ${K_COEFF_DIR}/ocs_s${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_OCS \
    -R ${BAND_FIRST_OCS} ${NBANDS} -c 2500.0 -i 1.0 \
    -l 25 ${COL_MASS_K_OCS} ${TOL_LINE} \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ocs_s${NBANDS}_l -m ${K_COEFF_DIR}/ocs_s${NBANDS}_lm \
    -L $SW_DATA/ocs_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/ocs_s${NBANDS}_log && echo "OCS done" &
fi

echo
echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_l ] || \
    [ ! -s $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc ] ; then
  echo "H2O lines"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R ${BAND_NIR_START} ${NBANDS} -c 2500.0 -i 1.0 \
    -l 1 ${COL_MASS_K_H2O} ${TOL_LINE} \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm $SW_DATA/h2o_map_${specfile}.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_log && echo "H2O lines done"
fi

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_s ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_s*
  Ccorr_k -C 33 1.0e-4 1.0e4 -F ../${PT_FILE} -D $HITRAN_H2O \
    -P 7 -R ${BAND_NIR_START} ${NBANDS} -c 2500.0 -i 1.0 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s ${SPECFILE} ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_s -m ${K_COEFF_DIR}/h2o_s${NBANDS}_sm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/h2o_s${NBANDS}_slog \
     && echo "H2O self-broadened continuum done"
fi

wait
echo "Calculation of k-coefficients completed."

################################################################################
# Calculate optical properties
################################################################################

echo "Calculating cloud optical properties."

WGT_SCTAVG="-${WGT:1}"

mkdir -p ${CLD_COEFF_DIR}

if [ ! -s ${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS} ] ; then
  echo 'Type 5 droplets'
  rm -f ${CLD_COEFF_DIR}/mon_sw_drop5_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -t ${WGT_SCTAVG} \
    -f 5 ${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_sw_drop5_${NBANDS} 1.e3 \
    ${RAD_DATA}/cloud/scatter_drop_type5
fi
if [ ! -s ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS} ] ; then
  echo 'Type 8 ice'
  rm -f ${CLD_COEFF_DIR}/mon_sw_ice8_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -w ${WGT_SCTAVG} \
    -f 12 ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_sw_ice8_${NBANDS} 920 \
    ${RAD_DATA}/cloud/scatter_ice_sw_type8
fi

echo "Calculation of cloud optical properties completed."

################################################################################
# Create spectral file
################################################################################

echo "Creating spectral file."

# Create full path to spectral file
SPEC_FILE="${SPEC_FILE_DIR}/sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}"

mkdir -p ${SPEC_FILE_DIR}
rm -f ${SPEC_FILE}
rm -f ${SPEC_FILE}_k

# Construct spectral file with gases
prep_spec << EOF > mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
sp_sw_${NBANDS}_${SP_ID}_skel
n
${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_v${NBANDS}_l
5
y
${K_COEFF_DIR}/h2o_s${NBANDS}_l
9
${K_COEFF_DIR}/h2o_s${NBANDS}_s
5
y
${K_COEFF_DIR}/co2_s${NBANDS}_l
5
y
${K_COEFF_DIR}/o3_u${NBANDS}_l
5
y
${K_COEFF_DIR}/o3_s${NBANDS}_l
5
y
${K_COEFF_DIR}/n2o_s${NBANDS}_l
5
y
${K_COEFF_DIR}/ch4_s${NBANDS}_l
5
y
${K_COEFF_DIR}/o2_u${NBANDS}_l
5
y
${K_COEFF_DIR}/o2_s${NBANDS}_l
5
y
${K_COEFF_DIR}/so2_s${NBANDS}_l
5
y
${K_COEFF_DIR}/so2_u${NBANDS}_l
5
y
${K_COEFF_DIR}/ocs_s${NBANDS}_l
-1
EOF

# Add N2O and O2 UV continua if requested
if [ ${O2_N2O_CONTINUUM} = "TRUE" ] ; then
prep_spec << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
${SPEC_FILE}
a
5
y
${K_COEFF_DIR}/n2o_u${NBANDS}_l
5
y
${K_COEFF_DIR}/o2_j${NBANDS}_l
-1
EOF
fi

# Add cloud fits to spectral file
prep_spec << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
${SPEC_FILE}
a
10
5
${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS}
1.70000E-06 5.00000E-05
12
8
${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS}
7.00000E-06 3.00000E-04
-1
EOF

# Add solar spectrum and Rayleigh scattering coefficients
prep_spec << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
${SPEC_FILE}
a
2
n
${SOLAR_SPEC_DIR}/${SOLAR_SPEC}
y
3
a
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
tidy_90 << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
${SPEC_FILE}
o
1
${COL_MASS_ELIM_H2O}
${COL_MASS_ELIM_CO2}
${COL_MASS_ELIM_O3}
${COL_MASS_ELIM_N2O}
${COL_MASS_ELIM_CH4}
${COL_MASS_ELIM_O2}
${COL_MASS_ELIM_SO2}
${COL_MASS_ELIM_OCS}
0.999990
6
${COL_MASS_STMJ_H2O}
${COL_MASS_STMJ_CO2}
${COL_MASS_STMJ_O3}
${COL_MASS_STMJ_N2O}
${COL_MASS_STMJ_CH4}
${COL_MASS_STMJ_O2}
${COL_MASS_STMJ_SO2}
${COL_MASS_STMJ_OCS}
-1
EOF

echo "Spectral file sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC} created. All done."
echo "Please check mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out for errors."

exit 0
