#!/bin/bash

# Import parameters
. $1

# Paths
. set_paths

# Line lists and cross-sections
HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

ref_pt_file="$RAD_DATA/gases/ref_pt"

# Create skeleton spectral file
specfile="sp_sw_${NBAND}_${SP_ID}_skel"
rm -f $specfile
. mk_sp_sw_${NBAND}_${SP_ID}_skel > /dev/null

# Construct weighting argument
WGT="+S ${SOLAR_SPEC_DIR}/${SOLAR_SPEC}"

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/h2o_v${NBAND}_l ] || \
    [ ! -s $SW_DATA/h2o_lbl_vis_${PT_FILE}.nc ] ; then
  echo "H2O lines (visible)"
  rm -f ${K_COEFF_DIR}/h2o_v${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R ${BAND_FIRST_H2O} $((BAND_NIR_START-1)) -c 2500.0 -i 1.0 \
    -l 1 ${COL_MASS_K_H2O} ${TOL} \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/h2o_v${NBAND}_l -m ${K_COEFF_DIR}/h2o_v${NBAND}_lm \
    -L $SW_DATA/h2o_lbl_vis_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/h2o_v${NBAND}_log && echo "H2O lines (visible) done" &
fi

if [ ! -s ${K_COEFF_DIR}/co2_s${NBAND}_l ] || \
    [ ! -s $SW_DATA/co2_lbl_sw_${PT_FILE}.nc ] ; then
  echo "CO2"
  rm -f ${K_COEFF_DIR}/co2_s${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R ${BAND_FIRST_CO2} ${NBAND} -c 2500.0 -i 1.0 \
    -l 2 ${COL_MASS_K_CO2} ${TOL} \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBAND}_l -m ${K_COEFF_DIR}/co2_s${NBAND}_lm \
    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/co2_s${NBAND}_log && echo "CO2 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ch4_s${NBAND}_l ] || \
    [ ! -s $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc ] ; then
  echo "CH4"
  rm -f ${K_COEFF_DIR}/ch4_s${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R ${BAND_FIRST_CH4} ${NBAND} -c 2500.0 -i 1.0 \
    -l 6 ${COL_MASS_K_CH4} ${TOL} \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_s${NBAND}_l -m ${K_COEFF_DIR}/ch4_s${NBAND}_lm \
    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/ch4_s${NBAND}_log && echo "CH4 done" &
fi

echo
echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBAND}_l ] || \
    [ ! -s $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc ] ; then
  echo "H2O lines"
  rm -f ${K_COEFF_DIR}/h2o_s${NBAND}_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R ${BAND_NIR_START} ${NBAND} -c 2500.0 -i 1.0 \
    -l 1 ${COL_MASS_K_H2O} ${TOL} \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBAND}_l -m ${K_COEFF_DIR}/h2o_s${NBAND}_lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_s${NBAND}_log && echo "H2O lines done"
  echo
fi

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBAND}_s ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o_s${NBAND}_s*
  Ccorr_k -C 33 1.0e-4 1.0e4 -F ../${PT_FILE} -D $HITRAN_H2O \
    -P 7 -R ${BAND_NIR_START} ${NBAND} -c 2500.0 -i 1.0 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s $specfile ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/h2o_s${NBAND}_s -m ${K_COEFF_DIR}/h2o_s${NBAND}_sm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/h2o_s${NBAND}_slog \
     && echo "H2O self-broadened continuum done"
fi

wait

echo "All done"

exit 0