#!/bin/bash

# Setting for k-coefficient calculation
SP_ID="dsa_ar_lowch4"
SOLAR_SPEC="sun_2.9gyr"
PT_FILE="pt663"

# Paths
. set_paths

# This script creates the 6 band SW spectral file sp_sw_6_jm2
# from scratch using HITRAN database files available in August 2013.
# The following files (available from www.cfa.harvard.edu/hitran)
# are required in HITRAN_DIR (set to your local HITRAN directory):

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"

# Water vapour continuum uses CAVIAR data contained within the
# suite ($RAD_DATA/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script should be run after the LbL files have been created
# by running the script for the 260 band file.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

ref_pt_file="$RAD_DATA/gases/ref_pt"

# Create skeleton spectral file
specfile="sp_sw_6_${SP_ID}_skel"
rm -f $specfile
. mk_sp_sw_6_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

# Construct weight argument
WGT="+S ${SOLAR_SPEC_DIR}/${SOLAR_SPEC}"

# Hadgem bands ->  220        ->  260 bands:
#            1 ->    1 -  38  ->  1/6 -  29
#            2 ->   38 -  91  ->   30 -  66
#            3 ->   91 - 118  ->   67 - 103
#            4 ->  118 - 148  ->  104 - 154
#            5 ->  148 - 188  ->  155 - 214
#            6 ->  188 - 220  ->  215 - 260

# Gases

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_s6_4l ] ; then
  echo "CO2 band 4"
  rm -f ${K_COEFF_DIR}/co2_s6_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 4 4 -c 2500.0 -i 1.0 -l 2 1.6e2 -t 4.0e-3  \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s6_4l -m ${K_COEFF_DIR}/co2_s6_4lm \
    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/co2_s6_4log \
    && echo "CO2 band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_s6_5l ] ; then
  echo "CO2 band 5"
  rm -f ${K_COEFF_DIR}/co2_s6_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 5 5 -c 2500.0 -i 1.0 -l 2 1.6e2 -t 3.0e-3  \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s6_5l -m ${K_COEFF_DIR}/co2_s6_5lm \
    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/co2_s6_5log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_s6_6l ] ; then
  echo "CO2 band 6"
  rm -f ${K_COEFF_DIR}/co2_s6_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 6 6 -c 2500.0 -i 1.0 -l 2 1.6e2 -t 6.0e-3  \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s6_6l -m ${K_COEFF_DIR}/co2_s6_6lm \
    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/co2_s6_6log \
    && echo "CO2 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ch4_s6_5l ] ; then
  echo "CH4 band 5"
  rm -f ${K_COEFF_DIR}/ch4_s6_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 5 5 -c 2500.0 -i 1.0 -l 6 1.0e-2 -t 6.0e-3  \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_s6_5l -m ${K_COEFF_DIR}/ch4_s6_5lm \
    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/ch4_s6_5log \
    && echo "CH4 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_s6_6l ] ; then
  echo "CH4 band 6"
  rm -f ${K_COEFF_DIR}/ch4_s6_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 6 6 -c 2500.0 -i 1.0 -l 6 1.0e-2 -t 6.0e-3  \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_s6_6l -m ${K_COEFF_DIR}/ch4_s6_6lm \
    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/ch4_s6_6log \
    && echo "CH4 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2o_s6_3l ] ; then
  echo "H2O lines band 3"
  rm -f ${K_COEFF_DIR}/h2o_s6_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 3 3 -c 2500.0 -i 1.0 -l 1 1.0e2 -n 2  \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s6_3l -m ${K_COEFF_DIR}/h2o_s6_3lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s6_3log \
    && echo "H2O lines band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s6_4l ] ; then
  echo "H2O lines band 4"
  rm -f ${K_COEFF_DIR}/h2o_s6_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 4 4 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 3.0e-3  \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s6_4l -m ${K_COEFF_DIR}/h2o_s6_4lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s6_4log \
    && echo "H2O lines band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s6_5l ] ; then
  echo "H2O lines band 5"
  rm -f ${K_COEFF_DIR}/h2o_s6_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 5 5 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 4.0e-3  \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s6_5l -m ${K_COEFF_DIR}/h2o_s6_5lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s6_5log \
    && echo "H2O lines band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s6_6l ] ; then
  echo "H2O lines band 6"
  rm -f ${K_COEFF_DIR}/h2o_s6_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 6 6 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 6.0e-3  \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s6_6l -m ${K_COEFF_DIR}/h2o_s6_6lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s6_6log \
    && echo "H2O lines band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2o_s6_s ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o_s6_s*
  Ccorr_k -C 33 1.0e-4 1.0e4 -F ../${PT_FILE} -D $HITRAN_H2O \
    -P 7 -R 3 6 -c 2500.0 -i 1.0 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s $specfile ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/h2o_s6_s -m ${K_COEFF_DIR}/h2o_s6_sm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s6_slog \
    && echo "H2O self-broadened continuum done" &
fi

wait

echo "All done"

exit 0
