#!/bin/bash

# Setting for k-coefficient calculation
SP_ID="dsa_ar10bar"
SP_FLDR="dsa_ar10bar"
NBANDS="43"
SOLAR_SPEC="sun"
PT_FILE="pt793"
TOL="-t 5.0e-4"
BAND_NIR_START="7" # 5.000000000E-07 m

# For molecules with near-IR absorption, the index of the first band for which
# to calculate absorption
BAND_FIRST_H2O="4"  # 25710 cm-1 = 3.88953714507973e-07 m
BAND_FIRST_CO2="10" # 12784 cm-1 = 7.82224331232518e-07 m
BAND_FIRST_CH4="11" # 11501 cm-1 = 8.69423652540053e-07 m

# Column masses for all molecules for k-coefficient calculation
COL_MASS_K_H2O="1.0e3" # 1.0e3 for 10.0 bar atm
COL_MASS_K_CO2="1.6e3" # 1.6e3 for 10.0 bar atm
COL_MASS_K_CH4="5.8e2" # 5.8e2 for 10.0 bar atm

# Continuum column masses
COL_H2OC="1.0e+03"
COL_N2_CH4="4.0e+03"
COL_N2_N2="7.0e+05"
COL_N2_H2="3.0e+04"
COL_H2_CO2="1.0e+04"
COL_H2_CH4="4.0e+03"
COL_H2_H2="5.0e+04"

# Column masses for all molecules for eliminating weak absorbers
COL_MASS_ELIM_H2O="2.5e2" # 2.5e2 for 10.0 bar atm
COL_MASS_ELIM_CO2="1.6e3" # 1.6e3 for 10.0 bar atm
COL_MASS_ELIM_CH4="5.8e2" # 5.8e2 for 10.0 bar atm

# Column masses for all molecules for eliminating weak absorbers
COL_MASS_STMJ_H2O="2.5e2" # 2.5e2 for 10.0 bar atm
COL_MASS_STMJ_CO2="1.6e3" # 1.6e3 for 10.0 bar atm
COL_MASS_STMJ_CH4="5.8e2" # 5.8e2 for 10.0 bar atm
