#!/bin/bash

# This script creates the SW cloud fits.

SOLAR_SPEC="pc"
NBAND="21"
SP_ID="dsa"

. ../set_paths_sw

# Skeletal spectral file
SPECFILE="sp_sw_${NBAND}_${SP_ID}_skel"

# Cscatter_average requires -S as weighting argument, not +S
WGT="-S ${SOLAR_SPEC_DIR}/${SOLAR_SPEC}"

mkdir -p ${CLD_COEFF_DIR}

if [ ! -s ${CLD_COEFF_DIR}/fit_sw_drop5_${NBAND} ] ; then
  echo 'Type 5 droplets'
  rm -f ${CLD_COEFF_DIR}/mon_sw_drop5_${NBAND}
  Cscatter_average -s ${SPECFILE} -P 1 -t ${WGT} \
    -f 5 ${CLD_COEFF_DIR}/fit_sw_drop5_${NBAND} \
    ${CLD_COEFF_DIR}/mon_sw_drop5_${NBAND} 1.e3 \
    ${RAD_DATA}/cloud/scatter_drop_type5
fi
if [ ! -s ${CLD_COEFF_DIR}/fit_sw_ice8_${NBAND} ] ; then
  echo 'Type 8 ice'
  rm -f ${CLD_COEFF_DIR}/mon_sw_ice8_${NBAND}
  Cscatter_average -s ${SPECFILE} -P 1 -w ${WGT} \
    -f 12 ${CLD_COEFF_DIR}/fit_sw_ice8_${NBAND} \
    ${CLD_COEFF_DIR}/mon_sw_ice8_${NBAND} 920 \
    ${RAD_DATA}/cloud/scatter_ice_sw_type8
fi
