#!/bin/bash

# Setting for k-coefficient calculation
SP_ID="dsa"
SOLAR_SPEC="sun"
PT_FILE="pt663"
NBANDS="21"

. ../set_paths_sw

# The following files (available from www.cfa.harvard.edu/hitran)
# are required in HITRAN_DIR (set to your local HITRAN directory):

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_O3="$HITRAN_DIR/03_hit12.par"
HITRAN_N2O="$HITRAN_DIR/04_hit08.par"
HITRAN_UV_N2O="$HITRAN_DIR/N2O-UV00.xsc"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"
HITRAN_O2="$HITRAN_DIR/07_hit12.par"
HITRAN_UV_O2="$HITRAN_DIR/07_UV06.par"
HITRAN_SO2="$HITRAN_DIR/09_hit12.par"
HITRAN_UV_SO2="$HITRAN_DIR/SO2_UV08.xsc"
HITRAN_OCS="$HITRAN_DIR/19_hit12.par"

HITRAN_UV_O3="$RAD_DATA/gases/ser_bdm_o3.xsc"
JPL_UV_O2="$RAD_DATA/gases/jpl_o2.xsc"

# Water vapour continuum uses CAVIAR data contained within the
# suite ($RAD_DATA/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script should be run after the LbL files have been created
# by running the script for the 280 band file.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

o3_pt_file="$RAD_DATA/gases/pt_o3_ser"
o2_pt_file="$RAD_DATA/gases/pt_o2_jpl"
n2o_pt_file="$RAD_DATA/gases/pt_n2o_uv"
so2_pt_file="$RAD_DATA/gases/pt_so2_uv"
ref_pt_file="$RAD_DATA/gases/ref_pt"

# Create skeleton spectral file
specfile="sp_sw_${NBANDS}_${SP_ID}_skel"
rm -f $specfile
. mk_sp_sw_${NBANDS}_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

# Construct weight argument
WGT="+S ${SOLAR_SPEC_DIR}/${SOLAR_SPEC}"

# Gases

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_5l ] ; then
  echo "CO2 band 5"
  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 10 17 -c 2500.0 -i 1.0 -l 2 1.0e1 -t 4.0e-3 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBANDS}_5l \
    -m ${K_COEFF_DIR}/co2_s${NBANDS}_5lm \
    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_s${NBANDS}_5log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_6l ] ; then
  echo "CO2 band 6"
  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 2 1.0e1 -t 1.0e-2 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBANDS}_6l \
    -m ${K_COEFF_DIR}/co2_s${NBANDS}_6lm \
    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_s${NBANDS}_6log \
    && echo "CO2 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/o3_u${NBANDS}_1-2l ] ; then
  echo "O3 bands 1-2"
  rm -f ${K_COEFF_DIR}/o3_u${NBANDS}_1-2l*
  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
    -R 1 2 -c 2500.0 -i 1.0 -l 3 1.0e-2 -t 1.0e-3 \
    -s $specfile ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/o3_u${NBANDS}_1-2l \
    -m ${K_COEFF_DIR}/o3_u${NBANDS}_1-2lm \
    -L $SW_DATA/o3_lbl_uv_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/o3_u${NBANDS}_1-2log \
    && echo "O3 bands 1-2 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o3_u${NBANDS}_3-4l ] ; then
  echo "O3 bands 3-4"
  rm -f ${K_COEFF_DIR}/o3_u${NBANDS}_3-4l*
  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
    -R 3 9 -c 2500.0 -i 1.0 -l 3 1.0e-2 -t 1.0e-2 \
    -s $specfile ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/o3_u${NBANDS}_3-4l \
    -m ${K_COEFF_DIR}/o3_u${NBANDS}_3-4lm \
    -L $SW_DATA/o3_lbl_uv_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/o3_u${NBANDS}_3-4log \
    && echo "O3 bands 3-4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o3_s${NBANDS}_6l ] ; then
  echo "O3 band 6"
  rm -f ${K_COEFF_DIR}/o3_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O3 \
    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 3 1.0e-2 -t 1.0e-2 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/o3_s${NBANDS}_6l \
    -m ${K_COEFF_DIR}/o3_s${NBANDS}_6lm \
    -L $SW_DATA/o3_lbl_sw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/o3_s${NBANDS}_6log \
    && echo "O3 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/n2o_s${NBANDS}_6l ] ; then
  echo "N2O band 6"
  rm -f ${K_COEFF_DIR}/n2o_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 4 5.0e-3 -t 6.0e-3 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/n2o_s${NBANDS}_6l \
    -m ${K_COEFF_DIR}/n2o_s${NBANDS}_6lm \
    -L $SW_DATA/n2o_lbl_sw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/n2o_s${NBANDS}_6log \
    && echo "N2O band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ch4_s${NBANDS}_5l ] ; then
  echo "CH4 band 5"
  rm -f ${K_COEFF_DIR}/ch4_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 10 17 -c 2500.0 -i 1.0 -l 6 1.0e-2 -t 6.0e-3 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_s${NBANDS}_5l \
    -m ${K_COEFF_DIR}/ch4_s${NBANDS}_5lm \
    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_s${NBANDS}_5log \
    && echo "CH4 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_s${NBANDS}_6l ] ; then
  echo "CH4 band 6"
  rm -f ${K_COEFF_DIR}/ch4_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 6 1.0e-2 -t 6.0e-3 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_s${NBANDS}_6l \
    -m ${K_COEFF_DIR}/ch4_s${NBANDS}_6lm \
    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_s${NBANDS}_6log \
    && echo "CH4 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/o2_u${NBANDS}_1l ] ; then
  echo "O2 band 1"
  rm -f ${K_COEFF_DIR}/o2_u${NBANDS}_1l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_UV_O2 \
    -R 1 1 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 1.0e-2 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/o2_u${NBANDS}_1l \
    -m ${K_COEFF_DIR}/o2_u${NBANDS}_1lm \
    -L $SW_DATA/o2_lbl_uv_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/o2_u${NBANDS}_1log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o2_s${NBANDS}_3l ] ; then
  echo "O2 band 3"
  rm -f ${K_COEFF_DIR}/o2_s${NBANDS}_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O2 \
    -R 3 3 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 1.0e-2 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/o2_s${NBANDS}_3l \
    -m ${K_COEFF_DIR}/o2_s${NBANDS}_3lm \
    -L $SW_DATA/o2_lbl_sw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/o2_s${NBANDS}_3log \
    && echo "O2 band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o2_s${NBANDS}_4l ] ; then
  echo "O2 band 4"
  rm -f ${K_COEFF_DIR}/o2_s${NBANDS}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O2 \
    -R 4 10 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 2.2e-3 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/o2_s${NBANDS}_4l \
    -m ${K_COEFF_DIR}/o2_s${NBANDS}_4lm \
    -L $SW_DATA/o2_lbl_sw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/o2_s${NBANDS}_4log \
    && echo "O2 band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o2_s${NBANDS}_5l ] ; then
  echo "O2 band 5"
  rm -f ${K_COEFF_DIR}/o2_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O2 \
    -R 11 17 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 1.0e-2 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/o2_s${NBANDS}_5l \
    -m ${K_COEFF_DIR}/o2_s${NBANDS}_5lm \
    -L $SW_DATA/o2_lbl_sw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/o2_s${NBANDS}_5log \
    && echo "O2 band 5 done" &
fi

if [ ! -s ${K_COEFF_DIR}/so2_s${NBANDS}_6l ] ; then
  echo "SO2 band 6"
  rm -f ${K_COEFF_DIR}/so2_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_SO2 \
    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 9 3.0e-4 -t 1.0e-3 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/so2_s${NBANDS}_6l \
    -m ${K_COEFF_DIR}/so2_s${NBANDS}_6lm \
    -L $SW_DATA/so2_lbl_sw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/so2_s${NBANDS}_6log \
    && echo "SO2 band 6 done" &
fi
if [ ! -s ${K_COEFF_DIR}/so2_u${NBANDS}_1-2l ] ; then
  echo "SO2 band 1-2"
  rm -f ${K_COEFF_DIR}/so2_u${NBANDS}_1-2l*
  Ccorr_k -F $so2_pt_file -X $HITRAN_UV_SO2 \
    -R 1 2 -c 2500.0 -i 1.0 -l 9 3.0e-4 -t 1.0e-3 \
    -s $specfile ${WGT} -q -r $ref_pt_file \
    -o ${K_COEFF_DIR}/so2_u${NBANDS}_1-2l \
    -m ${K_COEFF_DIR}/so2_u${NBANDS}_1-2lm \
    -L $SW_DATA/so2_lbl_uv_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/so2_u${NBANDS}_1-2log \
    && echo "SO2 band 1-2 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ocs_s${NBANDS}_6l ] ; then
  echo "OCS band 6"
  rm -f ${K_COEFF_DIR}/ocs_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_OCS \
    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 25 1.0e-3 -t 1.0e-3 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/ocs_s${NBANDS}_6l \
    -m ${K_COEFF_DIR}/ocs_s${NBANDS}_6lm \
    -L $SW_DATA/ocs_lbl_sw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ocs_s${NBANDS}_6log \
    && echo "OCS band 6 done" &
fi

echo "Jobs running in the foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_3l ] ; then
  echo "H2O lines band 3"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_3l*
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 3 3 -c 2500.0 -i 1.0 -l 1 1.0e2 -n 2 \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_3l \
    -m ${K_COEFF_DIR}/h2o_s${NBANDS}_3lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_3log \
    && echo "H2O lines band 3 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_4l ] ; then
  echo "H2O lines band 4"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 4 10 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 6.0e-3 \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_4l \
    -m ${K_COEFF_DIR}/h2o_s${NBANDS}_4lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_4log \
    && echo "H2O lines band 4 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_5l ] ; then
  echo "H2O lines band 5"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 11 17 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 6.0e-3 \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_5l \
    -m ${K_COEFF_DIR}/h2o_s${NBANDS}_5lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_5log \
    && echo "H2O lines band 5 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_6l ] ; then
  echo "H2O lines band 6"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 1 1.0e2 -t 6.0e-3 \
    -s $specfile ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_6l \
    -m ${K_COEFF_DIR}/h2o_s${NBANDS}_6lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_6log \
    && echo "H2O lines band 6 done"
fi

if [ ! -s ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c*
  Ccorr_k -F ../pt_cont \
    -R 3 ${NBANDS} -i 1.0 -ct 1 1 10.0 -t 1.0e-3 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c \
    -m ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6cm \
    -L $SW_DATA/h2o-h2o_lbl_sw.nc \
    -lw ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6clog \
    && echo "H2O self-broadened continuum done"
fi

wait

echo "All done"

exit 0
