#!/bin/bash

SP_ID="dsa"
SOLAR_SPEC="sun"
PT_FILE="pt663"
NBANDS="21"

. ../set_paths_sw

# Create full path to spectral file
SPEC_FILE="${SPEC_FILE_DIR}/sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}"

# Remove old version
rm -f ${SPEC_FILE}
rm -f ${SPEC_FILE}_k

# Replace old k-coefficients by new k-coefficients in spectral file
prep_spec << EOF
sp_sw_${NBANDS}_${SP_ID}_skel
n
${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_s${NBANDS}_3l
5
y
${K_COEFF_DIR}/h2o_s${NBANDS}_4l
5
y
${K_COEFF_DIR}/h2o_s${NBANDS}_5l
5
y
${K_COEFF_DIR}/h2o_s${NBANDS}_6l
19
${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c
5
y
${K_COEFF_DIR}/co2_s${NBANDS}_5l
5
y
${K_COEFF_DIR}/co2_s${NBANDS}_6l
5
y
${K_COEFF_DIR}/o3_u${NBANDS}_1-2l
5
y
${K_COEFF_DIR}/o3_u${NBANDS}_3-4l
5
y
${K_COEFF_DIR}/o3_s${NBANDS}_6l
5
y
${K_COEFF_DIR}/n2o_s${NBANDS}_6l
5
y
${K_COEFF_DIR}/ch4_s${NBANDS}_5l
5
y
${K_COEFF_DIR}/ch4_s${NBANDS}_6l
5
y
${K_COEFF_DIR}/o2_u${NBANDS}_1l
5
y
${K_COEFF_DIR}/o2_s${NBANDS}_3l
5
y
${K_COEFF_DIR}/o2_s${NBANDS}_4l
5
y
${K_COEFF_DIR}/o2_s${NBANDS}_5l
5
y
${K_COEFF_DIR}/so2_s${NBANDS}_6l
5
y
${K_COEFF_DIR}/so2_u${NBANDS}_1-2l
5
y
${K_COEFF_DIR}/ocs_s${NBANDS}_6l
-1
EOF

# Add cloud fits to spectral file
prep_spec << EOF
${SPEC_FILE}
a
10
5
${CLD_COEFF_DIR}/fit_sw_drop5_6
1.50000E-06 5.00000E-05
12
8
${CLD_COEFF_DIR}/fit_sw_ice8_6
7.00000E-06 3.20000E-04
-1
EOF

# Add solar spectrum and Rayleigh scattering coefficients
prep_spec << EOF
${SPEC_FILE}
a
2
n
${SOLAR_SPEC_DIR}/${SOLAR_SPEC}
y
3
a
-1
EOF

# Tidy up and set continuum overlap method
tidy_90 << EOF
${SPEC_FILE}
o
1
1.0e2
1.0e1
1.0e-2
5.0e-3
1.0e-2
2.3e3
3.0e-4
1.0e-3
10.0
0.999990
6
1.0e2
1.0e1
1.0e-2
5.0e-3
1.0e-2
2.3e3
3.0e-4
1.0e-3
10.0
n
8
1
-1
EOF