#!/bin/bash

# This script creates the k-coefficients.

PT_FILE="pt663"
CFC113_PT_FILE="$RAD_DATA/gases/pt_cfc113"
REF_PT_FILE="../ref_pt"
WGT="-u"

. ../set_paths_lw

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_O3="$HITRAN_DIR/03_hit12.par"
HITRAN_N2O="$HITRAN_DIR/04_hit08.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"
HITRAN_O2="$HITRAN_DIR/07_hit12.par"
HITRAN_SO2="$HITRAN_DIR/09_hit12.par"
HITRAN_OCS="$HITRAN_DIR/19_hit12.par"
HITRAN_CFC11="$HITRAN_DIR/CFC-11_IR00.xsc"
HITRAN_CFC12="$HITRAN_DIR/CFC-12_IR00.xsc"
HITRAN_CFC113="$HITRAN_DIR/CFC-113_IR00.xsc"
HITRAN_HCFC22="$HITRAN_DIR/HCFC-22_IR01.xsc"
HITRAN_HFC134a="$HITRAN_DIR/HFC-134a_IR00.xsc"

# Water vapour continuum uses CAVIAR data contained within the
# suite ($RAD_DATA/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script takes a very long time to run initially (probably
# several days if not done in parallel). However once the
# line-by-line netCDF files have been created, subsequent runs will
# use these files and the whole script should run in around an hour.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Create skeleton spectral file
SPECFILE="sp_lw_350_jm2dsa_skel"
rm -f ${SPECFILE}
. mk_sp_lw_350_jm2dsa_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

# Hadgem bands ->  300 bands:
#            1 ->    1 -  40
#            2 ->   41 -  55
#            3 ->   56 -  59 +  76 -  80
#            4 ->   60 -  75
#            5 ->   81 -  99 + 113 - 120
#            6 ->  100 - 112
#            7 ->  121 - 133
#            8 ->  134 - 150
#            9 ->  151 - 300

# Gases

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_l350_l ] || \
    [ ! -s ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc ] ; then
  echo "CO2"
  rm -f ${K_COEFF_DIR}/co2_l350_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 1 350 -c 2500.0 -i 0.1 -l 2 1.0e1 -b 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l350_l -m ${K_COEFF_DIR}/co2_l350_lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/co2_l350_log && echo "CO2 done" &
fi

if [ ! -s ${K_COEFF_DIR}/o3_l350_l ] || \
    [ ! -s ${ABS_COEFF_DIR}/o3_lbl_lw_${PT_FILE}.nc ] ; then
  echo "O3"
  rm -f ${K_COEFF_DIR}/o3_l350_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O3 \
    -R 1 350 -c 2500.0 -i 0.1 -l 3 1.0e-2 -b 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/o3_l350_l -m ${K_COEFF_DIR}/o3_l350_lm \
    -L ${ABS_COEFF_DIR}/o3_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/o3_l350_log && echo "O3 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ch4_l350_l ] || \
    [ ! -s ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc ] ; then
  echo "CH4"
  rm -f ${K_COEFF_DIR}/ch4_l350_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 1 350 -c 2500.0 -i 0.1 -l 6 1.0e-2 -b 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l350_l -m ${K_COEFF_DIR}/ch4_l350_lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/ch4_l350_log && echo "CH4 done" &
fi

if [ ! -s ${K_COEFF_DIR}/n2o_l350_l ] || \
    [ ! -s ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc ] ; then
  echo "N2O"
  rm -f ${K_COEFF_DIR}/n2o_l350_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 1 350 -c 2500.0 -i 0.1 -l 4 5.0e-3 -b 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/n2o_l350_l -m ${K_COEFF_DIR}/n2o_l350_lm \
    -L ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/n2o_l350_log && echo "N2O done" &
fi

if [ ! -s ${K_COEFF_DIR}/so2_l350_l ] || \
    [ ! -s ${ABS_COEFF_DIR}/so2_lbl_lw_${PT_FILE}.nc ] ; then
  echo "SO2"
  rm -f ${K_COEFF_DIR}/so2_l350_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_SO2 \
    -R 1 350 -c 2500.0 -i 0.1 -l 9 3.0e-4 -b 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/so2_l350_l -m ${K_COEFF_DIR}/o2_l350_lm \
    -L ${ABS_COEFF_DIR}/so2_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/so2_l350_log && echo "SO2 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ocs_l350_l ] || \
    [ ! -s ${ABS_COEFF_DIR}/ocs_lbl_lw_${PT_FILE}.nc ] ; then
  echo "OCS"
  rm -f ${K_COEFF_DIR}/ocs_l350_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_OCS \
    -R 1 350 -c 2500.0 -i 0.1 -l 25 1.0e-3 -b 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ocs_l350_l -m ${K_COEFF_DIR}/ocs_l350_lm \
    -L ${ABS_COEFF_DIR}/ocs_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/ocs_l350_log && echo "OCS done" &
fi

echo
echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_l350_l ] || \
    [ ! -s ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc ] ; then
  echo "H2O lines and foreign continuum"
  rm -f ${K_COEFF_DIR}/h2o_l350_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 1 350 -c 2500.0 -i 0.1 -l 1 1.0e2 -b 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk -np 8 \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l350_l -m ${K_COEFF_DIR}/h2o_l350_lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/h2o_l350_log
fi

if [ ! -s ${K_COEFF_DIR}/h2o_l350_s ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o_l350_s*
  Ccorr_k -C 33 1.0e-4 1.0e4 -F ../${PT_FILE} -D $HITRAN_H2O \
    -P 7 -R 1 350 -c 2500.0 -i 0.1 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s ${SPECFILE} ${WGT} -q -r ${REF_PT_FILE} \
    -o ${K_COEFF_DIR}/h2o_l350_s -m ${K_COEFF_DIR}/h2o_l350_sm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/h2o_l350_slog
fi


# Halocarbons

if [ ! -s ${K_COEFF_DIR}/cfc11_l350_l ] ; then
  echo "CFC 11"
  rm -f ${K_COEFF_DIR}/cfc11_l350_l*
  Ccorr_k -F ../${PT_FILE} -X $HITRAN_CFC11 \
    -R 81 120 -i 1.0 -l 14 0.1e-4 -t 1.0e-4 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/cfc11_l350_l -m ${K_COEFF_DIR}/cfc11_l350_lm \
    -L ${ABS_COEFF_DIR}/cfc11_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/cfc11_l350_log
fi

if [ ! -s ${K_COEFF_DIR}/cfc12_l350_l ] ; then
  echo "CFC 12"
  rm -f ${K_COEFF_DIR}/cfc12_l350_l*
  Ccorr_k -F ../${PT_FILE} -X $HITRAN_CFC12 \
    -R 81 120 -i 1.0 -l 15 0.2e-4 -t 1.0e-4 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/cfc12_l350_l -m ${K_COEFF_DIR}/cfc12_l350_lm \
    -L ${ABS_COEFF_DIR}/cfc12_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/cfc12_l350_log
fi

if [ ! -s ${K_COEFF_DIR}/cfc113_l350_l ] ; then
  echo "CFC 113"
  rm -f ${K_COEFF_DIR}/cfc113_l350_l*
  Ccorr_k -F ${CFC113_PT_FILE} -X $HITRAN_CFC113 \
    -R 56 133 -i 1.0 -l 16 0.4e-5 -t 1.0e-4 \
    -s ${SPECFILE} ${WGT} -q -r ${REF_PT_FILE} \
    -o ${K_COEFF_DIR}/cfc113_l350_l -m ${K_COEFF_DIR}/cfc113_l350_lm \
    -L ${ABS_COEFF_DIR}/cfc113_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/cfc113_l350_log
fi

if [ ! -s ${K_COEFF_DIR}/hcfc22_l350_l ] ; then
  echo "HCFC 22"
  rm -f ${K_COEFF_DIR}/hcfc22_l350_l*
  Ccorr_k -F ../${PT_FILE} -X $HITRAN_HCFC22 \
    -R 56 150 -i 1.0 -l 17 0.6e-5 -t 1.0e-4 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/hcfc22_l350_l -m ${K_COEFF_DIR}/hcfc22_l350_lm \
    -L ${ABS_COEFF_DIR}/hcfc22_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/hcfc22_l350_log
fi

if [ ! -s ${K_COEFF_DIR}/hfc134a_l350_l ] ; then
  echo "HFC 134a"
  rm -f ${K_COEFF_DIR}/hfc134a_l350_l*
  Ccorr_k -F ../${PT_FILE} -X $HITRAN_HFC134a \
    -R 81 150 -i 1.0 -l 19 0.3e-5 -t 1.0e-4 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/hfc134a_l350_l -m ${K_COEFF_DIR}/hfc134a_l350_lm \
    -L ${ABS_COEFF_DIR}/hfc134a_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/hfc134a_l350_log
fi

exit 0
