#!/bin/bash

# This script creates the k-coefficients.

PT_FILE="pt663"
REF_PT_FILE="../ref_pt"
WGT="+p"

HITRAN_DIR="/home/damundse/Line_lists/HITRAN"
ABS_COEFF_DIR="/home/damundse/Abs_coeff"
K_COEFF_DIR="/home/damundse/k-coeff/lw_jm3dsa/${PT_FILE}"

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_O3="$HITRAN_DIR/03_hit12.par"
HITRAN_N2O="$HITRAN_DIR/04_hit08.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"
HITRAN_O2="$HITRAN_DIR/07_hit12.par"
HITRAN_SO2="$HITRAN_DIR/09_hit12.par"
HITRAN_OCS="$HITRAN_DIR/19_hit12.par"
HITRAN_CFC11="$HITRAN_DIR/CFC-11_IR00.xsc"
HITRAN_CFC12="$HITRAN_DIR/CFC-12_IR00.xsc"
HITRAN_CFC113="$HITRAN_DIR/CFC-113_IR00.xsc"
HITRAN_HCFC22="$HITRAN_DIR/HCFC-22_IR01.xsc"
HITRAN_HFC134a="$HITRAN_DIR/HFC-134a_IR00.xsc"

# Water vapour continuum uses CAVIAR data contained within the
# suite ($RAD_DATA/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script should be run after the LbL files have been created
# by running the script for the 350 band file.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

CFC113_PT_FILE="$RAD_DATA/gases/pt_cfc113"

# Create skeleton spectral file
SPECFILE="sp_lw_9_jm3dsa_skel"
rm -f ${SPECFILE}
. mk_sp_lw_9_jm3dsa_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

# Hadgem bands ->  300 bands:
#            1 ->    1 -  40
#            2 ->   41 -  55
#            3 ->   56 -  59 +  76 -  80
#            4 ->   60 -  75
#            5 ->   81 -  99 + 113 - 120
#            6 ->  100 - 112
#            7 ->  121 - 133
#            8 ->  134 - 150
#            9 ->  151 - 300

# Gases

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_l9_3l ] ; then
  echo "CO2 band 3"
  rm -f ${K_COEFF_DIR}/co2_l9_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 3 3 -c 2500.0 -i 0.1 -l 2 0.5e1 -b 2.5e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l9_3l -m ${K_COEFF_DIR}/co2_l9_3lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/co2_l9_3log \
    && echo "CO2 band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l9_4l ] ; then
  echo "CO2 band 4"
  rm -f ${K_COEFF_DIR}/co2_l9_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 4 4 -c 2500.0 -i 0.05 -l 2 1.0e2 -b 1.5e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l9_4l -m ${K_COEFF_DIR}/co2_l9_4lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/co2_l9_4log \
    && echo "CO2 band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l9_5l ] ; then
  echo "CO2 band 5"
  rm -f ${K_COEFF_DIR}/co2_l9_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 5 5 -c 2500.0 -i 0.1 -l 2 0.5e1 -b 1.5e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l9_5l -m ${K_COEFF_DIR}/co2_l9_5lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/co2_l9_5log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l9_6l ] ; then
  echo "CO2 band 6"
  rm -f ${K_COEFF_DIR}/co2_l9_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 6 6 -c 2500.0 -i 0.1 -l 2 0.5e1 -b 2.5e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l9_6l -m ${K_COEFF_DIR}/co2_l9_6lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/co2_l9_6log \
    && echo "CO2 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/o3_l9_3l ] ; then
  echo "O3 band 3"
  rm -f ${K_COEFF_DIR}/o3_l9_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O3 \
    -R 3 3 -c 2500.0 -i 0.1 -l 3 2.0e-4 -n 1  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/o3_l9_3l -m ${K_COEFF_DIR}/o3_l9_3lm \
    -L ${ABS_COEFF_DIR}/o3_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/o3_l9_3log \
    && echo "O3 band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o3_l9_4l ] ; then
  echo "O3 band 4"
  rm -f ${K_COEFF_DIR}/o3_l9_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O3 \
    -R 4 4 -c 2500.0 -i 0.1 -l 3 2.0e-4 -n 4  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/o3_l9_4l -m ${K_COEFF_DIR}/o3_l9_4lm \
    -L ${ABS_COEFF_DIR}/o3_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/o3_l9_4log \
    && echo "O3 band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/o3_l9_6l ] ; then
  echo "O3 band 6"
  rm -f ${K_COEFF_DIR}/o3_l9_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O3 \
    -R 6 6 -c 2500.0 -i 0.1 -l 3 2.0e-2 -n 10  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/o3_l9_6l -m ${K_COEFF_DIR}/o3_l9_6lm \
    -L ${ABS_COEFF_DIR}/o3_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/o3_l9_6log \
    && echo "O3 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/n2o_l9_3l ] ; then
  echo "N2O band 3"
  rm -f ${K_COEFF_DIR}/n2o_l9_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 3 3 -c 2500.0 -i 0.1 -l 4 5.0e-3 -n 2  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/n2o_l9_3l -m ${K_COEFF_DIR}/n2o_l9_3lm \
    -L ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/n2o_l9_3log \
    && echo "N2O band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/n2o_l9_5l ] ; then
  echo "N2O band 5"
  rm -f ${K_COEFF_DIR}/n2o_l9_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 5 5 -c 2500.0 -i 0.1 -l 4 1.0e-3 -n 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/n2o_l9_5l -m ${K_COEFF_DIR}/n2o_l9_5lm \
    -L ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/n2o_l9_5log \
    && echo "N2O band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/n2o_l9_7l ] ; then
  echo "N2O band 7"
  rm -f ${K_COEFF_DIR}/n2o_l9_7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 7 7 -c 2500.0 -i 0.1 -l 4 0.5e-3 -b 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/n2o_l9_7l -m ${K_COEFF_DIR}/n2o_l9_7lm \
    -L ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/n2o_l9_7log \
    && echo "N2O band 7 done" &
fi
if [ ! -s ${K_COEFF_DIR}/n2o_l9_8l ] ; then
  echo "N2O band 8"
  rm -f ${K_COEFF_DIR}/n2o_l9_8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 8 8 -c 2500.0 -i 0.1 -l 4 5.0e-3 -n 1  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/n2o_l9_8l -m ${K_COEFF_DIR}/n2o_l9_8lm \
    -L ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/n2o_l9_8log \
    && echo "N2O band 8 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ch4_l9_7l ] ; then
  echo "CH4 band 7"
  rm -f ${K_COEFF_DIR}/ch4_l9_7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 7 7 -c 2500.0 -i 0.1 -l 6 2.5e-3 -b 2.0e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l9_7l -m ${K_COEFF_DIR}/ch4_l9_7lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/ch4_l9_7log \
    && echo "CH4 band 7 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l9_8l ] ; then
  echo "CH4 band 8"
  rm -f ${K_COEFF_DIR}/ch4_l9_8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 8 8 -c 2500.0 -i 0.1 -l 6 5.0e-3 -n 3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l9_8l -m ${K_COEFF_DIR}/ch4_l9_8lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/ch4_l9_8log \
    && echo "CH4 band 8 done" &
fi

if [ ! -s ${K_COEFF_DIR}/so2_l9_l ] ; then
  echo "SO2 bands 1 to 8"
  rm -f ${K_COEFF_DIR}/so2_l9_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_SO2 \
    -R 1 8 -c 2500.0 -i 0.1 -l 9 3.0e-4 -b 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/so2_l9_l -m ${K_COEFF_DIR}/so2_l9_lm \
    -L ${ABS_COEFF_DIR}/so2_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/so2_l9_log \
    && echo "SO2 bands 1 to 8 done" &
fi
if [ ! -s ${K_COEFF_DIR}/so2_nir9_l ] ; then
  echo "SO2 band 9"
  rm -f ${K_COEFF_DIR}/so2_nir9_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_SO2 \
    -R 9 9 -c 2500.0 -i 0.1 -l 9 3.0e-4 -b 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/so2_nir9_l -m ${K_COEFF_DIR}/so2_nir9_lm \
    -L ${ABS_COEFF_DIR}/so2_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/so2_nir9_log \
    && echo "SO2 band 9 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ocs_l9_l ] ; then
  echo "OCS bands 1 to 8"
  rm -f ocs_l9_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_OCS \
    -R 1 8 -c 2500.0 -i 0.1 -l 25 1.0e-3 -b 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ocs_l9_l -m ${K_COEFF_DIR}/ocs_l9_lm \
    -L ${ABS_COEFF_DIR}/ocs_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/ocs_l9_log \
    && echo "OCS bands 1 to 8 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ocs_nir9_l ] ; then
  echo "OCS band 9"
  rm -f ${K_COEFF_DIR}/ocs_nir9_l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_OCS \
    -R 9 9 -c 2500.0 -i 0.1 -l 25 1.0e-3 -b 1.0e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ocs_nir9_l -m ${K_COEFF_DIR}/ocs_nir9_lm \
    -L ${ABS_COEFF_DIR}/ocs_lbl_lw_${PT_FILE}.nc > ${K_COEFF_DIR}/ocs_nir9_log \
    && echo "OCS band 9 done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2o_l9_1l ] ; then
  echo "H2O band 1"
  rm -f ${K_COEFF_DIR}/h2o_l9_1l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 1 1 -c 2500.0 -i 0.1 -l 1 1.0e2 -b 2.2e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l9_1l -m ${K_COEFF_DIR}/h2o_l9_1lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l9_1log && echo "H2O band 1 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l9_2l ] ; then
  echo "H2O band 2"
  rm -f ${K_COEFF_DIR}/h2o_l9_2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 2 2 -c 2500.0 -i 0.1 -l 1 2.5e1 -n 14  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l9_2l -m ${K_COEFF_DIR}/h2o_l9_2lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l9_2log && echo "H2O band 2 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l9_3l ] ; then
  echo "H2O band 3"
  rm -f ${K_COEFF_DIR}/h2o_l9_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 3 3 -c 2500.0 -i 0.1 -l 1 2.5e1 -n 5 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l9_3l -m ${K_COEFF_DIR}/h2o_l9_3lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l9_3log && echo "H2O band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l9_4l ] ; then
  echo "H2O band 4"
  rm -f ${K_COEFF_DIR}/h2o_l9_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 4 4 -c 2500.0 -i 0.1 -l 1 0.5e1 -n 4  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l9_4l -m ${K_COEFF_DIR}/h2o_l9_4lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l9_4log && echo "H2O band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l9_5l ] ; then
  echo "H2O band 5"
  rm -f ${K_COEFF_DIR}/h2o_l9_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 5 5 -c 2500.0 -i 0.1 -l 1 0.5e1 -n 6  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l9_5l -m ${K_COEFF_DIR}/h2o_l9_5lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l9_5log && echo "H2O band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l9_6l ] ; then
  echo "H2O band 6"
  rm -f ${K_COEFF_DIR}/h2o_l9_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 6 6 -c 2500.0 -i 0.1 -l 1 0.5e1 -n 3  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l9_6l -m ${K_COEFF_DIR}/h2o_l9_6lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l9_6log && echo "H2O band 6 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l9_7l ] ; then
  echo "H2O band 7"
  rm -f ${K_COEFF_DIR}/h2o_l9_7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 7 7 -c 2500.0 -i 0.1 -l 1 0.5e1 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l9_7l -m ${K_COEFF_DIR}/h2o_l9_7lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l9_7log && echo "H2O band 7 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l9_8l ] ; then
  echo "H2O band 8"
  rm -f ${K_COEFF_DIR}/h2o_l9_8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 8 8 -c 2500.0 -i 0.1 -l 1 0.5e1 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l9_8l -m ${K_COEFF_DIR}/h2o_l9_8lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l9_8log && echo "H2O band 8 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l9_9l ] ; then
  echo "H2O band 9"
  rm -f ${K_COEFF_DIR}/h2o_l9_9l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 9 9 -c 2500.0 -i 0.1 -l 1 1.0e2 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l9_9l -m ${K_COEFF_DIR}/h2o_l9_9lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l9_9log && echo "H2O band 9 done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2o_l9_s ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o_l9_s*
  Ccorr_k -C 17 2.5e-1 2.5e2 -F ../${PT_FILE} -D $HITRAN_H2O \
    -P 7 -R 2 8 -c 2500.0 -i 0.1 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s ${SPECFILE} ${WGT} -q -r ${REF_PT_FILE} \
    -o ${K_COEFF_DIR}/h2o_l9_s -m ${K_COEFF_DIR}/h2o_l9_sm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l9_slog && echo "H2O self-broadened continuum done"
fi

# Halocarbons

if [ ! -s ${K_COEFF_DIR}/cfc11_l9_l ] ; then
  echo "CFC 11"
  rm -f ${K_COEFF_DIR}/cfc11_l9_l*
  Ccorr_k -F ../${PT_FILE} -X $HITRAN_CFC11 \
    -R 5 6 -i 1.0 -l 14 0.1e-4 -t 1.0e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/cfc11_l9_l -m ${K_COEFF_DIR}/cfc11_l9_lm \
    -L ${ABS_COEFF_DIR}/cfc11_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/cfc11_l9_log && echo "CFC 11 done"
fi

if [ ! -s ${K_COEFF_DIR}/cfc12_l9_l ] ; then
  echo "CFC 12"
  rm -f ${K_COEFF_DIR}/cfc12_l9_l*
  Ccorr_k -F ../${PT_FILE} -X $HITRAN_CFC12 \
    -R 5 6 -i 1.0 -l 15 0.2e-4 -t 1.0e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/cfc12_l9_l -m ${K_COEFF_DIR}/cfc12_l9_lm \
    -L ${ABS_COEFF_DIR}/cfc12_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/cfc12_l9_log && echo "CFC 12 done"
fi

if [ ! -s ${K_COEFF_DIR}/cfc113_l9_l ] ; then
  echo "CFC 113"
  rm -f ${K_COEFF_DIR}/cfc113_l9_l*
  Ccorr_k -F ${CFC113_PT_FILE} -X $HITRAN_CFC113 \
    -R 3 7 -i 1.0 -l 16 0.4e-5 -t 1.0e-3 \
    -s ${SPECFILE} ${WGT} -q -r ${REF_PT_FILE} \
    -o ${K_COEFF_DIR}/cfc113_l9_l -m ${K_COEFF_DIR}/cfc113_l9_lm \
    -L ${ABS_COEFF_DIR}/cfc113_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/cfc113_l9_log && echo "CFC 113 done"
fi

if [ ! -s ${K_COEFF_DIR}/hcfc22_l9_l ] ; then
  echo "HCFC 22"
  rm -f ${K_COEFF_DIR}/hcfc22_l9_l*
  Ccorr_k -F ../${PT_FILE} -X $HITRAN_HCFC22 \
    -R 3 8 -i 1.0 -l 17 0.6e-5 -t 1.0e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/hcfc22_l9_l -m ${K_COEFF_DIR}/hcfc22_l9_lm \
    -L ${ABS_COEFF_DIR}/hcfc22_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/hcfc22_l9_log && echo "HCFC 22 done"
fi

if [ ! -s ${K_COEFF_DIR}/hfc134a_l9_l ] ; then
  echo "HFC 134a"
  rm -f ${K_COEFF_DIR}/hfc134a_l9_l*
  Ccorr_k -F ../${PT_FILE} -X $HITRAN_HFC134a \
    -R 5 8 -i 1.0 -l 19 0.3e-5 -t 1.0e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/hfc134a_l9_l -m ${K_COEFF_DIR}/hfc134a_l9_lm \
    -L ${ABS_COEFF_DIR}/hfc134a_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/hfc134a_l9_log && echo "HFC 134a done"
fi

wait
echo "All done"

exit 0
