#!/bin/bash

NBANDS="9" # Number of bands
SP_ID="jm3dsa" # Spectral file ID
PT_FILE="pt663" # P-T grid

. ../set_paths_lw

# Create name of spectral file
SPEC_FILE="sp_lw_ga7_dsa"

mkdir -p ${SPEC_FILE_DIR}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}_k

# Construct spectral file

sp_lw_ga7_skel
prep_spec << EOF
sp_lw_9_jm3dsa_skel
n
${SPEC_FILE_DIR}/${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_l9_1l
5
y
${K_COEFF_DIR}/h2o_l9_2l
5
y
${K_COEFF_DIR}/h2o_l9_3l
5
y
${K_COEFF_DIR}/h2o_l9_4l
5
y
${K_COEFF_DIR}/h2o_l9_5l
5
y
${K_COEFF_DIR}/h2o_l9_6l
5
y
${K_COEFF_DIR}/h2o_l9_7l
5
y
${K_COEFF_DIR}/h2o_l9_8l
5
y
${K_COEFF_DIR}/h2o_l9_9l
9
${K_COEFF_DIR}/h2o_l9_s
5
y
${K_COEFF_DIR}/co2_l9_3l
5
y
${K_COEFF_DIR}/co2_l9_4l
5
y
${K_COEFF_DIR}/co2_l9_5l
5
y
${K_COEFF_DIR}/co2_l9_6l
5
y
${K_COEFF_DIR}/o3_l9_3l
5
y
${K_COEFF_DIR}/o3_l9_4l
5
y
${K_COEFF_DIR}/o3_l9_6l
5
y
${K_COEFF_DIR}/n2o_l9_3l
5
y
${K_COEFF_DIR}/n2o_l9_5l
5
y
${K_COEFF_DIR}/n2o_l9_7l
5
y
${K_COEFF_DIR}/n2o_l9_8l
5
y
${K_COEFF_DIR}/ch4_l9_7l
5
y
${K_COEFF_DIR}/ch4_l9_8l
5
y
${K_COEFF_DIR}/so2_l9_l
5
y
${K_COEFF_DIR}/so2_nir9_l
5
y
${K_COEFF_DIR}/ocs_l9_l
5
y
${K_COEFF_DIR}/ocs_nir9_l
5
y
${K_COEFF_DIR}/cfc11_l9_l
5
y
${K_COEFF_DIR}/cfc12_l9_l
5
y
${K_COEFF_DIR}/cfc113_l9_l
5
y
${K_COEFF_DIR}/hcfc22_l9_l
5
y
${K_COEFF_DIR}/hfc134a_l9_l
6
n
t
1 500
500
-1
EOF

# Add ice cloud optical properties only
prep_spec << EOF
${SPEC_FILE_DIR}/${SPEC_FILE}
a
10
5
${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS}
1.50000E-06 5.00000E-05
12
8
${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS}
8.00000E-06 3.20000E-04
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
tidy_90 << EOF
${SPEC_FILE_DIR}/${SPEC_FILE}
o
1
2.5e1
1.0e1
0.1e-1
0.5e-2
0.1e-1
3.0e-2
0.1e-4
0.2e-4
0.4e-5
0.6e-5
0.3e-5
1.0e-1
0.99990
6
2.5e1
1.0e1
0.1e-1
0.5e-2
0.1e-1
3.0e-6
0.1e-4
0.2e-4
0.4e-5
0.6e-5
0.3e-5
1.0e-5
-1
EOF

exit 0
