#!/bin/bash

# Setting for k-coefficient calculation
SP_ID="dsa_arva"
SP_FLDR="dsa_arva"
NBANDS="18"
SOLAR_SPEC="sun"
PT_FILE="pt663"
TOL="-b 1.0e-3"
BAND_NIR_START="3" # 5.000000000E-07 m

# For molecules with near-IR absorption, the index of the first band for which
# to calculate absorption
BAND_FIRST_H2O="2"  # 25710 cm-1 = 3.88953714507973e-07 m
BAND_FIRST_CO2="4" # 12784 cm-1 = 7.82224331232518e-07 m
BAND_FIRST_N2O="5" # 7797 cm-1 = 1.282604921754488e-06 m
BAND_FIRST_CH4="4" # 11501 cm-1 = 8.69423652540053e-07 m

# Column masses for all molecules for k-coefficient calculation
COL_MASS_K_H2O="1.0e+02"
COL_H2OC="10.0"
COL_MASS_K_CO2="1.6e+03"
COL_CO2C="1.0e2"
COL_MASS_K_N2O="16"
COL_MASS_K_CH4="5.8e-02"

# Column masses for all molecules for eliminating weak absorbers
COL_MASS_ELIM_H2O="2.5e+01"
COL_MASS_ELIM_CO2="1.6e+03"
COL_MASS_ELIM_N2O="16"
COL_MASS_ELIM_CH4="5.8e-02"

# Column masses for all molecules for eliminating weak absorbers
COL_MASS_STMJ_H2O="2.5e+02"
COL_MASS_STMJ_CO2="1.6e+03"
COL_MASS_STMJ_N2O="16"
COL_MASS_STMJ_CH4="5.8e-02"
