#!/bin/bash

# Setting for k-coefficient calculation
SP_ID="dsa_pm"
SP_FLDR="dsa_pm"
NBANDS="280"
SOLAR_SPEC="sun"
PT_FILE="pt793"
TOL="-t 5.0e-4"
BAND_NIR_START="66" # 5.000000000E-07 m

# For molecules with near-IR absorption, the index of the first band for which
# to calculate absorption
BAND_FIRST_H2O="30"  # 25710 cm-1 = 3.88953714507973e-07 m
BAND_FIRST_CO2="104" # 12784 cm-1 = 7.82224331232518e-07 m
BAND_FIRST_CH4="104" # 11501 cm-1 = 8.69423652540053e-07 m

# Column masses for all molecules for k-coefficient calculation
COL_MASS_K_H2O="1.0e+03"
COL_MASS_K_CO2="1.0e+05"
COL_MASS_K_CH4="5.8e+02"

# Continuum column masses
COL_H2OC="1.0e+03"
COL_CO2C="1.0e+06"
COL_CO2_H2="1.0e+4"
COL_H2_H2="90"

# The following continua have not been included due to weak absorption
# CO2-CH4: ~< 0.01 W/m2
# N2-CH4:  ~< 0.01 W/m2
# N2-N2:    = 0.00 W/m2
# N2-H2:   ~< 0.20 W/m2
# H2-CH4:  ~< 0.01 W/m2

# Column masses for all molecules for eliminating weak absorbers
COL_MASS_ELIM_H2O=${COL_MASS_K_H2O}
COL_MASS_ELIM_CO2=${COL_MASS_K_CO2}
COL_MASS_ELIM_CH4=${COL_MASS_K_CH4}

# Column masses for all molecules for sorting absorbers
COL_MASS_STMJ_H2O=${COL_MASS_K_H2O}
COL_MASS_STMJ_CO2=${COL_MASS_K_CO2}
COL_MASS_STMJ_CH4=${COL_MASS_K_CH4}
