#!/bin/bash

NBANDS="15" # Number of bands
SP_ID="dsa_ar10bar" # Spectral file ID
PT_FILE="pt793" # P-T grid

. ../set_paths_lw

################################################################################
# Calculate k-coefficients
################################################################################

echo "Calculating k-coefficients."

# Set paths to files
REF_PT_FILE="../ref_pt"
HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Create skeleton spectral file
SPECFILE="sp_lw_${NBANDS}_${SP_ID}_skel"
rm -f ${SPECFILE}
. mk_sp_lw_${NBANDS}_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_1-3l ] ; then
  echo "CO2 band 1-3"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_1-3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 1 3 -c 50000.0 -i 0.1 -l 2 1.6e3 -t 3.0e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_1-3l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_1-3lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_1-3log \
    && echo "CO2 band 1-3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_4l ] ; then
  echo "CO2 band 4"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 4 4 -c 50000.0 -i 0.1 -l 2 1.6e3 -t 7.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_4l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_4lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_4log \
    && echo "CO2 band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_5l ] ; then
  echo "CO2 band 5"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 5 5 -c 50000.0 -i 0.1 -l 2 1.6e3 -t 3.0e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_5l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_5lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_5log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_6l ] ; then
  echo "CO2 band 6"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 6 6 -c 50000.0 -i 0.1 -l 2 1.6e3 -t 7.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_6l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_6lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_6log \
    && echo "CO2 band 6 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_7l ] ; then
  echo "CO2 band 7"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 7 7 -c 50000.0 -i 0.1 -l 2 1.6e3 -t 3.0e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_7l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_7lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_7log \
    && echo "CO2 band 7 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_8l ] ; then
  echo "CO2 band 8"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 8 8 -c 50000.0 -i 0.1 -l 2 1.6e3 -t 7.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_8l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_8lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_8log \
    && echo "CO2 band 8 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_9-12l ] ; then
  echo "CO2 band 9-12"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_9-12l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 9 12 -c 50000.0 -i 0.1 -l 2 1.6e3 -t 5.0e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_9-12l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_9-12lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_9-12log \
    && echo "CO2 band 9-12 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_13l ] ; then
  echo "CO2 band 13"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_13l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 13 13 -c 50000.0 -i 0.1 -l 2 1.6e3 -t 1.0e-2 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_13l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_13lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_13log \
    && echo "CO2 band 13 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_14-15l ] ; then
  echo "CO2 band 14-15"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_14-15l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 14 15 -c 50000.0 -i 0.1 -l 2 1.6e3 -t 2.0e-2 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_14-15l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_14-15lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_14-15log \
    && echo "CO2 band 14-15 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ch4_l${NBANDS}_1-7l ] ; then
  echo "CH4 band 1-7"
  rm -f ${K_COEFF_DIR}/ch4_l${NBANDS}_1-7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 1 7 -c 2500.0 -i 0.1 -l 6 5.8e2 -t 4.0e-3 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBANDS}_1-7l \
    -m ${K_COEFF_DIR}/ch4_l${NBANDS}_1-7lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBANDS}_1-7log \
    && echo "CH4 band 1-7 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBANDS}_8l ] ; then
  echo "CH4 band 8"
  rm -f ${K_COEFF_DIR}/ch4_l${NBANDS}_8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 8 8 -c 2500.0 -i 0.1 -l 6 5.8e2 -t 7.5e-3 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBANDS}_8l \
    -m ${K_COEFF_DIR}/ch4_l${NBANDS}_8lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBANDS}_8log \
    && echo "CH4 band 8 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBANDS}_9l ] ; then
  echo "CH4 band 9"
  rm -f ${K_COEFF_DIR}/ch4_l${NBANDS}_9l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 9 9 -c 2500.0 -i 0.1 -l 6 5.8e2 -t 7.5e-3 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBANDS}_9l \
    -m ${K_COEFF_DIR}/ch4_l${NBANDS}_9lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBANDS}_9log \
    && echo "CH4 band 9 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBANDS}_10-12l ] ; then
  echo "CH4 band 10-12"
  rm -f ${K_COEFF_DIR}/ch4_l${NBANDS}_10-12l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 10 12 -c 2500.0 -i 0.1 -l 6 5.8e2 -t 7.5e-3 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBANDS}_10-12l \
    -m ${K_COEFF_DIR}/ch4_l${NBANDS}_10-12lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBANDS}_10-12log \
    && echo "CH4 band 9-12 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBANDS}_13-15l ] ; then
  echo "CH4 band 13-15"
  rm -f ${K_COEFF_DIR}/ch4_l${NBANDS}_13-15l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 13 15 -c 2500.0 -i 0.1 -l 6 5.8e2 -t 2.0e-2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBANDS}_13-15l \
    -m ${K_COEFF_DIR}/ch4_l${NBANDS}_13-15lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBANDS}_13-15log \
    && echo "CH4 band 13-15 done" &
fi

if [ ! -s ${K_COEFF_DIR}/n2-ch4_l${NBANDS}_1-${NBANDS}c ] ; then
  echo "N2-CH4 CIA"
  rm -f ${K_COEFF_DIR}/n2-ch4_l${NBANDS}_1-${NBANDS}c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/n2-ch4_2011.cia \
    -R 1 ${NBANDS} -i 1.0 \
    -ct 13 6 4.0e+03 -t 5.0e-3 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2-ch4_l${NBANDS}_1-${NBANDS}c \
    -m ${K_COEFF_DIR}/n2-ch4_l${NBANDS}_1-${NBANDS}cm \
    -L ${ABS_COEFF_DIR}/n2-ch4_lbl_lw.nc \
     > ${K_COEFF_DIR}/n2-ch4_l${NBANDS}_1-${NBANDS}clog \
     && echo "N2-CH4 CIA done" &
fi

if [ ! -s ${K_COEFF_DIR}/n2-n2_l${NBANDS}_1c ] ; then
  echo "N2-N2 CIA band 1"
  rm -f ${K_COEFF_DIR}/n2-n2_l${NBANDS}_1c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/n2-n2_2011_clean.cia \
    -R 1 1 -i 1.0 \
    -ct 13 13 7.0e+05 -t 2.0e-2 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2-n2_l${NBANDS}_1c \
    -m ${K_COEFF_DIR}/n2-n2_l${NBANDS}_1cm \
    -L ${ABS_COEFF_DIR}/n2-n2_lbl_lw.nc \
     > ${K_COEFF_DIR}/n2-n2_l${NBANDS}_1clog \
     && echo "N2-N2 CIA band 1 done" &
fi
if [ ! -s ${K_COEFF_DIR}/n2-n2_l${NBANDS}_2c ] ; then
  echo "N2-N2 CIA band 2"
  rm -f ${K_COEFF_DIR}/n2-n2_l${NBANDS}_2c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/n2-n2_2011_clean.cia \
    -R 2 2 -i 1.0 \
    -ct 13 13 7.0e+05 -t 1.0e-2 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2-n2_l${NBANDS}_2c \
    -m ${K_COEFF_DIR}/n2-n2_l${NBANDS}_2cm \
    -L ${ABS_COEFF_DIR}/n2-n2_lbl_lw.nc \
     > ${K_COEFF_DIR}/n2-n2_l${NBANDS}_2clog \
     && echo "N2-N2 CIA band 2 done" &
fi
if [ ! -s ${K_COEFF_DIR}/n2-n2_l${NBANDS}_3c ] ; then
  echo "N2-N2 CIA band 3"
  rm -f ${K_COEFF_DIR}/n2-n2_l${NBANDS}_3c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/n2-n2_2011_clean.cia \
    -R 3 3 -i 1.0 \
    -ct 13 13 7.0e+05 -t 1.0e-3 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2-n2_l${NBANDS}_3c \
    -m ${K_COEFF_DIR}/n2-n2_l${NBANDS}_3cm \
    -L ${ABS_COEFF_DIR}/n2-n2_lbl_lw.nc \
     > ${K_COEFF_DIR}/n2-n2_l${NBANDS}_3clog \
     && echo "N2-N2 CIA band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/n2-n2_l${NBANDS}_4-${NBANDS}c ] ; then
  echo "N2-N2 CIA band 4-15"
  rm -f ${K_COEFF_DIR}/n2-n2_l${NBANDS}_4-${NBANDS}c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/n2-n2_2011_clean.cia \
    -R 4 ${NBANDS} -i 1.0 \
    -ct 13 13 7.0e+05 -t 2.0e-2 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2-n2_l${NBANDS}_4-${NBANDS}c \
    -m ${K_COEFF_DIR}/n2-n2_l${NBANDS}_4-${NBANDS}cm \
    -L ${ABS_COEFF_DIR}/n2-n2_lbl_lw.nc \
     > ${K_COEFF_DIR}/n2-n2_l${NBANDS}_4-${NBANDS}clog \
     && echo "N2-N2 CIA band 4-15 done" &
fi

if [ ! -s ${K_COEFF_DIR}/n2-h2_l${NBANDS}_1-${NBANDS}c ] ; then
  echo "N2-H2 CIA"
  rm -f ${K_COEFF_DIR}/n2-h2_l${NBANDS}_1-${NBANDS}c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/n2-h2_2011.cia \
    -R 1 ${NBANDS} -i 1.0 \
    -ct 13 23 3.0e+04 -t 5.0e-3 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2-h2_l${NBANDS}_1-${NBANDS}c \
    -m ${K_COEFF_DIR}/n2-h2_l${NBANDS}_1-${NBANDS}cm \
    -L ${ABS_COEFF_DIR}/n2-h2_lbl_lw.nc \
     > ${K_COEFF_DIR}/n2-h2_l${NBANDS}_1-${NBANDS}clog \
     && echo "N2-H2 CIA done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2-co2_l${NBANDS}_1-${NBANDS}c ] ; then
  echo "H2-CO2 CIA"
  rm -f ${K_COEFF_DIR}/h2-co2_l${NBANDS}_1-${NBANDS}c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/h2-co2.cia \
    -R 1 ${NBANDS} -i 1.0 \
    -ct 23 2 1.0e+04 -t 5.0e-3 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/h2-co2_l${NBANDS}_1-${NBANDS}c \
    -m ${K_COEFF_DIR}/h2-co2_l${NBANDS}_1-${NBANDS}cm \
    -L ${ABS_COEFF_DIR}/h2-co2_lbl_lw.nc \
     > ${K_COEFF_DIR}/h2-co2_l${NBANDS}_1-${NBANDS}clog \
     && echo "H2-CO2 CIA done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2-ch4_l${NBANDS}_1-${NBANDS}c ] ; then
  echo "H2-CH4 CIA"
  rm -f ${K_COEFF_DIR}/h2-ch4_l${NBANDS}_1-${NBANDS}c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/h2-ch4_norm_2011.cia \
    -R 1 ${NBANDS} -i 1.0 \
    -ct 23 6 4.0e+03 -t 5.0e-3 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/h2-ch4_l${NBANDS}_1-${NBANDS}c \
    -m ${K_COEFF_DIR}/h2-ch4_l${NBANDS}_1-${NBANDS}cm \
    -L ${ABS_COEFF_DIR}/h2-ch4_lbl_lw.nc \
     > ${K_COEFF_DIR}/h2-ch4_l${NBANDS}_1-${NBANDS}clog \
     && echo "H2-CH4 CIA done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2-h2_l${NBANDS}_1-${NBANDS}c ] ; then
  echo "H2-H2 CIA"
  rm -f ${K_COEFF_DIR}/h2-h2_l${NBANDS}_1-${NBANDS}c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/h2-h2_2011.cia \
    -R 1 ${NBANDS} -i 1.0 \
    -ct 23 23 5.0e+04 -t 5.0e-3 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/h2-h2_l${NBANDS}_1-${NBANDS}c \
    -m ${K_COEFF_DIR}/h2-h2_l${NBANDS}_1-${NBANDS}cm \
    -L ${ABS_COEFF_DIR}/h2-h2_lbl_lw.nc \
     > ${K_COEFF_DIR}/h2-h2_l${NBANDS}_1-${NBANDS}clog \
     && echo "H2-H2 CIA done" &
fi

echo
echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_1l ] ; then
  echo "H2O band 1"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_1l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 1 1 -c 2500.0 -i 0.1 -l 1 1.0e+03 -t 6.0e-3 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_1l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_1lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_1log && echo "H2O band 1 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_2l ] ; then
  echo "H2O band 2"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 2 2 -c 2500.0 -i 0.1 -l 1 1.0e+03 -t 4.0e-3 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_2l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_2lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_2log && echo "H2O band 2 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_3l ] ; then
  echo "H2O band 3"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 3 3 -c 2500.0 -i 0.1 -l 1 1.0e+03 -t 3.0e-3 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_3l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_3lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_3log && echo "H2O band 3 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_4-5l ] ; then
  echo "H2O band 4-5"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_4-5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 4 5 -c 2500.0 -i 0.1 -l 1 1.0e+03 -t 4.0e-3 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_4-5l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_4-5lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_4-5log && echo "H2O band 4-5 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_6l ] ; then
  echo "H2O band 6"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 6 6 -c 2500.0 -i 0.1 -l 1 1.0e+03 -t 3.0e-3 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_6l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_6lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_6log && echo "H2O band 6 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_7l ] ; then
  echo "H2O band 7"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 7 7 -c 2500.0 -i 0.1 -l 1 1.0e+03 -t 1.5e-3 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_7l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_7lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_7log && echo "H2O band 7 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_8l ] ; then
  echo "H2O band 8"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 8 8 -c 2500.0 -i 0.1 -l 1 1.0e+03 -t 4.0e-3 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_8l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_8lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_8log && echo "H2O band 8 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_9-12l ] ; then
  echo "H2O band 9-12"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_9-12l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 9 12 -c 2500.0 -i 0.1 -l 1 1.0e+03 -t 1.0e-2 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_9-12l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_9-12lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_9-12log && echo "H2O band 9-12 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_13l ] ; then
  echo "H2O band 13"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_13l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 13 13 -c 2500.0 -i 0.1 -l 1 1.0e+03 -t 2.0e-2 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_13l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_13lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_13log && echo "H2O band 13 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_14-15l ] ; then
  echo "H2O band 14-15"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_14-15l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 14 15 -c 2500.0 -i 0.1 -l 1 1.0e+03 -n 5 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_14-15l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_14-15lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_14-15log && echo "H2O band 14-15 done"
fi

if [ ! -s ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-${NBANDS}c ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-${NBANDS}c*
  Ccorr_k -F ../pt_cont \
    -R 1 ${NBANDS} -c 2500.0 -i 0.1 \
    -ct 1 1 100.0 -t 1.0e-3 \
    -e ${RAD_DATA}/continua/caviar_s296 ${RAD_DATA}/continua/caviar_s260 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-${NBANDS}c \
    -m ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-${NBANDS}cm \
    -L ${ABS_COEFF_DIR}/h2o-h2o_lbl_lw.nc \
    -lw ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
     > ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-${NBANDS}clog \
     && echo "H2O self-broadened continuum done"
fi

wait
echo "Calculation of k-coefficients completed."

################################################################################
# Calculate optical properties
################################################################################

echo "Calculating cloud optical properties."

mkdir -p ${CLD_COEFF_DIR}

if [ ! -s ${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS} ] ; then
  rm -f ${CLD_COEFF_DIR}/mon_lw_drop5_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -t -p 250 \
    -f 5 ${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_lw_drop5_${NBANDS} 1.e3 \
    ${RAD_DATA}/cloud/scatter_drop_type5
fi
if [ ! -s ${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS} ] ; then
  rm -f ${CLD_COEFF_DIR}/mon_lw_ice8_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -w -p 250 \
    -f 12 ${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_lw_ice8_${NBANDS} 920 \
    ${RAD_DATA}/cloud/scatter_ice_lw_type8
fi

echo "Calculation of cloud optical properties completed."

################################################################################
# Create spectral file
################################################################################

echo "Creating spectral file."

# Create name of spectral file
SPEC_FILE="sp_lw_${NBANDS}_${SP_ID}"

mkdir -p ${SPEC_FILE_DIR}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}_k

# Construct spectral file

prep_spec << EOF > mk_sp_lw_${NBANDS}_${SP_ID}_out
sp_lw_${NBANDS}_${SP_ID}_skel
n
${SPEC_FILE_DIR}/${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_l${NBANDS}_1l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_2l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_3l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_4-5l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_6l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_7l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_8l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_9-12l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_13l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_14-15l
19
${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-${NBANDS}c
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_1-3l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_4l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_5l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_6l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_7l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_8l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_9-12l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_13l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_14-15l
5
y
${K_COEFF_DIR}/ch4_l${NBANDS}_1-7l
5
y
${K_COEFF_DIR}/ch4_l${NBANDS}_8l
5
y
${K_COEFF_DIR}/ch4_l${NBANDS}_9l
5
y
${K_COEFF_DIR}/ch4_l${NBANDS}_10-12l
5
y
${K_COEFF_DIR}/ch4_l${NBANDS}_13-15l
19
y
${K_COEFF_DIR}/n2-ch4_l${NBANDS}_1-${NBANDS}c
19
y
${K_COEFF_DIR}/n2-n2_l${NBANDS}_1c
19
y
${K_COEFF_DIR}/n2-n2_l${NBANDS}_2c
19
y
${K_COEFF_DIR}/n2-n2_l${NBANDS}_3c
19
y
${K_COEFF_DIR}/n2-n2_l${NBANDS}_4-${NBANDS}c
19
y
${K_COEFF_DIR}/n2-h2_l${NBANDS}_1-${NBANDS}c
19
y
${K_COEFF_DIR}/h2-co2_l${NBANDS}_1-${NBANDS}c
19
y
${K_COEFF_DIR}/h2-ch4_l${NBANDS}_1-${NBANDS}c
19
y
${K_COEFF_DIR}/h2-h2_l${NBANDS}_1-${NBANDS}c
6
n
t
1 500
500
-1
EOF

# Add ice cloud optical properties only
prep_spec << EOF >> mk_sp_lw_${NBANDS}_${SP_ID}_out
${SPEC_FILE_DIR}/${SPEC_FILE}
a
10
5
${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS}
1.50000E-06 5.00000E-05
12
8
${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS}
8.00000E-06 3.20000E-04
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
tidy_90 << EOF >> mk_sp_lw_${NBANDS}_${SP_ID}_out
${SPEC_FILE_DIR}/${SPEC_FILE}
o
8
1
0
0
0
0
0
0
1
2.5e2
1.6e3
5.8e2
0.0
0.0
100.0
4.0e+03
7.0e+05
3.0e+04
1.0e+04
4.0e+03
5.0e+04
0.99990
6
2.5e2
1.6e3
5.8e2
0.0
0.0
100.0
4.0e+03
7.0e+05
3.0e+04
1.0e+04
4.0e+03
5.0e+04
1.0e+06
n
-1
EOF

echo "Spectral file ${SPEC_FILE} created. All done."
echo "Please check mk_sp_lw_${NBANDS}_${SP_ID}_out for errors."

exit 0

