#!/bin/bash

SP_ID="dsa_arcc"
SP_FLDR="dsa_arcc"
NBAND="35"
SOLAR_SPEC="pc"
PT_FILE="pt663"

# Paths
. set_paths

# Create full path to spectral file
SPEC_FILE="${SPEC_FILE_DIR}/sp_sw_${NBAND}_${SP_ID}_${SOLAR_SPEC}"

# Remove old version
rm -f ${SPEC_FILE}
rm -f ${SPEC_FILE}_k

# Replace old k-coefficients by new k-coefficients in spectral file
prep_spec << EOF
sp_sw_${NBAND}_${SP_ID}_skel
n
${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_s${NBAND}_2l
5
y
${K_COEFF_DIR}/h2o_s${NBAND}_3l
5
y
${K_COEFF_DIR}/h2o_s${NBAND}_4l
5
y
${K_COEFF_DIR}/h2o_s${NBAND}_5l
5
y
${K_COEFF_DIR}/h2o_s${NBAND}_6l
19
${K_COEFF_DIR}/h2o-h2o_s${NBAND}_3-6c
5
y
${K_COEFF_DIR}/co2_s${NBAND}_4l
5
y
${K_COEFF_DIR}/co2_s${NBAND}_5l
5
y
${K_COEFF_DIR}/co2_s${NBAND}_6l
19
y
${K_COEFF_DIR}/co2-co2_s${NBAND}_6c
5
y
${K_COEFF_DIR}/ch4_s${NBAND}_4l
5
y
${K_COEFF_DIR}/ch4_s${NBAND}_5l
5
y
${K_COEFF_DIR}/ch4_s${NBAND}_6l
-1
EOF

# Add cloud fits to spectral file
prep_spec << EOF
${SPEC_FILE}
a
10
5
${CLD_COEFF_DIR}/fit_sw_drop5_${NBAND}
1.70000E-06 5.00000E-05
12
8
${CLD_COEFF_DIR}/fit_sw_ice8_${NBAND}
8.00000E-06 3.20000E-04
-1
EOF

# Add solar spectrum and Rayleigh scattering coefficients
prep_spec << EOF
${SPEC_FILE}
a
2
n
${SOLAR_SPEC_DIR}/${SOLAR_SPEC}
y
3
c
a
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
tidy_90 << EOF
${SPEC_FILE}
o
1
2.5e1
1.6e3
5.8e1
0.0
0.0
10.0
1.0e2
0.999990
6
2.5e1
1.6e3
5.8e1
0.0
0.0
10.0
1.0e2
n
-1
EOF