#!/bin/bash

SP_ID="dsa_arcc"
SP_FLDR="dsa_arcc"
NBANDS="35"
SOLAR_SPEC="sun"
PT_FILE="pt663"

. ../set_paths_sw

################################################################################
# Calculate k-coefficients
################################################################################

echo "Calculating k-coefficients."

# Set paths to files
HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

ref_pt_file="$RAD_DATA/gases/ref_pt"

# Create skeleton spectral file
specfile="sp_sw_35_${SP_ID}_skel"
rm -f $specfile
. mk_sp_sw_35_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

# Construct weight argument
WGT="+S ${SOLAR_SPEC_DIR}/${SOLAR_SPEC}"

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_4l ] ; then
  echo "CO2 band 4"
  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 4 9 -c 50000.0 -i 1.0 -l 2 1.6e3 -t 4.0e-3  \
    -sb gas_fractions -lp 2 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBANDS}_4l -m ${K_COEFF_DIR}/co2_s${NBANDS}_4lm \
    -L $SW_DATA/co2_sblbl_sw_${PT_FILE}_gf0.0-0.1.nc > \
    ${K_COEFF_DIR}/co2_s${NBANDS}_4log \
    && echo "CO2 band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_5l ] ; then
  echo "CO2 band 5"
  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 10 24 -c 50000.0 -i 1.0 -l 2 1.6e3 -t 3.0e-3  \
    -sb gas_fractions -lp 2 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBANDS}_5l -m ${K_COEFF_DIR}/co2_s${NBANDS}_5lm \
    -L $SW_DATA/co2_sblbl_sw_${PT_FILE}_gf0.0-0.1.nc > \
    ${K_COEFF_DIR}/co2_s${NBANDS}_5log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_6l ] ; then
  echo "CO2 band 6"
  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 25 35 -c 50000.0 -i 1.0 -l 2 1.6e3 -t 6.0e-3  \
    -sb gas_fractions -lp 2 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_s${NBANDS}_6l -m ${K_COEFF_DIR}/co2_s${NBANDS}_6lm \
    -L $SW_DATA/co2_sblbl_sw_${PT_FILE}_gf0.0-0.1.nc > \
    ${K_COEFF_DIR}/co2_s${NBANDS}_6log \
    && echo "CO2 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ch4_s${NBANDS}_4l ] ; then
  echo "CH4 band 4"
  rm -f ${K_COEFF_DIR}/ch4_s${NBANDS}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 4 9 -c 2500.0 -i 1.0 -l 6 5.8e1 -t 4.0e-3  \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_s${NBANDS}_4l -m ${K_COEFF_DIR}/ch4_s${NBANDS}_4lm \
    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/ch4_s${NBANDS}_4log \
    && echo "CH4 band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_s${NBANDS}_5l ] ; then
  echo "CH4 band 5"
  rm -f ${K_COEFF_DIR}/ch4_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 10 24 -c 2500.0 -i 1.0 -l 6 5.8e1 -t 3.0e-3  \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_s${NBANDS}_5l -m ${K_COEFF_DIR}/ch4_s${NBANDS}_5lm \
    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/ch4_s${NBANDS}_5log \
    && echo "CH4 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_s${NBANDS}_6l ] ; then
  echo "CH4 band 6"
  rm -f ${K_COEFF_DIR}/ch4_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 25 35 -c 2500.0 -i 1.0 -l 6 5.8e1 -t 6.0e-3  \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_s${NBANDS}_6l -m ${K_COEFF_DIR}/ch4_s${NBANDS}_6lm \
    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/ch4_s${NBANDS}_6log \
    && echo "CH4 band 6 done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_2l ] || \
    [ ! -s $SW_DATA/h2o_lbl_vis_${PT_FILE}.nc ] ; then
  echo "H2O lines band 2"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 2 2 -c 2500.0 -i 1.0 -l 1 1.0e2 -n 1 \
    -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_2l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_2lm \
    -L $SW_DATA/h2o_lbl_vis_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/h2o_s${NBANDS}_2log && echo "H2O lines band 2 done" &
fi

echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_3l ] ; then
  echo "H2O lines band 3"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 3 3 -c 2500.0 -i 1.0 -l 1 1.0e2 -n 2  \
    -s $specfile ${WGT} -lk \
    -k -x ${CONT_DIR}/mt_ckd_v3.0_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_3l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_3lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_3log \
    && echo "H2O lines band 3 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_4l ] ; then
  echo "H2O lines band 4"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 4 9 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 3.0e-3  \
    -s $specfile ${WGT} -lk \
    -k -x ${CONT_DIR}/mt_ckd_v3.0_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_4l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_4lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_4log \
    && echo "H2O lines band 4 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_5l ] ; then
  echo "H2O lines band 5"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 10 24 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 4.0e-3  \
    -s $specfile ${WGT} -lk \
    -k -x ${CONT_DIR}/mt_ckd_v3.0_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_5l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_5lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_5log \
    && echo "H2O lines band 5 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_6l ] ; then
  echo "H2O lines band 6"
  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 25 35 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 6.0e-3  \
    -s $specfile ${WGT} -lk \
    -k -x ${CONT_DIR}/mt_ckd_v3.0_frn \
    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_6l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_6lm \
    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_s${NBANDS}_6log \
    && echo "H2O lines band 6 done"
fi

if [ ! -s ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c*
  Ccorr_k -F ../pt_cont \
    -R 3 35 -i 1.0 -ct 1 1 10.0 -t 1.0e-3 \
    -e ${CONT_DIR}/mt_ckd_v3.0_s296 ${CONT_DIR}/mt_ckd_v3.0_s260 \
    -k -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c \
    -m ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6cm \
    -L $SW_DATA/h2o-h2o_lbl_sw.nc \
    -lw ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6clog \
    && echo "H2O self-broadened continuum done"
fi

if [ ! -s ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6c ] ; then
  echo "CO2-CO2 CIA"
  rm -f ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/co2-co2.cia \
    -R 25 35 -i 1.0 \
    -ct 2 2 1.0e2 -t 1.0e-2 \
    -k -s $specfile ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6c \
    -m ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6cm \
    -L $SW_DATA/co2-co2_lbl_sw.nc \
    > ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6clog \
    && echo "CO2-CO2 CIA done"
fi

wait
echo "Calculation of k-coefficients completed."

################################################################################
# Calculate optical properties
################################################################################

echo "Calculating cloud optical properties."

WGT_SCTAVG="-${WGT:1}"

mkdir -p ${CLD_COEFF_DIR}

if [ ! -s ${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS} ] ; then
  echo 'Type 5 droplets'
  rm -f ${CLD_COEFF_DIR}/mon_sw_drop5_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -t ${WGT_SCTAVG} \
    -f 5 ${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_sw_drop5_${NBANDS} 1.e3 \
    ${RAD_DATA}/cloud/scatter_drop_type5
fi
if [ ! -s ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS} ] ; then
  echo 'Type 8 ice'
  rm -f ${CLD_COEFF_DIR}/mon_sw_ice8_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -w ${WGT_SCTAVG} \
    -f 12 ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_sw_ice8_${NBANDS} 920 \
    ${RAD_DATA}/cloud/scatter_ice_sw_type8
fi

echo "Calculation of cloud optical properties completed."

################################################################################
# Create spectral file
################################################################################

echo "Creating spectral file."

# Create full path to spectral file
SPEC_FILE="${SPEC_FILE_DIR}/sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}"

mkdir -p ${SPEC_FILE_DIR}
rm -f ${SPEC_FILE}
rm -f ${SPEC_FILE}_k

# Replace old k-coefficients by new k-coefficients in spectral file
prep_spec << EOF > mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
sp_sw_${NBANDS}_${SP_ID}_skel
n
${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_s${NBANDS}_2l
5
y
${K_COEFF_DIR}/h2o_s${NBANDS}_3l
5
y
${K_COEFF_DIR}/h2o_s${NBANDS}_4l
5
y
${K_COEFF_DIR}/h2o_s${NBANDS}_5l
5
y
${K_COEFF_DIR}/h2o_s${NBANDS}_6l
19
${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c
5
y
${K_COEFF_DIR}/co2_s${NBANDS}_4l
5
y
${K_COEFF_DIR}/co2_s${NBANDS}_5l
5
y
${K_COEFF_DIR}/co2_s${NBANDS}_6l
19
y
${K_COEFF_DIR}/co2-co2_s${NBANDS}_6c
5
y
${K_COEFF_DIR}/ch4_s${NBANDS}_4l
5
y
${K_COEFF_DIR}/ch4_s${NBANDS}_5l
5
y
${K_COEFF_DIR}/ch4_s${NBANDS}_6l
-1
EOF

# Add cloud fits to spectral file
prep_spec << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
${SPEC_FILE}
a
10
5
${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS}
1.70000E-06 5.00000E-05
12
8
${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS}
8.00000E-06 3.20000E-04
-1
EOF

# Add solar spectrum and Rayleigh scattering coefficients
prep_spec << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
${SPEC_FILE}
a
2
n
${SOLAR_SPEC_DIR}/${SOLAR_SPEC}
y
3
c
a
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
tidy_90 << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
${SPEC_FILE}
o
8
1
0
1
2.5e1
1.6e3
5.8e1
0.0
0.0
10.0
1.0e2
0.999990
6
2.5e1
1.6e3
5.8e1
0.0
0.0
10.0
1.0e2
1.0e+5
n
-1
EOF

. ../set_permissions

echo "Spectral file sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC} created. All done."
echo "Please check mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out for errors."

exit 0
