#!/bin/bash

# This script creates the k-coefficients.

NBANDS="350" # Number of bands
SP_ID="dsa_ar" # Spectral file ID
LBL_RES="0.1" # Resolution in LbL files
TOL="-b 1.0e-3" # Tolerance for k-coefficients
PT_FILE="pt663" # P-T grid
REF_PT_FILE="../ref_pt" # Reference P-T for continuum

. ../set_paths_lw

HITRAN_H2O="${HITRAN_DIR}/01_hit12.par"
COL_H2O="1.0e+02"

HITRAN_CO2="${HITRAN_DIR}/02_hit12.par"
COL_CO2="1.6e+02" # 1% CO2 in a 1 bar atmosphere

HITRAN_CH4="${HITRAN_DIR}/06_hit12.par"
COL_CH4="5.8e+01" # 1% CH4 in a 1 bar atmosphere

# Water vapour continuum uses CAVIAR data contained within the
# suite (${RAD_DATA}/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script takes a very long time to run initially (probably
# several days if not done in parallel). However once the
# line-by-line netCDF files have been created, subsequent runs will
# use these files and the whole script should run in around an hour.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Create skeleton spectral file
SPECFILE="sp_lw_${NBANDS}_${SP_ID}_skel"
rm -f ${SPECFILE}
. mk_sp_lw_${NBANDS}_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

# Gases

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_l ] || \
    [ ! -s ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc ] ; then
  echo "CO2"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D ${HITRAN_CO2} \
    -R 1 ${NBANDS} -c 2500.0 -i ${LBL_RES} -l 2 ${COL_CO2} \
    ${TOL} -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_l -m ${K_COEFF_DIR}/co2_l${NBANDS}_lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/co2_l${NBANDS}_log && echo "CO2 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ch4_l${NBANDS}_l ] || \
    [ ! -s ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc ] ; then
  echo "CH4"
  rm -f ${K_COEFF_DIR}/ch4_l${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D ${HITRAN_CH4} \
    -R 1 ${NBANDS} -c 2500.0 -i ${LBL_RES} -l 6 ${COL_CH4} \
    ${TOL} -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBANDS}_l -m ${K_COEFF_DIR}/ch4_l${NBANDS}_lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/ch4_l${NBANDS}_log && echo "CH4 done" &
fi

echo
echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_l ] || \
    [ ! -s ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc ] ; then
  echo "H2O lines and foreign continuum"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_l*
  Ccorr_k -F ../${PT_FILE} -D ${HITRAN_H2O} \
    -R 1 ${NBANDS} -c 2500.0 -i ${LBL_RES} -l 1 ${COL_H2O} \
    ${TOL} -s ${SPECFILE} +p -lk \
    -k -x ${RAD_DATA}/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_l -m ${K_COEFF_DIR}/h2o_l${NBANDS}_lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/h2o_l${NBANDS}_log \
     && echo "H2O lines and foreign continuum done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_s ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_s*
  Ccorr_k -C 17 2.5e-1 2.5e2 -F ../${PT_FILE} -D ${HITRAN_H2O} \
    -P 7 -R 1 ${NBANDS} -c 2500.0 -i ${LBL_RES} \
    -e ${RAD_DATA}/continua/caviar_s296 ${RAD_DATA}/continua/caviar_s260 \
    -k -s ${SPECFILE} +p -q -r ${REF_PT_FILE} \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_s -m ${K_COEFF_DIR}/h2o_l${NBANDS}_sm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
     > ${K_COEFF_DIR}/h2o_l${NBANDS}_slog \
     && echo "H2O self-broadened continuum done"
fi

wait

echo "All done"
