#!/bin/bash

# This script creates the k-coefficients.

SP_ID="dsa_ar"
NBAND="12"
PT_FILE="pt663"
REF_PT_FILE="../ref_pt"
WGT="+p"

. ../set_paths_lw

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"

# Water vapour continuum uses CAVIAR data contained within the
# suite ($RAD_DATA/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script should be run after the LbL files have been created
# by running the script for the 350 band file.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Create skeleton spectral file
SPECFILE="sp_lw_${NBAND}_${SP_ID}_skel"
rm -f ${SPECFILE}
. mk_sp_lw_${NBAND}_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

# Gases

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_1l ] ; then
  echo "CO2 band 1"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_1l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 1 1 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 1 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_1l -m ${K_COEFF_DIR}/co2_l${NBAND}_1lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_1log \
    && echo "CO2 band 1 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_2l ] ; then
  echo "CO2 band 2"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 2 2 -c 2500.0 -i 0.1 -l 2 1.6e2 -b 1.5e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_2l -m ${K_COEFF_DIR}/co2_l${NBAND}_2lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_2log \
    && echo "CO2 band 2 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_3l ] ; then
  echo "CO2 band 3"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 3 3 -c 2500.0 -i 0.1 -l 2 1.6e2 -b 2.5e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_3l -m ${K_COEFF_DIR}/co2_l${NBAND}_3lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_3log \
    && echo "CO2 band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_4l ] ; then
  echo "CO2 band 4"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 4 4 -c 2500.0 -i 0.05 -l 2 1.6e3 -b 1.5e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_4l -m ${K_COEFF_DIR}/co2_l${NBAND}_4lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_4log \
    && echo "CO2 band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_5l ] ; then
  echo "CO2 band 5"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 5 5 -c 2500.0 -i 0.1 -l 2 1.6e2 -b 1.5e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_5l -m ${K_COEFF_DIR}/co2_l${NBAND}_5lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_5log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_6l ] ; then
  echo "CO2 band 6"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 6 6 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 10 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_6l -m ${K_COEFF_DIR}/co2_l${NBAND}_6lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_6log \
    && echo "CO2 band 6 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_7l ] ; then
  echo "CO2 band 7"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 7 7 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 1 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_7l -m ${K_COEFF_DIR}/co2_l${NBAND}_7lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_7log \
    && echo "CO2 band 7 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_8-10l ] ; then
  echo "CO2 band 8-10"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_8-10l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 8 10 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 5 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_8-10l -m ${K_COEFF_DIR}/co2_l${NBAND}_8-10lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_8-10log \
    && echo "CO2 band 8-10 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_11l ] ; then
  echo "CO2 band 11"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_11l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 11 11 -c 2500.0 -i 0.1 -l 2 1.6e3 -n 10 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_11l -m ${K_COEFF_DIR}/co2_l${NBAND}_11lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_11log \
    && echo "CO2 band 11 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_12l ] ; then
  echo "CO2 band 12"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_12l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 12 12 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 1 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_12l -m ${K_COEFF_DIR}/co2_l${NBAND}_12lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_12log \
    && echo "CO2 band 12 done" &
fi


if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_1-5l ] ; then
  echo "CH4 band 1-5"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_1-5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 1 5 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 1 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_1-5l -m ${K_COEFF_DIR}/ch4_l${NBAND}_1-5lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_1-5log \
    && echo "CH4 band 1-5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_6l ] ; then
  echo "CH4 band 6"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 6 6 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 5 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_6l -m ${K_COEFF_DIR}/ch4_l${NBAND}_6lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_6log \
    && echo "CH4 band 6 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_7-10l ] ; then
  echo "CH4 band 7-10"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_7-10l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 7 10 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 8 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_7-10l -m ${K_COEFF_DIR}/ch4_l${NBAND}_7-10lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_7-10log \
    && echo "CH4 band 7-10 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_11-12l ] ; then
  echo "CH4 band 11-12"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_11-12l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 11 12 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 5 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_11-12l -m ${K_COEFF_DIR}/ch4_l${NBAND}_11-12lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_11-12log \
    && echo "CH4 band 11-12 done" &
fi

echo
echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_1l ] ; then
  echo "H2O band 1"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_1l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 1 1 -c 2500.0 -i 0.1 -l 1 2.5e2 -b 1.5e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_1l -m ${K_COEFF_DIR}/h2o_l${NBAND}_1lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_1-12map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_1log && echo "H2O band 1 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_2l ] ; then
  echo "H2O band 2"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 2 2 -c 2500.0 -i 0.1 -l 1 2.5e2 -n 18 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_2l -m ${K_COEFF_DIR}/h2o_l${NBAND}_2lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_1-12map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_2log && echo "H2O band 2 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_3l ] ; then
  echo "H2O band 3"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 3 3 -c 2500.0 -i 0.1 -l 1 2.5e1 -n 8 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_3l -m ${K_COEFF_DIR}/h2o_l${NBAND}_3lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_1-12map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_3log && echo "H2O band 3 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_4l ] ; then
  echo "H2O band 4"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 4 4 -c 2500.0 -i 0.1 -l 1 0.5e2 -n 12 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_4l -m ${K_COEFF_DIR}/h2o_l${NBAND}_4lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_1-12map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_4log && echo "H2O band 4 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_5l ] ; then
  echo "H2O band 5"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 5 5 -c 2500.0 -i 0.1 -l 1 0.5e2 -n 7 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_5l -m ${K_COEFF_DIR}/h2o_l${NBAND}_5lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_1-12map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_5log && echo "H2O band 5 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_6l ] ; then
  echo "H2O band 6"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 6 6 -c 2500.0 -i 0.1 -l 1 0.5e1 -n 5 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_6l -m ${K_COEFF_DIR}/h2o_l${NBAND}_6lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_1-12map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_6log && echo "H2O band 6 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_7l ] ; then
  echo "H2O band 7"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 7 7 -c 2500.0 -i 0.1 -l 1 0.5e2 -n 7 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_7l -m ${K_COEFF_DIR}/h2o_l${NBAND}_7lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_1-12map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_7log && echo "H2O band 7 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_8l ] ; then
  echo "H2O band 8"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 8 8 -c 2500.0 -i 0.1 -l 1 0.5e2 -n 10 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_8l -m ${K_COEFF_DIR}/h2o_l${NBAND}_8lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_1-12map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_8log && echo "H2O band 8 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_9-10l ] ; then
  echo "H2O band 9-10"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_9-10l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 9 10 -c 2500.0 -i 0.1 -l 1 0.5e2 -n 10 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_9-10l -m ${K_COEFF_DIR}/h2o_l${NBAND}_9-10lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_1-12map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_9-10log && echo "H2O band 9-10 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_11-12l ] ; then
  echo "H2O band 11-12"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_11-12l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 11 12 -c 2500.0 -i 0.1 -l 1 0.5e2 -n 5 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_11-12l -m ${K_COEFF_DIR}/h2o_l${NBAND}_11-12lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_1-12map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_11-12log && echo "H2O band 11-12 done"
fi

if [ ! -s ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_1-12c ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_1-12c*
  Ccorr_k -F ../pt_cont \
    -R 1 ${NBAND} -c 2500.0 -i 0.1 \
    -ct 1 1 10.0 -t 1.0e-3 \
    -e ${RAD_DATA}/continua/caviar_s296 ${RAD_DATA}/continua/caviar_s260 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_1-12c \
    -m ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_1-12cm \
    -L ${ABS_COEFF_DIR}/h2o-h2o_lbl_lw.nc \
    -lw ${K_COEFF_DIR}/h2o_l${NBAND}_1-12map.nc \
     > ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_1-12clog \
     && echo "H2O self-broadened continuum done"
fi

wait

echo "All done"

exit 0
