#!/bin/bash

# This script creates the k-coefficients.

SP_ID="dsa_ar"
NBAND="12"
PT_FILE="pt663"
REF_PT_FILE="../ref_pt"
WGT="+p"

HITRAN_DIR="/home/damundse/Line_lists/HITRAN"
ABS_COEFF_DIR="/home/damundse/Abs_coeff"
K_COEFF_DIR="/home/damundse/k-coeff/lw_${SP_ID}/${PT_FILE}"

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"

# Water vapour continuum uses CAVIAR data contained within the
# suite ($RAD_DATA/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script should be run after the LbL files have been created
# by running the script for the 350 band file.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Create skeleton spectral file
SPECFILE="sp_lw_${NBAND}_${SP_ID}_skel"
rm -f ${SPECFILE}
. mk_sp_lw_${NBAND}_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

# Gases

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_1l ] ; then
  echo "CO2 band 1"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_1l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 1 1 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 1  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_1l -m ${K_COEFF_DIR}/co2_l${NBAND}_1lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_1log \
    && echo "CO2 band 1 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_2l ] ; then
  echo "CO2 band 2"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 2 2 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_2l -m ${K_COEFF_DIR}/co2_l${NBAND}_2lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_2log \
    && echo "CO2 band 2 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_3l ] ; then
  echo "CO2 band 3"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 3 3 -c 2500.0 -i 0.1 -l 2 1.6e2 -b 2.5e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_3l -m ${K_COEFF_DIR}/co2_l${NBAND}_3lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_3log \
    && echo "CO2 band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_4l ] ; then
  echo "CO2 band 4"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 4 4 -c 2500.0 -i 0.05 -l 2 1.6e2 -b 1.5e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_4l -m ${K_COEFF_DIR}/co2_l${NBAND}_4lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_4log \
    && echo "CO2 band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_5l ] ; then
  echo "CO2 band 5"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 5 5 -c 2500.0 -i 0.1 -l 2 1.6e2 -b 1.5e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_5l -m ${K_COEFF_DIR}/co2_l${NBAND}_5lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_5log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_6l ] ; then
  echo "CO2 band 6"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 6 6 -c 2500.0 -i 0.1 -l 2 1.6e2 -b 2.5e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_6l -m ${K_COEFF_DIR}/co2_l${NBAND}_6lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_6log \
    && echo "CO2 band 6 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_7l ] ; then
  echo "CO2 band 7"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 7 7 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 1  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_7l -m ${K_COEFF_DIR}/co2_l${NBAND}_7lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_7log \
    && echo "CO2 band 7 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_8l ] ; then
  echo "CO2 band 8"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 8 8 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_8l -m ${K_COEFF_DIR}/co2_l${NBAND}_8lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_8log \
    && echo "CO2 band 8 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_9l ] ; then
  echo "CO2 band 9"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_9l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 9 9 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_9l -m ${K_COEFF_DIR}/co2_l${NBAND}_9lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_9log \
    && echo "CO2 band 9 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_10l ] ; then
  echo "CO2 band 10"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_10l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 10 10 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_10l -m ${K_COEFF_DIR}/co2_l${NBAND}_10lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_10log \
    && echo "CO2 band 10 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_11l ] ; then
  echo "CO2 band 11"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_11l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 11 11 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_11l -m ${K_COEFF_DIR}/co2_l${NBAND}_11lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_11log \
    && echo "CO2 band 11 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_12l ] ; then
  echo "CO2 band 12"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_12l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 12 12 -c 2500.0 -i 0.1 -l 2 1.6e2 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_12l -m ${K_COEFF_DIR}/co2_l${NBAND}_12lm \
    -L ${ABS_COEFF_DIR}/co2_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_12log \
    && echo "CO2 band 12 done" &
fi


if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_1l ] ; then
  echo "CH4 band 1"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_1l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 1 1 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 1 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_1l -m ${K_COEFF_DIR}/ch4_l${NBAND}_1lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_1log \
    && echo "CH4 band 1 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_2l ] ; then
  echo "CH4 band 2"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 2 2 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 1 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_2l -m ${K_COEFF_DIR}/ch4_l${NBAND}_2lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_2log \
    && echo "CH4 band 2 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_3l ] ; then
  echo "CH4 band 3"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 3 3 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 1 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_3l -m ${K_COEFF_DIR}/ch4_l${NBAND}_3lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_3log \
    && echo "CH4 band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_4l ] ; then
  echo "CH4 band 4"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 4 4 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 1 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_4l -m ${K_COEFF_DIR}/ch4_l${NBAND}_4lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_4log \
    && echo "CH4 band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_5l ] ; then
  echo "CH4 band 5"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 5 5 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 1 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_5l -m ${K_COEFF_DIR}/ch4_l${NBAND}_5lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_5log \
    && echo "CH4 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_6l ] ; then
  echo "CH4 band 6"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 6 6 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 8 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_6l -m ${K_COEFF_DIR}/ch4_l${NBAND}_6lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_6log \
    && echo "CH4 band 6 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_7l ] ; then
  echo "CH4 band 7"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 7 7 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 8 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_7l -m ${K_COEFF_DIR}/ch4_l${NBAND}_7lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_7log \
    && echo "CH4 band 7 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_8l ] ; then
  echo "CH4 band 8"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 8 8 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 8  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_8l -m ${K_COEFF_DIR}/ch4_l${NBAND}_8lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_8log \
    && echo "CH4 band 8 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_9l ] ; then
  echo "CH4 band 9"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_9l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 9 9 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 8  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_9l -m ${K_COEFF_DIR}/ch4_l${NBAND}_9lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_9log \
    && echo "CH4 band 9 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_10l ] ; then
  echo "CH4 band 10"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_10l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 10 10 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_10l -m ${K_COEFF_DIR}/ch4_l${NBAND}_10lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_10log \
    && echo "CH4 band 10 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_11l ] ; then
  echo "CH4 band 11"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_11l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 11 11 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_11l -m ${K_COEFF_DIR}/ch4_l${NBAND}_11lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_11log \
    && echo "CH4 band 11 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_12l ] ; then
  echo "CH4 band 12"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_12l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 12 12 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_12l -m ${K_COEFF_DIR}/ch4_l${NBAND}_12lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_12log \
    && echo "CH4 band 12 done" &
fi


if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_1l ] ; then
  echo "H2O band 1"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_1l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 1 1 -c 2500.0 -i 0.1 -l 1 1.0e2 -b 2.2e-3  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_1l -m ${K_COEFF_DIR}/h2o_l${NBAND}_1lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_1log && echo "H2O band 1 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_2l ] ; then
  echo "H2O band 2"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 2 2 -c 2500.0 -i 0.1 -l 1 2.5e1 -n 14  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_2l -m ${K_COEFF_DIR}/h2o_l${NBAND}_2lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_2log && echo "H2O band 2 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_3l ] ; then
  echo "H2O band 3"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_3l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 3 3 -c 2500.0 -i 0.1 -l 1 2.5e1 -n 5 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_3l -m ${K_COEFF_DIR}/h2o_l${NBAND}_3lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_3log && echo "H2O band 3 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_4l ] ; then
  echo "H2O band 4"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 4 4 -c 2500.0 -i 0.1 -l 1 0.5e1 -n 4  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_4l -m ${K_COEFF_DIR}/h2o_l${NBAND}_4lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_4log && echo "H2O band 4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_5l ] ; then
  echo "H2O band 5"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 5 5 -c 2500.0 -i 0.1 -l 1 0.5e1 -n 6  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_5l -m ${K_COEFF_DIR}/h2o_l${NBAND}_5lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_5log && echo "H2O band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_6l ] ; then
  echo "H2O band 6"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 6 6 -c 2500.0 -i 0.1 -l 1 0.5e1 -n 3  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_6l -m ${K_COEFF_DIR}/h2o_l${NBAND}_6lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_6log && echo "H2O band 6 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_7l ] ; then
  echo "H2O band 7"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 7 7 -c 2500.0 -i 0.1 -l 1 0.5e1 -n 6  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_7l -m ${K_COEFF_DIR}/h2o_l${NBAND}_7lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_7log && echo "H2O band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_8l ] ; then
  echo "H2O band 8"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 8 8 -c 2500.0 -i 0.1 -l 1 0.5e1 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_8l -m ${K_COEFF_DIR}/h2o_l${NBAND}_8lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_8log && echo "H2O band 8 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_9l ] ; then
  echo "H2O band 9"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_9l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 9 9 -c 2500.0 -i 0.1 -l 1 1.0e2 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_9l -m ${K_COEFF_DIR}/h2o_l${NBAND}_9lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_9log && echo "H2O band 9 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_10l ] ; then
  echo "H2O band 10"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_10l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 10 10 -c 2500.0 -i 0.1 -l 1 1.0e2 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_10l -m ${K_COEFF_DIR}/h2o_l${NBAND}_10lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_10log && echo "H2O band 10 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_11l ] ; then
  echo "H2O band 11"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_11l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 11 11 -c 2500.0 -i 0.1 -l 1 1.0e2 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_11l -m ${K_COEFF_DIR}/h2o_l${NBAND}_11lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_11log && echo "H2O band 11 done" &
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_12l ] ; then
  echo "H2O band 12"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_12l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 12 12 -c 2500.0 -i 0.1 -l 1 1.0e2 -n 5  \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_12l -m ${K_COEFF_DIR}/h2o_l${NBAND}_12lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_12log && echo "H2O band 12 done" &
fi

if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_s ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_s*
  Ccorr_k -C 17 2.5e-1 2.5e2 -F ../${PT_FILE} -D $HITRAN_H2O \
    -P 7 -R 2 ${NBAND} -c 2500.0 -i 0.1 \
    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
    -k -s ${SPECFILE} ${WGT} -q -r ${REF_PT_FILE} \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_s -m ${K_COEFF_DIR}/h2o_l${NBAND}_sm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_slog \
    && echo "H2O self-broadened continuum done"
fi

wait

echo "All done"

exit 0
