#!/bin/bash

NBANDS="350" # Number of bands
SP_ID="dsa_ar" # Spectral file ID
PT_FILE="pt663" # P-T grid

COL_H2O="1.0e+02" # 1 bar atmosphere
COL_CO2="1.6e+02" # 1% CO2 in a 1 bar atmosphere
COL_CH4="5.8e+01" # 1% CH4 in a 1 bar atmosphere
COL_TIDY_H2O="2.5e1" # 1 bar atmosphere

. ../set_paths_lw

# Create name of spectral file
SPEC_FILE="sp_lw_${NBANDS}_${SP_ID}"

mkdir -p ${SPEC_FILE_DIR}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}_k

# Construct spectral file
prep_spec << EOF
${SPEC_FILE}_skel
n
${SPEC_FILE_DIR}/${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_l${NBANDS}_l
9
${K_COEFF_DIR}/h2o_l${NBANDS}_s
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_l
5
y
${K_COEFF_DIR}/ch4_l${NBANDS}_l
6
n
t
1 500
500
-1
EOF

# Add cloud optical properties
prep_spec << EOF
${SPEC_FILE_DIR}/${SPEC_FILE}
a
10
5
${CLD_DIR}/fit_lw_drop5_${NBANDS}
7.60000E-06 5.00000E-05
12
8
${CLD_DIR}/fit_lw_ice8_${NBANDS}
1.30000E-05 3.10000E-04
-1
EOF

# Remove weak absorbers in bands (up to 1% CO2 and CH4) and set major absorbers
tidy_90 << EOF
${SPEC_FILE_DIR}/${SPEC_FILE}
o
1
${COL_H2O}
${COL_CO2}
${COL_CH4}
0.99990
6
${COL_TIDY_H2O}
${COL_CO2}
${COL_CH4}
-1
EOF
