#!/bin/bash

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.

NBANDS="16" # Number of bands
TOL="-b 2.0e-3" # Tolerance for k-coefficients
SP_ID="ar_dsa" # Spectral file ID
SRC_FUNC="lw" # Choose between long-wave (lw) and short-wave (sw)

SPEC_FILE_DIR="/Users/damundse/Spectral_files/${SP_ID}"
SPEC_FILE="sp_${SRC_FUNC}_${NBANDS}_${SP_ID}"

# Charnay et al. Case A
# TIDY_SP_ID="ara_dsa"
# TIDY_SPEC_FILE="sp_${SRC_FUNC}_${NBANDS}_${TIDY_SP_ID}"
# rm -f ${SPEC_FILE_DIR}/${TIDY_SPEC_FILE}
# tidy_90 << EOF
# ${SPEC_FILE_DIR}/${SPEC_FILE}
# n
# ${SPEC_FILE_DIR}/${TIDY_SPEC_FILE}
# 1
# 2.5e+01
# 1.4e+01
# 5.2e+00
# 0.99990
# 6
# 2.5e+01
# 1.4e+01
# 5.2e+00
# -1
# EOF

# Charnay et al. Case B
TIDY_SP_ID="arb_dsa" # Spectral file ID of tidy file
TIDY_SPEC_FILE="sp_${SRC_FUNC}_${NBANDS}_${TIDY_SP_ID}"
rm -f ${SPEC_FILE_DIR}/${TIDY_SPEC_FILE}
tidy_90 << EOF
${SPEC_FILE_DIR}/${SPEC_FILE}
n
${SPEC_FILE_DIR}/${TIDY_SPEC_FILE}
1
2.5e+01
1.6e+02
1.2e+01
0.99990
6
2.5e+01
1.6e+02
1.2e+01
-1
EOF

# 1% CO2 and CH4
# tidy_90 << EOF
# ${SPEC_FILE_DIR}/${SPEC_FILE}
# n
# ${SPEC_FILE_DIR}/${TIDY_SPEC_FILE}
# 1
# 2.5e+01
# 1.6e+02
# 5.8e+01
# 0.99990
# 6
# 2.5e+01
# 1.6e+02
# 5.8e+01
# -1
# EOF