#!/bin/bash

# This script creates the k-coefficients.

SP_ID="dsa_mars"
NBAND="17"
WGT="+p"

# For a 10 bar atmosphere
PT_FILE="pt793"
COL_H2O="1.0e+03"
COL_CO2="1.0e+05" # 1e6 ppmv in a 10 bar atmosphere
COL_H2OC="100.0" # 10 bar atmosphere
COL_CO2C="1.0e6" # 1e6 ppmv in a 10 bar atmosphere

. ../set_paths_lw

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"

# Water vapour continuum uses CAVIAR data contained within the
# suite ($RAD_DATA/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script should be run after the LbL files have been created
# by running the script for the 350 band file.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Create skeleton spectral file
SPECFILE="sp_lw_${NBAND}_${SP_ID}_skel"
rm -f ${SPECFILE}
. mk_sp_lw_${NBAND}_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

# Gases

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_1-6l ] ; then
  echo "CO2 band 1-6"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_1-6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 1 6 -c 50000.0 -i 0.1 -l 2 ${COL_CO2} -b 2.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_1-6l \
    -m ${K_COEFF_DIR}/co2_l${NBAND}_1-6lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf1.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_1-6log \
    && echo "CO2 band 1-6 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_7l ] ; then
  echo "CO2 band 7"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 7 7 -c 50000.0 -i 0.1 -l 2 ${COL_CO2} -b 1.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_7l -m ${K_COEFF_DIR}/co2_l${NBAND}_7lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf1.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_7log \
    && echo "CO2 band 7 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_8-9l ] ; then
  echo "CO2 band 8-9"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_8-9l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 8 9 -c 50000.0 -i 0.1 -l 2 ${COL_CO2} -b 2.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_8-9l \
    -m ${K_COEFF_DIR}/co2_l${NBAND}_8-9lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf1.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_8-9log \
    && echo "CO2 band 8-9 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_10-17l ] ; then
  echo "CO2 band 10-17"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_10-17l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 10 17 -c 50000.0 -i 0.1 -l 2 ${COL_CO2} -n 5 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_10-17l \
    -m ${K_COEFF_DIR}/co2_l${NBAND}_10-17lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf1.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_10-17log \
    && echo "CO2 band 10-17 done" &
fi

echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_1-4l ] ; then
  echo "H2O band 1-4"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_1-4l*
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_map.nc
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 1 4 -c 2500.0 -i 0.1 -l 1 ${COL_H2O} -b 2.0e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_1-4l \
    -m ${K_COEFF_DIR}/h2o_l${NBAND}_1-4lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_1-4log && echo "H2O band 1-4 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_5-6l ] ; then
  echo "H2O band 5-6"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_5-6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 5 6 -c 2500.0 -i 0.1 -l 1 ${COL_H2O} -b 4.0e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_5-6l \
    -m ${K_COEFF_DIR}/h2o_l${NBAND}_5-6lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_5-6log && echo "H2O band 5-6 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_7-17l ] ; then
  echo "H2O band 7-17"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_7-17l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 7 17 -c 2500.0 -i 0.1 -l 1 ${COL_H2O} -n 5 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_7-17l \
    -m ${K_COEFF_DIR}/h2o_l${NBAND}_7-17lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_7-17log && echo "H2O band 7-17 done"
fi


if [ ! -s ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_1-17c ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_1-17c*
  Ccorr_k -F ../pt_cont \
    -R 1 17 -c 2500.0 -i 0.1 \
    -ct 1 1 ${COL_H2OC} -t 1.0e-3 \
    -e ${RAD_DATA}/continua/caviar_s296 ${RAD_DATA}/continua/caviar_s260 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_1-17c \
    -m ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_1-17cm \
    -L ${ABS_COEFF_DIR}/h2o-h2o_sbc_lw.nc \
    -lw ${K_COEFF_DIR}/h2o_l${NBAND}_map.nc \
     > ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_1-17clog \
     && echo "H2O self-broadened continuum done"
fi


if [ ! -s ${K_COEFF_DIR}/co2-co2_l${NBAND}_1-17c ] ; then
  echo "CO2-CO2 CIA"
  rm -f ${K_COEFF_DIR}/co2-co2_l${NBAND}_1-17c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/co2-co2.cia \
    -R 1 17 -c 2500.0 -i 1.0 \
    -ct 2 2 ${COL_CO2C} -t 1.0e-2 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2-co2_l${NBAND}_1-17c \
    -m ${K_COEFF_DIR}/co2-co2_l${NBAND}_1-17cm \
    -L ${ABS_COEFF_DIR}/co2-co2_lbl_lw.nc \
     > ${K_COEFF_DIR}/co2-co2_l${NBAND}_1-17clog \
     && echo "CO2-CO2 CIA done"
fi

wait

echo "All done"

exit 0
