#!/bin/bash

NBAND="17" # Number of bands
SP_ID="dsa_mars" # Spectral file ID

# For a 10 bar atmosphere
PT_FILE="pt793"
COL_H2O="1.0e+03"
COL_CO2="1.0e+05" # 1e6 ppmv in a 10 bar atmosphere
COL_H2OC="100.0" # 10 bar atmosphere
COL_CO2C="1.0e6" # 1e6 ppmv in a 10 bar atmosphere

. ../set_paths_lw

# Create name of spectral file
SPEC_FILE="sp_lw_${NBAND}_${SP_ID}"

mkdir -p ${SPEC_FILE_DIR}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}_k

# Construct spectral file

prep_spec << EOF
sp_lw_${NBAND}_${SP_ID}_skel
n
${SPEC_FILE_DIR}/${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_l${NBAND}_1-4l
5
y
${K_COEFF_DIR}/h2o_l${NBAND}_5-6l
5
y
${K_COEFF_DIR}/h2o_l${NBAND}_7-17l
19
${K_COEFF_DIR}/h2o-h2o_l${NBAND}_1-17c
5
y
${K_COEFF_DIR}/co2_l${NBAND}_1-6l
5
y
${K_COEFF_DIR}/co2_l${NBAND}_7l
5
y
${K_COEFF_DIR}/co2_l${NBAND}_8-9l
5
y
${K_COEFF_DIR}/co2_l${NBAND}_10-17l
19
y
${K_COEFF_DIR}/co2-co2_l${NBAND}_1-17c
6
n
t
1 500
500
-1
EOF

# Add ice cloud optical properties only
prep_spec << EOF
${SPEC_FILE_DIR}/${SPEC_FILE}
a
10
5
${CLD_COEFF_DIR}/fit_lw_drop5_${NBAND}
1.50000E-06 5.00000E-05
12
8
${CLD_COEFF_DIR}/fit_lw_ice8_${NBAND}
8.00000E-06 3.20000E-04
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
tidy_90 << EOF
${SPEC_FILE_DIR}/${SPEC_FILE}
o
1
${COL_H2O}
${COL_CO2}
${COL_H2OC}
${COL_CO2C}
0.99990
6
${COL_H2O}
${COL_CO2}
${COL_H2OC}
${COL_CO2C}
n
8
1
0
-1
EOF

exit 0
