#!/bin/bash

NBAND="17" # Number of bands
SP_ID="dsa_mars" # Spectral file ID

# For a 10 bar atmosphere
PT_FILE="pt793"
COL_H2O="1.0e+03"
COL_CO2="1.0e+05" # 1e6 ppmv in a 10 bar atmosphere
COL_H2OC="100.0" # 10 bar atmosphere
COL_CO2C="1.0e6" # 1e6 ppmv in a 10 bar atmosphere

. ../set_paths_lw

################################################################################
# Calculate k-coefficients
################################################################################

echo "Calculating k-coefficients."

# Set paths to files
HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Create skeleton spectral file
SPECFILE="sp_lw_${NBANDS}_${SP_ID}_skel"
rm -f ${SPECFILE}
. mk_sp_lw_${NBANDS}_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_1-6l ] ; then
  echo "CO2 band 1-6"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_1-6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 1 6 -c 50000.0 -i 0.1 -l 2 1.0e+05 -b 2.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_1-6l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_1-6lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf1.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_1-6log \
    && echo "CO2 band 1-6 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_7l ] ; then
  echo "CO2 band 7"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 7 7 -c 50000.0 -i 0.1 -l 2 1.0e+06 -b 1.2e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_7l -m ${K_COEFF_DIR}/co2_l${NBANDS}_7lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf1.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_7log \
    && echo "CO2 band 7 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_8-9l ] ; then
  echo "CO2 band 8-9"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_8-9l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 8 9 -c 50000.0 -i 0.1 -l 2 1.0e+05 -b 2.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_8-9l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_8-9lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf1.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_8-9log \
    && echo "CO2 band 8-9 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_10-16l ] ; then
  echo "CO2 band 10-16"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_10-16l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 10 16 -c 50000.0 -i 0.1 -l 2 1.0e+05 -n 5 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_10-16l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_10-16lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf1.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_10-16log \
    && echo "CO2 band 10-16 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_17l ] ; then
  echo "CO2 band 17"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_17l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 17 17 -c 50000.0 -i 0.1 -l 2 1.0e+05 -n 10 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_17l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_17lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf1.0.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_17log \
    && echo "CO2 band 17 done" &
fi

echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_1-4l ] ; then
  echo "H2O band 1-4"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_1-4l*
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_map.nc
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 1 4 -c 2500.0 -i 0.1 -l 1 1.0e+03 -b 2.0e-3 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_1-4l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_1-4lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_1-4log && echo "H2O band 1-4 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_5-6l ] ; then
  echo "H2O band 5-6"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_5-6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 5 6 -c 2500.0 -i 0.1 -l 1 1.0e+03 -b 4.0e-3 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_5-6l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_5-6lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_5-6log && echo "H2O band 5-6 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_7-17l ] ; then
  echo "H2O band 7-17"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_7-17l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 7 17 -c 2500.0 -i 0.1 -l 1 1.0e+03 -n 5 \
    -s ${SPECFILE} +p -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_7-17l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_7-17lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_7-17log && echo "H2O band 7-17 done"
fi


if [ ! -s ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-17c ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-17c*
  Ccorr_k -F ../pt_cont \
    -R 1 17 -c 2500.0 -i 0.1 \
    -ct 1 1 100.0 -t 1.0e-3 \
    -e ${RAD_DATA}/continua/caviar_s296 ${RAD_DATA}/continua/caviar_s260 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-17c \
    -m ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-17cm \
    -L ${ABS_COEFF_DIR}/h2o-h2o_lbl_lw.nc \
    -lw ${K_COEFF_DIR}/h2o_l${NBANDS}_map.nc \
     > ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-17clog \
     && echo "H2O self-broadened continuum done"
fi


if [ ! -s ${K_COEFF_DIR}/co2-co2_l${NBANDS}_1-17c ] ; then
  echo "CO2-CO2 CIA"
  rm -f ${K_COEFF_DIR}/co2-co2_l${NBANDS}_1-17c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/co2-co2.cia \
    -R 1 17 -c 2500.0 -i 1.0 \
    -ct 2 2 1.0e6 -t 1.0e-2 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2-co2_l${NBANDS}_1-17c \
    -m ${K_COEFF_DIR}/co2-co2_l${NBANDS}_1-17cm \
    -L ${ABS_COEFF_DIR}/co2-co2_lbl_lw.nc \
     > ${K_COEFF_DIR}/co2-co2_l${NBANDS}_1-17clog \
     && echo "CO2-CO2 CIA done"
fi

wait
echo "Calculation of k-coefficients completed."

################################################################################
# Calculate optical properties
################################################################################

echo "Calculating cloud optical properties."

mkdir -p ${CLD_COEFF_DIR}

if [ ! -s ${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS} ] ; then
  rm -f ${CLD_COEFF_DIR}/mon_lw_drop5_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -t -p 250 \
    -f 5 ${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_lw_drop5_${NBANDS} 1.e3 \
    ${RAD_DATA}/cloud/scatter_drop_type5
fi
if [ ! -s ${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS} ] ; then
  rm -f ${CLD_COEFF_DIR}/mon_lw_ice8_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -w -p 250 \
    -f 12 ${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_lw_ice8_${NBANDS} 920 \
    ${RAD_DATA}/cloud/scatter_ice_lw_type8
fi

echo "Calculation of cloud optical properties completed."

################################################################################
# Create spectral file
################################################################################

echo "Creating spectral file."

# Create name of spectral file
SPEC_FILE="sp_lw_${NBANDS}_${SP_ID}"

mkdir -p ${SPEC_FILE_DIR}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}_k

# Construct spectral file

prep_spec << EOF > mk_sp_lw_${NBANDS}_${SP_ID}_out
sp_lw_${NBANDS}_${SP_ID}_skel
n
${SPEC_FILE_DIR}/${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_l${NBANDS}_1-4l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_5-6l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_7-17l
19
${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-17c
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_1-6l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_7l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_8-9l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_10-16l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_17l
19
y
${K_COEFF_DIR}/co2-co2_l${NBANDS}_1-17c
6
n
t
1 500
500
-1
EOF

# Add ice cloud optical properties only
prep_spec << EOF >> mk_sp_lw_${NBANDS}_${SP_ID}_out
${SPEC_FILE_DIR}/${SPEC_FILE}
a
10
5
${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS}
1.50000E-06 5.00000E-05
12
8
${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS}
8.00000E-06 3.20000E-04
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
tidy_90 << EOF >> mk_sp_lw_${NBANDS}_${SP_ID}_out
${SPEC_FILE_DIR}/${SPEC_FILE}
o
1
${COL_H2O}
${COL_CO2}
${COL_H2OC}
${COL_CO2C}
0.99990
6
${COL_H2O}
${COL_CO2}
${COL_H2OC}
${COL_CO2C}
n
8
1
0
-1
EOF

echo "Spectral file ${SPEC_FILE} created. All done."
echo "Please check mk_sp_lw_${NBANDS}_${SP_ID}_out for errors."

exit 0
