#!/bin/bash

# This script creates the k-coefficients.

SP_ID="dsa_arcc"
NBAND="17"
PT_FILE="pt663"
WGT="+p"

. ../set_paths_lw

HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"

# Water vapour continuum uses CAVIAR data contained within the
# suite ($RAD_DATA/continua).

# Aerosol and cloud parametrisations are those used operationally
# in the Met Office from GA3.0 (see also $RAD_DIR/examples/aerosols,
# $RAD_DIR/examples/droplets).

# Note this script should be run after the LbL files have been created
# by running the script for the 350 band file.

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Create skeleton spectral file
SPECFILE="sp_lw_${NBAND}_${SP_ID}_skel"
rm -f ${SPECFILE}
. mk_sp_lw_${NBAND}_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

# Gases

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_1l ] ; then
  echo "CO2 band 1"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_1l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 1 1 -c 2500.0 -i 0.1 -l 2 1.6e3 -n 1 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_1l -m ${K_COEFF_DIR}/co2_l${NBAND}_1lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_1log \
    && echo "CO2 band 1 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_2l ] ; then
  echo "CO2 band 2"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 2 2 -c 50000.0 -i 0.1 -l 2 1.6e3 -n 5 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_2l -m ${K_COEFF_DIR}/co2_l${NBAND}_2lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_2log \
    && echo "CO2 band 2 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_3-4l ] ; then
  echo "CO2 band 3-4"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_3-4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 3 4 -c 2500.0 -i 0.1 -l 2 1.6e3 -b 2.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_3-4l \
    -m ${K_COEFF_DIR}/co2_l${NBAND}_3-4lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_3-4log \
    && echo "CO2 band 3-4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_5l ] ; then
  echo "CO2 band 5"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 5 5 -c 2500.0 -i 0.1 -l 2 1.6e4 -b 1.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_5l -m ${K_COEFF_DIR}/co2_l${NBAND}_5lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_5log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_6-9l ] ; then
  echo "CO2 band 6-9"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_6-9l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 6 9 -c 2500.0 -i 0.1 -l 2 1.6e3 -b 2.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_6-9l \
    -m ${K_COEFF_DIR}/co2_l${NBAND}_6-9lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_6-9log \
    && echo "CO2 band 6-9 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_10l ] ; then
  echo "CO2 band 10"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_10l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 10 10 -c 2500.0 -i 0.1 -l 2 1.6e3 -n 1 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_10l \
    -m ${K_COEFF_DIR}/co2_l${NBAND}_10lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_10log \
    && echo "CO2 band 10 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_11-15l ] ; then
  echo "CO2 band 11-15"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_11-15l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 11 15 -c 2500.0 -i 0.1 -l 2 1.6e3 -n 5 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_11-15l \
    -m ${K_COEFF_DIR}/co2_l${NBAND}_11-15lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_11-15log \
    && echo "CO2 band 11-15 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_16l ] ; then
  echo "CO2 band 16"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_10l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 16 16 -c 2500.0 -i 0.1 -l 2 1.6e4 -n 10 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_16l \
    -m ${K_COEFF_DIR}/co2_l${NBAND}_16lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_16log \
    && echo "CO2 band 16 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBAND}_17l ] ; then
  echo "CO2 band 17"
  rm -f ${K_COEFF_DIR}/co2_l${NBAND}_17l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 17 17 -c 2500.0 -i 0.1 -l 2 1.6e3 -n 5 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/co2_l${NBAND}_17l \
    -m ${K_COEFF_DIR}/co2_l${NBAND}_17lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBAND}_17log \
    && echo "CO2 band 17 done" &
fi

if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_1-8l ] ; then
  echo "CH4 band 1-8"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_1-8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 1 8 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 1 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_1-8l \
    -m ${K_COEFF_DIR}/ch4_l${NBAND}_1-8lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_1-8log \
    && echo "CH4 band 1-8 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_9l ] ; then
  echo "CH4 band 9"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_9l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 9 9 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 5 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_9l \
    -m ${K_COEFF_DIR}/ch4_l${NBAND}_9lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_9log \
    && echo "CH4 band 9 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_10-13l ] ; then
  echo "CH4 band 10-13"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_10-13l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 10 13 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 8 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_10-13l \
    -m ${K_COEFF_DIR}/ch4_l${NBAND}_10-13lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_10-13log \
    && echo "CH4 band 10-13 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_14-15l ] ; then
  echo "CH4 band 14-15"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_14-15l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 14 15 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 3 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_14-15l \
    -m ${K_COEFF_DIR}/ch4_l${NBAND}_14-15lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_14-15log \
    && echo "CH4 band 14-15 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBAND}_16-17l ] ; then
  echo "CH4 band 16-17"
  rm -f ${K_COEFF_DIR}/ch4_l${NBAND}_16-17l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 16 17 -c 2500.0 -i 0.1 -l 6 5.8e1 -n 5 \
    -s ${SPECFILE} ${WGT} -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBAND}_16-17l \
    -m ${K_COEFF_DIR}/ch4_l${NBAND}_16-17lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBAND}_16-17log \
    && echo "CH4 band 16-17 done" &
fi

echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_1-2l ] ; then
  echo "H2O band 1-2"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_1-2l*
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_map.nc
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 1 2 -c 2500.0 -i 0.1 -l 1 1.0e2 -b 2.0e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_1-2l \
    -m ${K_COEFF_DIR}/h2o_l${NBAND}_1-2lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_1-2log && echo "H2O band 1-2 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_3-4l ] ; then
  echo "H2O band 3-4"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_3-4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 3 4 -c 2500.0 -i 0.1 -l 1 1.0e2 -b 4.0e-3 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_3-4l \
    -m ${K_COEFF_DIR}/h2o_l${NBAND}_3-4lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_3-4log && echo "H2O band 3-4 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBAND}_5-17l ] ; then
  echo "H2O band 5-17"
  rm -f ${K_COEFF_DIR}/h2o_l${NBAND}_5-17l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 5 17 -c 2500.0 -i 0.1 -l 1 1.0e2 -n 5 \
    -s ${SPECFILE} ${WGT} -lk \
    -k -x $RAD_DATA/continua/caviar_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBAND}_5-17l \
    -m ${K_COEFF_DIR}/h2o_l${NBAND}_5-17lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBAND}_map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBAND}_5-17log && echo "H2O band 5-17 done"
fi


if [ ! -s ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_2-17c ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_2-17c*
  Ccorr_k -F ../pt_cont \
    -R 1 17 -c 2500.0 -i 0.1 \
    -ct 1 1 10.0 -t 1.0e-3 \
    -e ${RAD_DATA}/continua/caviar_s296 ${RAD_DATA}/continua/caviar_s260 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_2-17c \
    -m ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_2-17cm \
    -L ${ABS_COEFF_DIR}/h2o-h2o_lbl_lw.nc \
    -lw ${K_COEFF_DIR}/h2o_l${NBAND}_map.nc \
     > ${K_COEFF_DIR}/h2o-h2o_l${NBAND}_2-17clog \
     && echo "H2O self-broadened continuum done"
fi


if [ ! -s ${K_COEFF_DIR}/co2-co2_l${NBAND}_1-17c ] ; then
  echo "CO2-CO2 CIA"
  rm -f ${K_COEFF_DIR}/co2-co2_l${NBAND}_1-17c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/co2-co2.cia \
    -R 1 17 -c 2500.0 -i 1.0 \
    -ct 2 2 1.0e2 -t 1.0e-2 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2-co2_l${NBAND}_1-17c \
    -m ${K_COEFF_DIR}/co2-co2_l${NBAND}_1-17cm \
    -L ${ABS_COEFF_DIR}/co2-co2_lbl_lw.nc \
     > ${K_COEFF_DIR}/co2-co2_l${NBAND}_1-17clog \
     && echo "CO2-CO2 CIA done"
fi

wait

echo "All done"

exit 0
