#!/bin/bash
# Defines paths to all needed input and output data for generation of
# long-wave spectral files.

HOST=`uname -n`
if [ ${HOST:0:4} == "dali" ]; then
  HOST="dali"
  SOCRATES_DIR="/discover/nobackup/projects/giss/socrates"
else
  SOCRATES_DIR="/scr2/socrates"
fi

HITRAN_DIR="${SOCRATES_DIR}/hitran"
CONT_DIR="${SOCRATES_DIR}/continua"
K_COEFF_DIR="${SOCRATES_DIR}/data/sp_cmp/lw_${SP_ID}/${PT_FILE}"
ABS_COEFF_DIR="${SOCRATES_DIR}/data/abs_coeff"
SOLAR_SPEC_DIR="${SOCRATES_DIR}/stellar_spectra"
CLD_COEFF_DIR="${SOCRATES_DIR}/data/sp_cmp/lw_${SP_ID}/cld"

if [ -n "${SP_FLDR}" ] ; then
  SPEC_FILE_DIR="${SOCRATES_DIR}/spectral_files/sp_lw_${SP_FLDR}"
else
  SPEC_FILE_DIR="${SOCRATES_DIR}/spectral_files/sp_lw_${SP_ID}"
fi

# If on discover (dali node) put cloud optical properties in
# in working directory.
if [ ${HOST} == "dali" ]; then
  CLD_COEFF_DIR="lw_${SP_ID}/cld"
fi
