#!/bin/bash
# Defines paths to all needed input and output data for generation of
# short-wave spectral files.

SOCRATES_DIR="/scr2/socrates"

HITRAN_DIR="${SOCRATES_DIR}/hitran"
CONT_DIR="${SOCRATES_DIR}/continua"
K_COEFF_DIR="${SOCRATES_DIR}/data/sp_cmp/sw_${SP_ID}/${PT_FILE}/${SOLAR_SPEC}"
SW_DATA="${SOCRATES_DIR}/data/abs_coeff"
SOLAR_SPEC_DIR="${SOCRATES_DIR}/stellar_spectra"
CLD_COEFF_DIR="${SOCRATES_DIR}/data/sp_cmp/sw_${SP_ID}/cld/${SOLAR_SPEC}"

if [ -n "${SP_FLDR}" ] ; then
  SPEC_FILE_DIR="${SOCRATES_DIR}/spectral_files/sp_sw_${SP_FLDR}"
else
  SPEC_FILE_DIR="${SOCRATES_DIR}/spectral_files/sp_sw_${SP_ID}"
fi
