#!/bin/bash
# Defines paths to all needed input and output data for generation of
# diagnostic spectral files.

SOCRATES_DIR="/scr2/socrates"

HITRAN_DIR="${SOCRATES_DIR}/hitran"
CONT_DIR="${SOCRATES_DIR}/continua"
K_COEFF_DIR="${HOME}/socrates_data/sp_cmp/diag_${SP_ID}/${PT_FILE}"
ABS_COEFF_DIR="${SOCRATES_DIR}/data/abs_coeff"
SOLAR_SPEC_DIR="${SOCRATES_DIR}/stellar_spectra"
CLD_COEFF_DIR="${HOME}/socrates_data/sp_cmp/diag_${SP_ID}/cld"
SPEC_FILE_DIR="${HOME}/spectral_files/sp_diag"
