#!/bin/bash
# Defines paths to all needed input and output data for generation of
# short-wave spectral files.

HITRAN_DIR="/scr2/socrates/hitran"
CONT_DIR="/scr2/socrates/continua"
K_COEFF_DIR="/scr2/socrates/data/sp_cmp/lw_${SP_ID}/${PT_FILE}"
ABS_COEFF_DIR="/scr2/socrates/data/abs_coeff"
SOLAR_SPEC_DIR="/scr2/socrates/stellar_spectra"
CLD_COEFF_DIR="/scr2/socrates/data/sp_cmp/lw_${SP_ID}/cld"

if [ -n "${SP_FLDR}" ] ; then
  SPEC_FILE_DIR="/scr2/socrates/spectral_files/sp_lw_${SP_FLDR}"
else
  SPEC_FILE_DIR="/scr2/socrates/spectral_files/sp_lw_${SP_ID}"
fi
