#!/bin/bash

# Setting for k-coefficient calculation
SP_ID="dsa_ar_fujii2017_ckd"
SP_FLDR="dsa_ar_fujii2017_ckd"
NBANDS="280"
SOLAR_SPEC="k186"
PT_FILE="pt663"
TOL="-b 1.0e-3"
BAND_NIR_START="66" # 5.000000000E-07 m

# For molecules with near-IR absorption, the index of the first band for which
# to calculate absorption
BAND_FIRST_H2O="30"  # 25710 cm-1 = 3.88953714507973e-07 m
BAND_FIRST_CO2="104" # 12784 cm-1 = 7.82224331232518e-07 m
BAND_FIRST_CH4="104" # 11501 cm-1 = 8.69423652540053e-07 m

# Column masses for all molecules for k-coefficient calculation
COL_MASS_K_H2O="1.0e2" # 1.0e2 for 1.0 bar atm
COL_MASS_K_CO2="1.6e2" # 1.6e2 for 1.0 bar atm
COL_MASS_K_CH4="5.8e1" # 5.8e1 for 1.0 bar atm

# Column masses for all molecules for eliminating weak absorbers
COL_MASS_ELIM_H2O="2.5e1" # 2.5e1 for 1.0 bar atm
COL_MASS_ELIM_CO2="1.6e2" # 1.6e2 for 1.0 bar atm
COL_MASS_ELIM_CH4="5.8e1" # 5.8e1 for 1.0 bar atm

# Column masses for all molecules for eliminating weak absorbers
COL_MASS_STMJ_H2O="2.5e1" # 2.5e1 for 1.0 bar atm
COL_MASS_STMJ_CO2="1.6e2" # 1.6e2 for 1.0 bar atm
COL_MASS_STMJ_CH4="5.8e1" # 5.8e1 for 1.0 bar atm
