#!/bin/bash

NBANDS="17" # Number of bands
SP_ID="dsa_arva" # Spectral file ID
PT_FILE="pt663" # P-T grid

. ../set_paths_lw

################################################################################
# Calculate k-coefficients
################################################################################

echo "Calculating k-coefficients."

# Set paths to files
HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
HITRAN_N2O="$HITRAN_DIR/04_hit08.par"
HITRAN_CH4="$HITRAN_DIR/06_hit12.par"

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Create skeleton spectral file
SPECFILE="sp_lw_${NBANDS}_${SP_ID}_skel"
rm -f ${SPECFILE}
. mk_sp_lw_${NBANDS}_${SP_ID}_skel > /dev/null

# Create directory for k-coefficients
mkdir -p ${K_COEFF_DIR}

echo "Jobs running in background:"

if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_1l ] ; then
  echo "CO2 band 1"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_1l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 1 1 -c 2500.0 -i 0.1 -l 2 1.6e3 -n 1 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_1l -m ${K_COEFF_DIR}/co2_l${NBANDS}_1lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_1log \
    && echo "CO2 band 1 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_2l ] ; then
  echo "CO2 band 2"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 2 2 -c 50000.0 -i 0.1 -l 2 1.6e3 -n 5 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_2l -m ${K_COEFF_DIR}/co2_l${NBANDS}_2lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_2log \
    && echo "CO2 band 2 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_3-4l ] ; then
  echo "CO2 band 3-4"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_3-4l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 3 4 -c 2500.0 -i 0.1 -l 2 1.6e3 -b 2.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_3-4l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_3-4lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_3-4log \
    && echo "CO2 band 3-4 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_5l ] ; then
  echo "CO2 band 5"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 5 5 -c 2500.0 -i 0.1 -l 2 1.6e3 -b 2.0e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_5l -m ${K_COEFF_DIR}/co2_l${NBANDS}_5lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_5log \
    && echo "CO2 band 5 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_6l ] ; then
  echo "CO2 band 6"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_6l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 6 6 -c 2500.0 -i 0.1 -l 2 1.6e3 -b 1.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_6l -m ${K_COEFF_DIR}/co2_l${NBANDS}_6lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_6log \
    && echo "CO2 band 6 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_7-10l ] ; then
  echo "CO2 band 7-10"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_7-10l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 7 10 -c 2500.0 -i 0.1 -l 2 1.6e3 -t 7.5e-3 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_7-10l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_7-10lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_7-10log \
    && echo "CO2 band 7-10 done" &
fi
if [ ! -s ${K_COEFF_DIR}/co2_l${NBANDS}_11-17l ] ; then
  echo "CO2 band 11-17"
  rm -f ${K_COEFF_DIR}/co2_l${NBANDS}_11-17l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
    -R 11 17 -c 2500.0 -i 0.1 -l 2 1.6e3 -n 5 \
    -sb gas_fractions -lp 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2_l${NBANDS}_11-17l \
    -m ${K_COEFF_DIR}/co2_l${NBANDS}_11-17lm \
    -L ${ABS_COEFF_DIR}/co2_sblbl_lw_${PT_FILE}_gf0.0-0.1.nc \
    > ${K_COEFF_DIR}/co2_l${NBANDS}_11-17log \
    && echo "CO2 band 11-17 done" &
fi


if [ ! -s ${K_COEFF_DIR}/n2o_l${NBANDS}_1-2l ] ; then
  echo "N2O band 1-2"
  rm -f ${K_COEFF_DIR}/n2o_l${NBANDS}_1-2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 1 2 -c 2500.0 -i 0.1 -l 4 16 -n 1 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2o_l${NBANDS}_1-2l \
    -m ${K_COEFF_DIR}/n2o_l${NBANDS}_1-2lm \
    -L ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/n2o_l${NBANDS}_1-2log \
    && echo "N2O band 1-2 done" &
fi
if [ ! -s ${K_COEFF_DIR}/n2o_l${NBANDS}_3-7l ] ; then
  echo "N2O band 3-7"
  rm -f ${K_COEFF_DIR}/n2o_l${NBANDS}_3-7l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 3 7 -c 2500.0 -i 0.1 -l 4 16 -b 5.0e-3 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2o_l${NBANDS}_3-7l \
    -m ${K_COEFF_DIR}/n2o_l${NBANDS}_3-7lm \
    -L ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/n2o_l${NBANDS}_3-7log \
    && echo "N2O band 3-7 done" &
fi
if [ ! -s ${K_COEFF_DIR}/n2o_l${NBANDS}_8l ] ; then
  echo "N2O band 8"
  rm -f ${K_COEFF_DIR}/n2o_l${NBANDS}_8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 8 8 -c 2500.0 -i 0.1 -l 4 16 -t 3.0e-3 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2o_l${NBANDS}_8l \
    -m ${K_COEFF_DIR}/n2o_l${NBANDS}_8lm \
    -L ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/n2o_l${NBANDS}_8log \
    && echo "N2O band 8 done" &
fi
if [ ! -s ${K_COEFF_DIR}/n2o_l${NBANDS}_9-10l ] ; then
  echo "N2O band 9-10"
  rm -f ${K_COEFF_DIR}/n2o_l${NBANDS}_9-10l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 9 10 -c 2500.0 -i 0.1 -l 4 16 -t 5.0e-3 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2o_l${NBANDS}_9-10l \
    -m ${K_COEFF_DIR}/n2o_l${NBANDS}_9-10lm \
    -L ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/n2o_l${NBANDS}_9-10log \
    && echo "N2O band 9-12 done" &
fi
if [ ! -s ${K_COEFF_DIR}/n2o_l${NBANDS}_11-12l ] ; then
  echo "N2O band 11-12"
  rm -f ${K_COEFF_DIR}/n2o_l${NBANDS}_11-12l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 11 12 -c 2500.0 -i 0.1 -l 4 16 -t 1.0e-2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2o_l${NBANDS}_11-12l \
    -m ${K_COEFF_DIR}/n2o_l${NBANDS}_11-12lm \
    -L ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/n2o_l${NBANDS}_11-12log \
    && echo "N2O band 11-12 done" &
fi
if [ ! -s ${K_COEFF_DIR}/n2o_l${NBANDS}_13-15l ] ; then
  echo "N2O band 13-15"
  rm -f ${K_COEFF_DIR}/n2o_l${NBANDS}_13-15l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 13 15 -c 2500.0 -i 0.1 -l 4 16 -n 3 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2o_l${NBANDS}_13-15l \
    -m ${K_COEFF_DIR}/n2o_l${NBANDS}_13-15lm \
    -L ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/n2o_l${NBANDS}_13-15log \
    && echo "N2O band 13-15 done" &
fi
if [ ! -s ${K_COEFF_DIR}/n2o_l${NBANDS}_16-17l ] ; then
  echo "N2O band 16-17"
  rm -f ${K_COEFF_DIR}/n2o_l${NBANDS}_16-17l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
    -R 16 17 -c 2500.0 -i 0.1 -l 4 16 -n 5 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/n2o_l${NBANDS}_16-17l \
    -m ${K_COEFF_DIR}/n2o_l${NBANDS}_16-17lm \
    -L ${ABS_COEFF_DIR}/n2o_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/n2o_l${NBANDS}_16-17log \
    && echo "N2O band 16-17 done" &
fi


if [ ! -s ${K_COEFF_DIR}/ch4_l${NBANDS}_1-9l ] ; then
  echo "CH4 band 1-9"
  rm -f ${K_COEFF_DIR}/ch4_l${NBANDS}_1-9l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 1 9 -c 2500.0 -i 0.1 -l 6 5.8e-02 -n 1 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBANDS}_1-9l \
    -m ${K_COEFF_DIR}/ch4_l${NBANDS}_1-9lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBANDS}_1-9log \
    && echo "CH4 band 1-9 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBANDS}_10l ] ; then
  echo "CH4 band 10"
  rm -f ${K_COEFF_DIR}/ch4_l${NBANDS}_10l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 10 10 -c 2500.0 -i 0.1 -l 6 5.8e-02 -n 2 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBANDS}_10l -m ${K_COEFF_DIR}/ch4_l${NBANDS}_10lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBANDS}_10log \
    && echo "CH4 band 10 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBANDS}_11-13l ] ; then
  echo "CH4 band 11-13"
  rm -f ${K_COEFF_DIR}/ch4_l${NBANDS}_11-13l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 11 13 -c 2500.0 -i 0.1 -l 6 5.8e-02 -n 5 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBANDS}_11-13l \
    -m ${K_COEFF_DIR}/ch4_l${NBANDS}_11-13lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBANDS}_11-13log \
    && echo "CH4 band 11-13 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBANDS}_14-15l ] ; then
  echo "CH4 band 14-15"
  rm -f ${K_COEFF_DIR}/ch4_l${NBANDS}_14-15l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 14 15 -c 2500.0 -i 0.1 -l 6 5.8e-02 -n 1 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBANDS}_14-15l \
    -m ${K_COEFF_DIR}/ch4_l${NBANDS}_14-15lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBANDS}_14-15log \
    && echo "CH4 band 14-15 done" &
fi
if [ ! -s ${K_COEFF_DIR}/ch4_l${NBANDS}_16-17l ] ; then
  echo "CH4 band 16-17"
  rm -f ${K_COEFF_DIR}/ch4_l${NBANDS}_16-17l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
    -R 16 17 -c 2500.0 -i 0.1 -l 6 5.8e-02 -n 5 \
    -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/ch4_l${NBANDS}_16-17l \
    -m ${K_COEFF_DIR}/ch4_l${NBANDS}_16-17lm \
    -L ${ABS_COEFF_DIR}/ch4_lbl_lw_${PT_FILE}.nc \
    > ${K_COEFF_DIR}/ch4_l${NBANDS}_16-17log \
    && echo "CH4 band 16-17 done" &
fi

echo "Jobs running in foreground:"

if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_1-2l ] ; then
  echo "H2O band 1-2"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_1-2l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 1 2 -c 2500.0 -i 0.1 -l 1 1.0e2 -b 2.0e-3 \
    -s ${SPECFILE} +p -lk \
    -k -x ${CONT_DIR}/mt_ckd_v3.0_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_1-2l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_1-2lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_1-2log && echo "H2O band 1-2 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_3-5l ] ; then
  echo "H2O band 3-5"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_3-5l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 3 5 -c 2500.0 -i 0.1 -l 1 1.0e2 -b 4.0e-3 \
    -s ${SPECFILE} +p -lk \
    -k -x ${CONT_DIR}/mt_ckd_v3.0_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_3-5l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_3-5lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_3-5log && echo "H2O band 3-5 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_6-8l ] ; then
  echo "H2O band 6-8"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_6-8l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 6 8 -c 2500.0 -i 0.1 -l 1 1.0e2 -n 8 \
    -s ${SPECFILE} +p -lk \
    -k -x ${CONT_DIR}/mt_ckd_v3.0_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_6-8l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_6-8lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_6-8log && echo "H2O band 6-8 done"
fi
if [ ! -s ${K_COEFF_DIR}/h2o_l${NBANDS}_9-17l ] ; then
  echo "H2O band 9-17"
  rm -f ${K_COEFF_DIR}/h2o_l${NBANDS}_9-17l*
  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
    -R 9 17 -c 2500.0 -i 0.1 -l 1 1.0e2 -n 5 \
    -s ${SPECFILE} +p -lk \
    -k -x ${CONT_DIR}/mt_ckd_v3.0_frn \
    -o ${K_COEFF_DIR}/h2o_l${NBANDS}_9-17l \
    -m ${K_COEFF_DIR}/h2o_l${NBANDS}_9-17lm \
    -L ${ABS_COEFF_DIR}/h2o_lbl_lwf_${PT_FILE}.nc \
    -sm ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
    > ${K_COEFF_DIR}/h2o_l${NBANDS}_9-17log && echo "H2O band 9-17 done"
fi


if [ ! -s ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-${NBANDS}c ] ; then
  echo "H2O self-broadened continuum"
  rm -f ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-${NBANDS}c*
  Ccorr_k -F ../pt_cont \
    -R 1 ${NBANDS} -c 2500.0 -i 0.1 \
    -ct 1 1 10.0 -t 1.0e-3 \
    -e ${CONT_DIR}/mt_ckd_v3.0_s296 ${CONT_DIR}/mt_ckd_v3.0_s260 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-${NBANDS}c \
    -m ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-${NBANDS}cm \
    -L ${ABS_COEFF_DIR}/h2o-h2o_lbl_lw.nc \
    -lw ${K_COEFF_DIR}/h2o_l${NBANDS}_1-${NBANDS}map.nc \
     > ${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-${NBANDS}clog \
     && echo "H2O self-broadened continuum done"
fi


if [ ! -s ${K_COEFF_DIR}/co2-co2_l${NBANDS}_1-${NBANDS}c ] ; then
  echo "CO2-CO2 CIA"
  rm -f ${K_COEFF_DIR}/co2-co2_l${NBANDS}_1-${NBANDS}c*
  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/co2-co2.cia \
    -R 1 ${NBANDS} -c 2500.0 -i 1.0 \
    -ct 2 2 1.0e2 -t 1.0e-2 \
    -k -s ${SPECFILE} +p -lk \
    -o ${K_COEFF_DIR}/co2-co2_l${NBANDS}_1-${NBANDS}c \
    -m ${K_COEFF_DIR}/co2-co2_l${NBANDS}_1-${NBANDS}cm \
    -L ${ABS_COEFF_DIR}/co2-co2_lbl_lw.nc \
     > ${K_COEFF_DIR}/co2-co2_l${NBANDS}_1-${NBANDS}clog \
     && echo "CO2-CO2 CIA done" &
fi

wait
echo "Calculation of k-coefficients completed."

################################################################################
# Calculate optical properties
################################################################################

echo "Calculating cloud optical properties."

mkdir -p ${CLD_COEFF_DIR}

if [ ! -s ${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS} ] ; then
  rm -f ${CLD_COEFF_DIR}/mon_lw_drop5_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -t -p 250 \
    -f 5 ${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_lw_drop5_${NBANDS} 1.e3 \
    ${RAD_DATA}/cloud/scatter_drop_type5
fi
if [ ! -s ${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS} ] ; then
  rm -f ${CLD_COEFF_DIR}/mon_lw_ice8_${NBANDS}
  Cscatter_average -s ${SPECFILE} -P 1 -w -p 250 \
    -f 12 ${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS} \
    ${CLD_COEFF_DIR}/mon_lw_ice8_${NBANDS} 920 \
    ${RAD_DATA}/cloud/scatter_ice_lw_type8
fi

echo "Calculation of cloud optical properties completed."

################################################################################
# Create spectral file
################################################################################

echo "Creating spectral file."

# Create name of spectral file
SPEC_FILE="sp_lw_${NBANDS}_${SP_ID}"

mkdir -p ${SPEC_FILE_DIR}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}
rm -f ${SPEC_FILE_DIR}/${SPEC_FILE}_k

# Construct spectral file

prep_spec << EOF > mk_sp_lw_${NBANDS}_${SP_ID}_out
sp_lw_${NBANDS}_${SP_ID}_skel
n
${SPEC_FILE_DIR}/${SPEC_FILE}
5
${K_COEFF_DIR}/h2o_l${NBANDS}_1-2l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_3-5l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_6-8l
5
y
${K_COEFF_DIR}/h2o_l${NBANDS}_9-17l
19
${K_COEFF_DIR}/h2o-h2o_l${NBANDS}_1-17c
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_1l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_2l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_3-4l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_5l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_6l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_7-10l
5
y
${K_COEFF_DIR}/co2_l${NBANDS}_11-17l
19
y
${K_COEFF_DIR}/co2-co2_l${NBANDS}_1-17c
5
y
${K_COEFF_DIR}/n2o_l${NBANDS}_1-2l
5
y
${K_COEFF_DIR}/n2o_l${NBANDS}_3-7l
5
y
${K_COEFF_DIR}/n2o_l${NBANDS}_8l
5
y
${K_COEFF_DIR}/n2o_l${NBANDS}_9-10l
5
y
${K_COEFF_DIR}/n2o_l${NBANDS}_11-12l
5
y
${K_COEFF_DIR}/n2o_l${NBANDS}_13-15l
5
y
${K_COEFF_DIR}/n2o_l${NBANDS}_16-17l
5
y
${K_COEFF_DIR}/ch4_l${NBANDS}_1-9l
5
y
${K_COEFF_DIR}/ch4_l${NBANDS}_10l
5
y
${K_COEFF_DIR}/ch4_l${NBANDS}_11-13l
5
y
${K_COEFF_DIR}/ch4_l${NBANDS}_14-15l
5
y
${K_COEFF_DIR}/ch4_l${NBANDS}_16-17l
6
n
t
1 500
500
-1
EOF

# Add ice cloud optical properties only
prep_spec << EOF >> mk_sp_lw_${NBANDS}_${SP_ID}_out
${SPEC_FILE_DIR}/${SPEC_FILE}
a
10
5
${CLD_COEFF_DIR}/fit_lw_drop5_${NBANDS}
1.50000E-06 5.00000E-05
12
8
${CLD_COEFF_DIR}/fit_lw_ice8_${NBANDS}
8.00000E-06 3.20000E-04
-1
EOF

# Rearrange so the major gas is listed first for each band and
# gases are removed from bands where absorption is very weak.
tidy_90 << EOF >> mk_sp_lw_${NBANDS}_${SP_ID}_out
${SPEC_FILE_DIR}/${SPEC_FILE}
o
8
1
0
1
2.5e1
1.6e3
16
5.8e-2
10.0
1.0e2
0.99990
6
2.5e1
1.6e3
16
5.8e-2
10.0
1.0e2
1.0e+5
n
-1
EOF

. ../set_permissions

echo "Spectral file ${SPEC_FILE} created. All done."
echo "Please check mk_sp_lw_${NBANDS}_${SP_ID}_out for errors."

exit 0
